### ISSUE TITLE
Not working at all

### ISSUE THREAD

**Issue by M1ghty-boy** [Pugmatt/BedrockConnect#100]
trying to get my friends to join my server, just connects them to a default server instead of the bedrockconnect menu

**Comment by martincheck** [comment]
noticed the same thing.  I thought it was the hosted version of this, but then I setup my own instance and it had the same problem.  Interestingly enough, the server I setup seems to work fine when I connect from my PC, but just sends me to the default server on xbox, so something may have changed on the xbox side...

**Comment by rroughton** [comment]
Friend is having a problem connecting, though seems like

Info: xBox One, Minecraft version 1.16.4002.70

His screen seems to hang on the "connecting to server" before reaching the DNS server. I'm not hosting my own, just using the public one.

**Comment by twedcl01** [comment]
I seem to be having the same issue. 

On Switch, I had it working yesterday on the public DNS, but now when I try to connect I just get an "unable to connect to world" message.

Other servers seem to work when I use the default DNS.

**Comment by moroniccoffee1** [comment]
Same issue. Switched to other DNS and able to access featured servers fine. Also the server I want to connect to works on phone and computer but not through here. Hope you get a chance to look at it. PING rate shows as really high.

**Comment by martincheck** [comment]
> noticed the same thing. I thought it was the hosted version of this, but then I setup my own instance and it had the same problem. Interestingly enough, the server I setup seems to work fine when I connect from my PC, but just sends me to the default server on xbox, so something may have changed on the xbox side...

Correction on this, I didn't setup the local version of this server correctly, after redoing this (following the very helpful video tutorial) I know have an azure server hosting my own bedrockconnect instance, and it works just fine.  So it seems like the "hosted" version of this is probably just overwhelmed again.

**Comment by Pugmatt** [comment]
This week, I'll be looking into expanding the public DNS into multiple servers to load balance players in, as the servers been getting hit with larger player counts lately. Thank you for your patience, apologies for the lag.

**Comment by Pugmatt** [comment]
Put up some more servers up today for the original serverlist server to fall back on so the original doesn't get too overwhelmed on busy days. Hopefully this should help the lag and some of the issues that's been happening.

**Comment by martincheck** [comment]
thanks for fixing, looks better now!
