### ISSUE TITLE
Update on Nintendo Switch

### ISSUE THREAD

**Issue by twedcl01** [Pugmatt/BedrockConnect#102]
The most recent update(11/16/2020) for the Switch seems to not be working with BedrockConnect.

I try to open the Server List, but I get an error message that says "Could not connect: outdated server!"
My friend tried to access the server from their Switch and got the same error message.

**Comment by DoctorMacc** [comment]
Addressed through #103. 

You'll likely have to be patient until tomorrow, as that's when the update will drop for everyone else.

**Comment by Pugmatt** [comment]
@DoctorMacc Thanks for committing that.

The public server is now updated to 1.16.100.

**Comment by DoctorMacc** [comment]
Happy to help! :) Hope I saved you a lot of trouble with the CreativeContentPacket.
