### ISSUE TITLE
Unable to see 'Join to view server lists' on Switch or XboxOne

### ISSUE THREAD

**Issue by MattCM** [Pugmatt/BedrockConnect#105]
UK server owner here, so after the 1.16.100 update our clients on Switch and XboxOne are unable to see the 'Join to open server list' on any of the featured servers using the DNS settings as advised. Is it worth setting up our own DNS to try and resolve this, are we the only ones getting this issue? I can see a 1.16.100 update was pushed, however this was before the full rollout of 1.16.100 on all platforms.

**Comment by RedcatPhoenix2** [comment]
Same problem.

**Comment by Pugmatt** [comment]
One of the serverlist servers today was having some difficulties, should be fixed now.

**Comment by DaidoujiChen** [comment]
Same problem.

**Comment by Pugmatt** [comment]
> Same problem.

The servers are currently up and functional. If you're still having the problem, you can try hosting a local instance if you're able to. https://www.youtube.com/watch?v=AW5X7-qnvLk

**Comment by DaidoujiChen** [comment]
![image](https://user-images.githubusercontent.com/670441/99896246-b4e6b800-2cc9-11eb-8e8f-127025bc53bd.jpeg)

**Comment by big-blanco** [comment]
Can confirm PS4 issue is an issue.  Have a weird feeling this is Sony being jerks but I'm no expert.  Would be really awesome to get it working though since PS users can finally access servers.

**Comment by DoctorMacc** [comment]
I looked into PS4 support, since they got featured servers with 1.16.100. My current theory is that BedrockConnect doesn't handle domains other than the featured server domains, and the PS4 is not a fan of that. If this theory is correct, I don't know which domains BedrockConnect needs to resolve.

**Comment by Pugmatt** [comment]
I'll look into this further when I can. For now, anyone on PS4 should be able to join BedrockConnect on PS4 with this method, which is what I've seen commonly before featured servers came out on PS4: https://www.youtube.com/watch?v=ND_VFaAXC8M
The method above can also be replicated by hosting a local BedrockConnect instance on your computer.

**Comment by MattCM** [comment]
Can confirm both Xbox One and Switch now works again - must have just been a blip! thanks @Pugmatt

**Comment by Benhemoth** [comment]
Farthest I can do: change DNS, join BedrockConnect, start joining dedicated server, "You need to authenticate to Microsoft services." I'm stuck. I'm soooo close. lol Trying to help my friends do it without using phones/PCs.

(on ps5 btw)
