### ISSUE TITLE
Duplicate DNS entry

### ISSUE THREAD

**Issue by hafichuk** [Pugmatt/BedrockConnect#107]
It looks like there is a duplicate entry at
https://github.com/Pugmatt/BedrockConnect/blob/5e482f507af8a25951303ae89350c421d7da6085/serverlist-server/src/main/com/pyratron/pugmatt/bedrockconnect/BedrockConnect.java#L96

**Comment by Pugmatt** [comment]
Thanks for pointing this out. It is now fixed in the latest release.
