### ISSUE TITLE
Dns not working

### ISSUE THREAD

**Issue by guruplant** [Pugmatt/BedrockConnect#11]
I have been using this for the last 3 weeks perfectly. Last night 09/03/20 at around 1 am gmt I was kicked from my server. I cannot get back on. Other on my server that use console are having the same issue

**Comment by minerj101** [comment]
Same issue for about half of my server members

**Comment by Pugmatt** [comment]
Make sure the DNS settings are still set correctly on your consoles. Does it just bring you to the regular featured server when trying to join the serverlist?

**Comment by minerj101** [comment]
Yes but it says bad connection and people are not able to join the server 
![F5CD6482-F627-4EDB-A015-EFB4520639BF](https://user-images.githubusercontent.com/61999256/76344976-dc7f2700-62d8-11ea-899e-a79bb91c97c2.jpeg)
![32C48386-358D-40AA-BABE-63C57A074470](https://user-images.githubusercontent.com/61999256/76345009-f4ef4180-62d8-11ea-8bb7-55c32931b1f9.jpeg)
![A1DE51F8-B34C-4394-B532-62CB53281238](https://user-images.githubusercontent.com/61999256/76345076-17815a80-62d9-11ea-99b7-f99dc08efe60.jpeg)

**Comment by guruplant** [comment]
It appears to be fixed.

**Comment by minerj101** [comment]
Did you fix the issue

**Comment by minerj101** [comment]
Will you be active in about a hour

**Comment by minerj101** [comment]
Or 15 minutes

**Comment by minerj101** [comment]
?

**Comment by Pugmatt** [comment]
Please stop spamming this thread, only one message is necessary.  

What country are you located in? It might a connection issue with where your location, and I can look into it from there.

**Comment by minerj101** [comment]
Sorry

**Comment by minerj101** [comment]
The us

**Comment by Pugmatt** [comment]
Just for clarification, the errors are appearing after trying to join the serverlist, and not joining a server from the serverlist correct?

In the next day or two I'll make a video tutorial on how to locally host the DNS and serverlist server, since the issue seems to currently lie in poor connection.

**Comment by guruplant** [comment]
What was happening with us was when selecting a sever in the bedrock server screen before you get to what we call the void world you would get the unable to connect to world error. 

This was before it brought up the server list that you could manually add a server to. Since about 11pm gmt last night things have been working again

**Comment by Pugmatt** [comment]
> The us

Tutorials up. Feel free to give a watch: https://www.youtube.com/watch?v=AW5X7-qnvLk
