### ISSUE TITLE
Switch Player is redirected to the actual featured server rather than the server list

### ISSUE THREAD

**Issue by untojupiter** [Pugmatt/BedrockConnect#112]
This Switch player has changed their DNS settings and still is unable to connect to the server list in order to connect to a Geyser-supported server

**Comment by Pugmatt** [comment]
If they've tried restarted Minecraft and their Switch multiple times, and it still isn't working, they can try the following:

Usually only an issue on Xbox, but turning off IPv6 in router settings sometimes helps: https://www.youtube.com/watch?v=3FhBEI55__s
Or, they host a BedrockConnect instance locally: https://www.youtube.com/watch?v=AW5X7-qnvLk&
