### ISSUE TITLE
Minecraft got updated pls update server

### ISSUE THREAD

**Issue by Kcjsjcjd** [Pugmatt/BedrockConnect#114]
So minecraft 1.16.200 just got released and the server list is now outdated can you please update the server list

**Comment by kmpoppe** [comment]
+1 for this wish, I literally managed to get the serverlist server going this minute ... and then my game updated -.-

Thank you for providing this software @Pugmatt !

**Comment by Bryantdl7** [comment]
New version number is 1.16.200

**Comment by Pugmatt** [comment]
Thank you for your patience. Working on getting it updated.

**Comment by DoctorMacc** [comment]
I have provided a PR if it's of any assistance.

**Comment by Pugmatt** [comment]
The serverlist is now updated to 1.16.200. Thanks for your patience everyone.
