### ISSUE TITLE
[Improvement] Transparency on how to handle updates to Minecraft & BedrockConnect

### ISSUE THREAD

**Issue by Bryantdl7** [Pugmatt/BedrockConnect#115]
As this new update has shown, the world relies on you, friend! 

It would be great to know what parts of the code need to be adjusted to allow for a new version of the bypass server to be released, specifically: 

- What handles pushing the version number? 
- Is there a specific resource you turn to so you know how to update the code? 
- I see the <artifactId>bedrock-v419</artifactId> is something which seems to coincide with the version number, what resource is used to find this info, is it just this and Bedrock_v419.V419_CODEC? 

Documenting how you accomplish these tasks is essential for the longevity of this project, should some day you decide to stop maintaining it, thanks in advance!

**Comment by DoctorMacc** [comment]
I'm happy to do this as well as I'm familiar with BedrockConnect's backend library.

**Comment by Pugmatt** [comment]
Currently, BedrockConnect uses https://github.com/CloudburstMC/Protocol for its protocol needs, so updating typically depends on this library to be updated as well, which the great folks over there are very quick about and know much more than me in that area. :) In terms of updating to the new version for that, if it's an update that doesn't require packet changes it's just changing the Protocol version number in pom.xml and changing the codec variable in Server.java, as you have noticed. Typically for an update though it will require that + changing other code.

@DoctorMacc has been very helpful with the updating as well, and I greatly appreciate it! If you feel you can write about it @DoctorMacc , go for it. I'll see if I can get a Wiki section going maybe on the repository.

**Comment by Bryantdl7** [comment]
I looked at your most recent PR and I see it’s 422 for the new build and the snapshot has gone to 2.6.1, what resource do you use to get these numbers? Is it some command or is there some change log which contains these numbers? 

Updating it is the easy part it’s proven difficult to find the info to update it with

**Comment by DoctorMacc** [comment]
422 is the protocol number for Bedrock, which is what is used to determine changes in Bedrock's network communication. 2.6.1 just means the library bumped up. I closely follow the development of the library as it is important to Geyser - a good resource for it is the Nukkit/Cloudburst Discord.

**Comment by Technoguyfication** [comment]
Speaking of this, does anything think it would be worthwhile to make an auto updater for this software? I have BC running on a cloud VM that I don't touch often, and I can see how it'd be easy to forget to update it. Or maybe I just need to watch for new releases on GitHub and pull the latest jar and replace it.

**Comment by Bryantdl7** [comment]
It probably would be easier to run a daily cron job to pull updates than make an auto updater, just my thoughts.

**Comment by kmpoppe** [comment]
@Technoguyfication 
> Speaking of this, does anyone think it would be worthwhile to make an auto updater for this software? I have BC running on a cloud VM that I don't touch often, and I can see how it'd be easy to forget to update it. Or maybe I just need to watch for new releases on GitHub and pull the latest jar and replace it.

I use a **[start.sh](https://github.com/Pugmatt/BedrockConnect/files/8039458/start.txt)** for BedrockConnect that loosely resembles the [Minecraft Ubunt Server start script](https://jamesachambers.com/minecraft-bedrock-edition-ubuntu-dedicated-server-guide/).

It checks for the most recent release on GitHub and replaces your local version once it finds a new one. Please not that I run BedrockConnect from /home/mcbcsl, you'd need to change that path all over the script. You can just cron a kill of the screen instance and restart it every so often (like 6 hours or so, whatevery floats your goat).

As I run two of the other public instances in Germany and the UK I update these as fast as I can so people can continue playing, updating them every night would be too infrequent, but sure, in your scenario it should be fine.

**Comment by kmpoppe** [comment]
We're now running an hourly GitHub action to check for a new Bedrock Server download and page the people who must know (most importantly @Camotoy as he's the Protocol wizard), so we're looking into a brighter future as to the reaction to updates.
