### ISSUE TITLE
Problems

### ISSUE THREAD

**Issue by awsomenes** [Pugmatt/BedrockConnect#120]
Honestly, this never works. It’s absolutely ridiculous, my switch Minecraft game crashes, I can’t load into worlds I get kicked literally every time. This is amazing work but only if it would actually work

**Comment by Pugmatt** [comment]
I'm running through some tests tonight, so it might be a bit buggy. If it's that much of a problem on your end, run a local version:  https://www.youtube.com/watch?v=AW5X7-qnvLk
