### ISSUE TITLE
No internet with switch

### ISSUE THREAD

**Issue by Keurig-Creator** [Pugmatt/BedrockConnect#122]
I am hosting the instance locally on my computer, I change the DNS settings right, when I start minecraft, it does not show any servers and says no internet connection? I tried 1.1.1.1, 1.0.0.1, 8.8.8.8 but neither work.

**Comment by Pugmatt** [comment]
You are following this tutorial, correct? https://www.youtube.com/watch?v=AW5X7-qnvLk
