### ISSUE TITLE
Locally hosted server and Switch not talking

### ISSUE THREAD

**Issue by tomrow** [Pugmatt/BedrockConnect#123]
When trying to host a server with the 1.5.6 BEDROC~1.JAR file (not the zipped one) and the console's primary DNS server is set to the computer it's running on, the console seems to completely disregard the spoofing and connect directly to the featured servers, or show the Coming Soon message. My guesses are that either Windows is blocking outbound DNS servers, Minecraft gives up when it finds the server list page is in a private IP range, or BedrockConnect is not hosting the DNS server properly or at all. The publically accessible DNS server works perfectly fine for me. Has anyone found a workaround?

**Comment by Keurig-Creator** [comment]
I get the same problem with locally hosting

**Comment by Pugmatt** [comment]
> When trying to host a server with the 1.5.6 BEDROC~1.JAR file (not the zipped one) and the console's primary DNS server is set to the computer it's running on, the console seems to completely disregard the spoofing and connect directly to the featured servers, or show the Coming Soon message. My guesses are that either Windows is blocking outbound DNS servers, Minecraft gives up when it finds the server list page is in a private IP range, or BedrockConnect is not hosting the DNS server properly or at all. The publically accessible DNS server works perfectly fine for me. Has anyone found a workaround?

What DNS software are you using? The BedrockConnect software is not a DNS server, it only supplies the serverlist server that a DNS server needs to redirect to. If you haven't already, check out this: https://www.youtube.com/watch?v=AW5X7-qnvLk

**Comment by tomrow** [comment]
Oh, thanks for clarifying that. I must've missed something when reading the instructions
