### ISSUE TITLE
IPV6 Causing Problems

### ISSUE THREAD

**Issue by raymondraptor** [Pugmatt/BedrockConnect#124]
Hello there!

First, I just wanted to say that this is a great solution to a stupid issue that Microsoft doesn't seem to be in any rush to fix.

It's worked for a few of my friends, but the ones who use Xfinity (and are forced to use IPv6) are always sent to the server directly. 

Is there any remedy for this? 

I know its better to run it locally, but they don't have any type of system to run it on.

Thanks!

**Comment by Pugmatt** [comment]
This is a known issue, and currently no workaround to make it work with IPv6 as it's a problem with how the game console deals with IPv6 DNS servers. The only solutions are to host it locally, or disable IPv6 in your router. Tutorials on how to disable IPv6 can be found on YouTube, such as here: https://www.youtube.com/watch?v=3FhBEI55__s
