### ISSUE TITLE
Suggestion: Disable user custom servers

### ISSUE THREAD

**Issue by DespicableKee** [Pugmatt/BedrockConnect#126]
With the addition of custom default servers, it only seems fair for hosters to be able to disable creation of user generated custom servers. It would likely be in the form of a integer setting, between 0 and 3.
0 (default) shows user's current custom servers and allows creation and deletion of user-generated custom servers
1 shows user's custom server's, but creation of user-generated servers is disabled
2 shows user's custom server's, but creation and deletion of user-generated servers is disabled
3 doesn't shows user's custom servers, or the ability to create or delete user-generated servers
You could also just simply this to true/false, where true would equal 3 and false would equal 0.

**Comment by Pugmatt** [comment]
Thanks for the suggestion. An option to toggle user server options has now been added in the latest release: https://github.com/Pugmatt/BedrockConnect/releases/tag/1.6.1
