### ISSUE TITLE
Unable to connect on Switch

### ISSUE THREAD

**Issue by elgrandmarc** [Pugmatt/BedrockConnect#127]
It keeps saying Unable to Connect after choosing an already listed IP address. Tried a dozens of times, restarted the game and the Switch and still not working.

**Comment by Pugmatt** [comment]
Verify the following:
- The Primary DNS on the game console is set to  104.238.130.180
- The secondary DNS is set to 8.8.8.8 . Also can try 1.1.1.1 .
- If you're on the serverlist already and get the error after choosing a server, make sure the server you're connecting to is on Bedrock edition and not Java Edition. 
- If you've verified the above, it might just be a bad connection. In which case, you can try hosting a local instance: https://www.youtube.com/watch?v=AW5X7-qnvLk

**Comment by elgrandmarc** [comment]
Problem solved! Thanks for the quick response

**Comment by elgrandmarc** [comment]
Problem solved! Thanks for the quick response
