### ISSUE TITLE
== READ THIS before saying server is down ==

### ISSUE THREAD

**Issue by Pugmatt** [Pugmatt/BedrockConnect#128]
My host has alerted that the server was DDOS'd, and they're null routing the 104.238.130.180 address for 24 hours. I will try to get an alternative server up in the meantime.
If you are able to, I recommend setting up a local instance for now: https://www.youtube.com/watch?v=AW5X7-qnvLk

**Comment by Pugmatt** [comment]
Appears to be back. I'll be keeping an eye on it.

**Comment by Otoris** [comment]
Happening again

**Comment by Pugmatt** [comment]
Server was just having some issues, it's not related to this. Issue here was already solved.
