### ISSUE TITLE
Not working on Xbox in 1.16.201

### ISSUE THREAD

**Issue by mrpatches123** [Pugmatt/BedrockConnect#131]
It keeps saying “Unable to connect to world” and if it goes to the open server list it does the same thing when I try to join a server.

**Comment by Pugmatt** [comment]
Verify the following:
- The Primary DNS on the game console is set to  104.238.130.180
- The secondary DNS is set to 8.8.8.8 . Also can try 1.1.1.1 .
- If you're on the serverlist already and get the error after choosing a server, make sure the server you're connecting to is on Bedrock edition and not Java Edition. 
- If you've verified the above, it might just be a bad connection. In which case, you can try hosting a local instance: https://www.youtube.com/watch?v=AW5X7-qnvLk

**Comment by beyondnorm** [comment]
Switch 1.16.201 isn't working either it gets stuck before the server list.

Is it possible to run it locally on Linux?

**Comment by jbenammi** [comment]
As of yesterday 1.16.201 Switch stopped connecting before the server list. Gets stuck on "Locating Server" and does not move forward with populating the server list. All of the above has already been verified.

**Comment by Pugmatt** [comment]
> Switch 1.16.201 isn't working either it gets stuck before the server list.
> 
> Is it possible to run it locally on Linux?

Hmm, still appears to be working on my Switch fine. You can run the jar on Linux, and use BIND as the DNS software: https://github.com/Pugmatt/BedrockConnect/blob/master/BIND_Install.txt



> As of yesterday (12/27/20) 1.16.201 Switch stopped connecting before the server list. Gets stuck on "Locating Server" and does not move forward with populating the server list. All of the above has already been verified.

This happens as well when trying to host it locally?

**Comment by beyondnorm** [comment]
> As of yesterday (12/27/20) 1.16.201 Switch stopped connecting before the server list. Gets stuck on "Locating Server" and does not move forward with populating the server list. All of the above has already been verified.

This is exactly the same thing that is happening to me.

**Comment by TroveFan1** [comment]
> Verify the following:
> 
> * The Primary DNS on the game console is set to  104.238.130.180
> * The secondary DNS is set to 8.8.8.8 . Also can try 1.1.1.1 .
> * If you're on the serverlist already and get the error after choosing a server, make sure the server you're connecting to is on Bedrock edition and not Java Edition.
> * If you've verified the above, it might just be a bad connection. In which case, you can try hosting a local instance: https://www.youtube.com/watch?v=AW5X7-qnvLk


This does not work at all, when I connect to any of the servers it immediately stalls to unable to connect.
I verified all and even ran local instance
