### ISSUE TITLE
Hive server will not work

### ISSUE THREAD

**Issue by jdextraze** [Pugmatt/BedrockConnect#132]
Just to let you know that the Hive server will not work anymore because it uses [DNSSEC](https://en.wikipedia.org/wiki/Domain_Name_System_Security_Extensions) to secure their DNS. You can see this by doing an ANY query on their domain: `dig hivebedrock.network any`. The **RRSIG**, **DNSKEY** and **NSEC3PARAM** entry secures the domain from DNS hijacking. It should be mentioned in the **README**.

I also want to mention that I will be hosting a bedrock connect server at 173.82.100.84 if you want to list it.

Cheers,

J.D.

**Comment by Pugmatt** [comment]
Thanks for letting me know, I'll look into it. The Hive server still appears to be redirecting to the serverlist server correctly through the DNS server on my PC and Nintendo Switch. Haven't tested on an Xbox yet, and don't have a PS4/PS5. So I can get a better idea, what devices/game consoles has it not been working on your end?

**Comment by kmpoppe** [comment]
On the topic of other servers, I had also planned to host a server people could connect to. Would it be an idea to check if we can use one database access (or mirror the database that you're using @Pugmatt) so that people get their servers, whichever other DNS server they use (the ultimate goal would be a load balancer IP that distributes queries between the Serverlist servers so that players use 1 IP and the load get distributed...)?

**Comment by jdextraze** [comment]
I tried on a switch. I also had a friend that had trouble at first using it and then it worked. I forgot about the TTL of DNS which are mostly under 5 minutes for those servers but the console might not respect it and use a higher standard. That is probably also the issue with all those people saying it is not working, local DNS cache on the console.

@Pugmatt If your DNS hack has been active for a while it might be why it is still working for you. If DNSSEC was activated after you started using BedrockConnect the DNSSEC will not have propagated to the console. That is my guess.

@kmpoppe If you setup an IP load balancer then you have only 1 public IP not a list and setting that up is complex and afaik not allowed between multiple hosting providers for security and performance reasons.

Anyway, the error I get with Hive is "Bad IP address". Here's some screenshot but they are in french.

**Network Configuration**
![2020122711313400-57B4628D2267231D57E0FC1078C0596D](https://user-images.githubusercontent.com/1495286/103292888-c1db8300-49bc-11eb-922c-1fb674c90090.jpg)

**Minecraft Server List**
![2020122909255600-11B64E28AD7A49CA9EC8AC007BE858C6](https://user-images.githubusercontent.com/1495286/103292900-c7d16400-49bc-11eb-9977-d3b70ad91a86.jpg)

**Error When Connecting To Hive**
![2020122909260700-11B64E28AD7A49CA9EC8AC007BE858C6](https://user-images.githubusercontent.com/1495286/103292905-cacc5480-49bc-11eb-9803-f385c376f2a0.jpg)

**Comment by kmpoppe** [comment]
@jdextraze You might be right for load balancing, yet, if we wanted to created multiple servers (in different countries which would be nice for players) it would still be cool if they could access the existing players servers, they created on 104.x.y.z, right?

Did you try to connect to the Hive server _after_ you have connected to the Serverlist Server? Because that would transfer you directly to the IP 54.39.75.136 of hivebedrock(.)network and thus there'll be no DNSSEC problem I guess?

**Comment by jdextraze** [comment]
@kmpoppe No but I wasn't attempting to connect to the Hive server ... I was saying that the Hive server didn't work anymore with the DNS hijacking technique used to connect to BedrockConnect. All other servers worked fine.

@Pugmatt And while doing another test just now, it worked. So it brings me to the other thing I mentioned, DNS caching on the console. Weird thing is that I don't remember accessing the Hive server before using my bedrock connect, so it is a mystery why their DNS would be cached. Other mystery is that they have DNSSEC active and it should protect them from that kind of hijacking. 🤷

If we wanted to share database between multiple servers we would need a secure way to do it, my MySQL knowledge doesn't extend to their server sync and secure connection abilities.

**Comment by jdextraze** [comment]
Solved the mystery of DNSSEC, it is setup on their DNS provider but not their domain name provider. For it to work properly you need to add a **DS** entry at the domain name level and they didn't. So it leave a DNS caching issue only.

@Pugmatt do you want me to close this ticket or do you want to close it after adding a warning about DNS caching in the README?

@kmpoppe you should start another issue for the multi server suggestion.

**Comment by kmpoppe** [comment]
@jdextraze Will do so. Please don't remove your IP from this Issue so that I can refer to this in a list.

**Comment by Pugmatt** [comment]
@jdextraze Thanks for looking into that. Odd stuff, and I wouldn't doubt local cache on the console is involved as well. I'll close the issue once I add info about it in the README.

@kmpoppe For now, I'd prefer keeping the servers available under the main BedrockConnect DNS, 104.238.130.180, hosted by me. The servers can sometimes get finicky when under heavy traffic, so I'd rather have control over them if one starts acting up. I also would rather not have multiple parties having access to the player information in the database, if that makes sense.

I currently have multiple BedrockConnect instances running, and the DNS chooses which one to direct to using Round Robin balancing. This obviously isn't super ideal, and sometime in the next month I plan on launching up more instances that are specific to regions and having a load balancer that will balance according to region and availability better.

On the topic of adding your guy's instances though, I would be down to adding them to a section in the README or Wiki as alternative IPs to use.
