### ISSUE TITLE
Show Coordinates

### ISSUE THREAD

**Issue by kmpoppe** [Pugmatt/BedrockConnect#134]
https://github.com/Pugmatt/BedrockConnect/blob/0a4410bff023d374942659bb4b76a4ccece55230/serverlist-server/src/main/com/pyratron/pugmatt/bedrockconnect/BCPlayer.java#L139

Hey @Pugmatt,

I was wondering why `showCoordinates` is set to true. Whenever I choose a server from the list to connect to, the coordinates shown are 0, -2, 0 - and then the transfer to the selected server starts, so I don't see a real use for the coordinates?

Thanks!

Kai

**Comment by Pugmatt** [comment]
This is just leftover when I was initially developing BedrockConnect and testing with the packets trying to get it to work. It can be set to false. I've now done this in the latest commit.
