### ISSUE TITLE
nodb=false has no effect

### ISSUE THREAD

**Issue by kmpoppe** [Pugmatt/BedrockConnect#135]
https://github.com/Pugmatt/BedrockConnect/blob/e40ba0021f501beded32eb19637f4221d3c2cb7f/serverlist-server/src/main/com/pyratron/pugmatt/bedrockconnect/BedrockConnect.java#L56-L57

If `nodb=` is ommited when starting, mySQL is correctly used, but if, like me, one was adding `nodb=false` to make clear what they intended, the `noDB` variable in the code is set to true no matter what follows.

I'd only set `noDB` to true only if `=true` followed in the parameter.

Thoughts?

Kai

**Comment by Pugmatt** [comment]
Something I probably missed when implementing this, thanks for letting me know. Latest commit should now have this fixed and requires it to be set to true.
