### ISSUE TITLE
Doesn't work on switch?

### ISSUE THREAD

**Issue by comrade-zoe** [Pugmatt/BedrockConnect#137]
Hey,
Have "cleared cache" and left overnight but despite having set the DNS to BedrockConnects, I get sent straight to the server? 
![16094175477875808390017553106836](https://user-images.githubusercontent.com/66450509/103410494-52ec5e80-4b63-11eb-937c-88471892a178.jpg)

For a while there are no servers, then you click off and move around a bit
![16094176285239090149992270343771](https://user-images.githubusercontent.com/66450509/103410517-8202d000-4b63-11eb-9079-693f6ca9f3a5.jpg)

Then servers appear
![1609417685755248392296159188194](https://user-images.githubusercontent.com/66450509/103410541-a3fc5280-4b63-11eb-8d7e-85a65f0601c0.jpg)

And after connecting you just go to the server
![16094177271755430827221832511247](https://user-images.githubusercontent.com/66450509/103410552-bbd3d680-4b63-11eb-87a7-d01417a784e3.jpg)

**Comment by kmpoppe** [comment]
The MOTD (Message Of The Day) under the server's name would show "Join to open Server List" if your switch has correctly figured out what server to connect to.

I had this issue with my switch for quite some times as well. For me switching it off completely (not just in power safe mode) and setting the secondary DNS to one of 8.8.8.8 or 8.8.4.4 (these are the Google DNSs) fixed it. You might need to play around with the secondary DNS settings.

**Comment by DespicableKee** [comment]
> The MOTD (Message Of The Day) under the server's name would show "Join to open Server List" if your switch has correctly figured out what server to connect to.
> 
> I had this issue with my switch for quite some times as well. For me switching it off completely (not just in power safe mode) and setting the secondary DNS to one of 8.8.8.8 or 8.8.4.4 (these are the Google DNSs) fixed it. You might need to play around with the secondary DNS settings.

And if this fails, you could also host your own dns server.
I have personally had issues with the main dns server in the past, but now that I'm hosting my own dns I'm able to forward the featured servers on both my PS4 and mobile device. I believe that the issue involves distance, downtime, a combination of both, or maybe some ISP's block certain outside dns servers.

**Comment by JamesTheAwesomeDude** [comment]
> The MOTD (Message Of The Day) under the server's name would show "Join to open Server List" if your switch has correctly figured out what server to connect to.

I'll chime in: on my brother's Switch, only _some_ of the servers will have this message. Be sure to scroll through the whole list and check for one; sometimes only the last one in the list works! (But you can join any; it's all the same.)

**Comment by comrade-zoe** [comment]
Sky Broadband in the UK redirects external DNS requests to their DNS servers, running an internal DNS server and DoH solves this.

**Comment by zoe72a** [comment]
For future reference on sky with custom DNS servers, this only occurs if Sky Broadband Shield (Unsure about the buddy app, which is router rather than DNS side) is enabled - which is default behavior. Disable it and it should work.
