### ISSUE TITLE
Connection to server times out

### ISSUE THREAD

**Issue by gnobi1** [Pugmatt/BedrockConnect#14]
Hello. No matter what I choose it says connection to server times out. This is the screen right before I select saved server

**Comment by LoganMD** [comment]
I'm having the same issue. I'd create my own server, but I'm already hosting a bedrock server on the same port.

**Comment by Pugmatt** [comment]
All servers, including servers like Mineplex and Hive, give "Connect to server times out"?

**Comment by LoganMD** [comment]
Seems like the issue fixed itself, I assume the DNS server itself was just temporarily offline.
