### ISSUE TITLE
Not working on Xbox

### ISSUE THREAD

**Issue by DhruvDav3** [Pugmatt/BedrockConnect#143]
I did everything and I even got to the server ip input stage, when you try to join the server you want to, it says unable to connect to world

**Comment by Pugmatt** [comment]
That is an issue with the server you are trying to connect to then, not BedrockConnect. Have you verified that the server you are trying to connect to is Bedrock Edition and not Java edition?

**Comment by DhruvDav3** [comment]
Yea, I've verified that it is a Bedrock Edition server

**Comment by Pugmatt** [comment]
Does it appear to be just happening with the one server, or any server you join?

**Comment by Feneck91** [comment]
I have exactly the same problem. Using https://hub.docker.com/r/marctv/minecraft-bedrock-server on my NAS + Docker.
Redirection ports are OK, an in local network all is working fine.
Not working with your solution, not working with Phantom too!

**Comment by z1haze** [comment]
I also am having this issue. I setup a bedrock server for my friends and they've been playing over the weekend. today within the last hour, it says unable to connect to world (when joining the default server, such as mineplex) eg before you even get to the second server picker

**Comment by Pugmatt** [comment]
> I also am having this issue. I setup a bedrock server for my friends and they've been playing over the weekend. today within the last hour, it says unable to connect to world (when joining the default server, such as mineplex) eg before you even get to the second server picker

Server was having issues today due to unexpected downtime with my server hosting. Should be good to go now, give it another try.

**Comment by z1haze** [comment]
yeah man, all good.

**Comment by SSJteengohanx** [comment]
I cant join server it needs my player database
