### ISSUE TITLE
Nintendo switch not working 

### ISSUE THREAD

**Issue by zrafferty** [Pugmatt/BedrockConnect#145]
I made a server and ip dns and cannot get it to function on my switch.
Verification server works on pc only after editing configuration file to geo.thehive from just thehive 
Nintendo switch will not connect 
Verified all ports are open 
On version 1.16.201

**Comment by Pugmatt** [comment]
Can you go into more detail on "will not connect"? Any error messages?

**Comment by zrafferty** [comment]
Loads main servers only.  For test on pc which is functional after editing the hive url as stated I am able to connect via internal ip and loop back but just no success on the switch

**Comment by zrafferty** [comment]
Is there any other parts that should be opened prior that switch uses and pc doesnt?

**Comment by Pugmatt** [comment]
Should only need 19132 opened for the serverlist server, and port 53 for the DNS server.

**Comment by zrafferty** [comment]
I'll add 53 don't recall if I did but when I tested on pc I used my internal ip of 192.168.0.10
As well as a 127.0.0.1(local host)
Pc works perfect just switch side that don't work.
I'll comment back of there any other issues

**Comment by zrafferty** [comment]
I added port 53 as well as added a second dns off your list and now working not sure which fixed but  I do thank for help. Now just have to fix a quirk of a Java server kn bedrock where my craft supplies are not crafting and getting tossed out
