### ISSUE TITLE
Cant use this on Xbox One

### ISSUE THREAD

**Issue by TroveFan1** [Pugmatt/BedrockConnect#146]
When I try to connect to a server it says Unable to connect to server before the input screen even appears.
I have tried this with both DNSs available in my country.

**Comment by Pugmatt** [comment]
If you have your local instance up (like you said here: https://github.com/Pugmatt/BedrockConnect/issues/131#issuecomment-762616589), can you look under the "Friends" tab and see if it shows up under LAN servers. If you have the local server set up correctly, it should always be showing up here.
