### ISSUE TITLE
Unable to use on Xbox One 

### ISSUE THREAD

**Issue by kieran2001** [Pugmatt/BedrockConnect#147]
I’m unable to use on Xbox one.

The issue I face is:

I can connect to server in the default, but server selectors don’t open to add a new one etc.

I’ve checked the following:
 
- DNS Correct
- No IPV6

I’ve tried the following:

- Restarting console
- Resetting server list
- restarting game

**Comment by Pugmatt** [comment]
DNS on the console might be acting finicky, not sure. Have you tried hosting a local instance yet?

**Comment by kieran2001** [comment]
Tried the U.K. instance, no difference.

**Comment by Pugmatt** [comment]
Most I can recommend then is hosting a local instance. With both the local instance running and console on the same network, you can join it through the "Friends" tab in-game and see if it shows up under LAN servers. I have links for tutorials on different devices on the Troubleshooting page.
