### ISSUE TITLE
Nintendo switch: Unable to connect to world

### ISSUE THREAD

**Issue by JustAbdul6** [Pugmatt/BedrockConnect#149]
Hi, I have tried this method and I can get to the server list but whenever I join a server (including featured ones) they say that I am unable to connect to them. Please help.

**Comment by Pugmatt** [comment]
Sounds more like a connection issue, as once you're joining a server from the serverlist the connection is off of BedrockConnect's. Try changing the secondary DNS to a different one if you haven't already: https://github.com/Pugmatt/BedrockConnect/wiki/Troubleshooting#the-internet-on-my-console-is-not-working-at-all-now
