### ISSUE TITLE
[enhancement] Offer a second DNS address for another list made by another creator

### ISSUE THREAD

**Issue by ZeekaBobIs** [Pugmatt/BedrockConnect#151]
[GeyserMC](https://github.com/GeyserMC) lets users connect to Java servers and it'd be awesome if you offered [this github project](https://github.com/GeyserMC/GeyserConnect) their own public DNS.

**Comment by Pugmatt** [comment]
They already have a public DNS: 136.49.186.24

Not sure if it's hosted by the developers, but it's the one I see circulating around the community.
