### ISSUE TITLE
Will not load sever list just sends me to the main severs like lifeboat...

### ISSUE THREAD

**Issue by Bagelbits1944** [Pugmatt/BedrockConnect#152]
I can not connect to the sever list on my Switch and to be sure it wasn't just the switch I also tried my phone and it still will not load the sever list just sends me to the main severs. I have tried all of the listed dns secondary severs and no seem to work. I has worked twice out of the all times i have tried to us it. Could a vpn or firewall be blocking the dns sever Im connected to?

**Comment by Pugmatt** [comment]
Not really sure, unfortunately. Could be something in your router blocking the DNS server or forcing the DNS. Could try setting the DNS in your router, or seeing if you have IPv6 enabled: https://www.youtube.com/watch?v=3FhBEI55__s

**Comment by DespicableKee** [comment]
> Not really sure, unfortunately. Could be something in your router blocking the DNS server or forcing the DNS. Could try setting the DNS in your router, or seeing if you have IPv6 enabled: https://www.youtube.com/watch?v=3FhBEI55__s

If this doesn't work, you may need to host your own DNS server. I am not able to use the public DNS servers for whatever reason, but once I hosted my own I was able to join external servers on my PS4, without issue. Though I may have just tried during an outage or something.
