### ISSUE TITLE
hypriot/rpi-java depricate

### ISSUE THREAD

**Issue by acidflash** [Pugmatt/BedrockConnect#153]
Need to update Docker file to new version https://github.com/hypriot/rpi-java says
DEPRECATED: PLEASE USE OFFICIAL DOCKER IMAGES openjdk AS THEY PROVIDE IMAGES FOR ARM

**Comment by SeniorHeld** [comment]
Dockerfile is updated to openjdk:11 and should work with windows, linux and arm
See Dockerfile in folder "docker"
