### ISSUE TITLE
Bind Install Script on Pop!_OS

### ISSUE THREAD

**Issue by Kore-Development** [Pugmatt/BedrockConnect#156]
When running the Bind install script on Pop!_OS it says unsupported OS. Pop!_OS is an Ubuntu distro, so it should be supported.

**Comment by jdextraze** [comment]
First of all script is made to support Ubuntu, not every distro based on Ubuntu. It use the data provided by the OS in `/etc/os-release` to check support. Can you paste the content of that file here.
