### ISSUE TITLE
Xbox V1.16.201 Server List Not Working

### ISSUE THREAD

**Issue by CroopzyYT** [Pugmatt/BedrockConnect#158]
It's either showing up with the servers the same as normal when enabled or the server info doesn't show at all and just loads and never loads up the text that says "click to open server list" until I quit and rejoin the application and the servers show with normal information.

**Comment by CroopzyYT** [comment]
Just realised I also can't play servers normally with the DNS on

**Comment by CroopzyYT** [comment]
Constantly get disconnected when I have the DNS on.

**Comment by Pugmatt** [comment]
Try using one of the other DNS's being hosted if you haven't already. Sounds like a bad connection. https://github.com/Pugmatt/BedrockConnect#publicly-available-bedrockconnect-instances

**Comment by CroopzyYT** [comment]
> Try using one of the other DNS's being hosted if you haven't already. Sounds like a bad connection. https://github.com/Pugmatt/BedrockConnect#publicly-available-bedrockconnect-instances

Okay thanks, I have tried the other ones and they didn't work. My connection has been struggling recently so it is probably that.

**Comment by Pugmatt** [comment]
If you're able to, you can also try hosting your own local instance, tutorials located at the bottom of the page: https://github.com/Pugmatt/BedrockConnect/wiki/Troubleshooting#im-having-lag-issues-or-getting-disconnected-when-on-or-trying-to-connect-to-the-bedrockconnect-serverlist

**Comment by Thedoczek** [comment]
> Try using one of the other DNS's being hosted if you haven't already. Sounds like a bad connection. https://github.com/Pugmatt/BedrockConnect#publicly-available-bedrockconnect-instances

It didn't work for me

**Comment by CroopzyYT** [comment]
I've started to use the bedrock connect app instead, it seems to work but you have to watch an add every time
