### ISSUE TITLE
Error when trying to install on ubtuntu

### ISSUE THREAD

**Issue by pineapplee85** [Pugmatt/BedrockConnect#159]
Hi,
I am following the steps but get this error when trying to install on ubuntu:

sudo: install-bind.sh: command not found

I presume I am missing something?

Thanks

**Comment by jdextraze** [comment]
In the same folder where the script is try `sudo ./install-bind.sh [IP]` (replace [IP] with your server IP address). Also the script need to be made executable first: `chmod +x ./install-bind.sh`.

**Comment by rstone13** [comment]
I had this same issue. I solved it by running the command (from the same directory that the script is) as:

`sudo bash ./install_bind.sh [IP]`

**Comment by pineapplee85** [comment]
Hi,
It was because I didn't chmod. 
Thanks!
