### ISSUE TITLE
Server address validation too strict

### ISSUE THREAD

**Issue by mindw0rm** [Pugmatt/BedrockConnect#16]
1. the regex (`[a-zA-Z.0-9]+`) does not allow a hyphen,  which is valid in domain names.
2. the maximum length (45) is also too strict; each part (label) can be up to 63 chars, the total length can be at least up to 253. 

See e.g. https://en.wikipedia.org/wiki/Hostname#Restrictions_on_valid_hostnames

**Comment by Pugmatt** [comment]
Thanks for alerting me of this! It has been fixed in the latest push.
