### ISSUE TITLE
Outdated Server error on Xbox One.

### ISSUE THREAD

**Issue by BigDataDaddy** [Pugmatt/BedrockConnect#165]
Just started getting an Outdated Server error at 12:40 EST today right after the Xbox One Bedrock client upgraded to v1.16.210 build 5508458 protocol version 428.   My guess is that the Bedrock Connect server is now out of date with the protocol version.

**Comment by kmpoppe** [comment]
Yep. Same as last update. Please be patient for @Pugmatt to update the protocol library.

**Comment by Pugmatt** [comment]
Serverlist server has now been updated to 1.16.210, and latest JAR can be found under releases.
