### ISSUE TITLE
Why can't PS4 use this DNS server directly?

### ISSUE THREAD

**Issue by masaomi-yamaguchi** [Pugmatt/BedrockConnect#167]
Hi,
I am playing Minecraft on PS4 now.
To play on a multi-server that is not realms, I tried to use this DNS server.
But, I have only PS4 and iPhone, neither Android device nor PCs.

Since I cannot find a way to use this DNS server through iPhone,
I tried to use this DNS server directly like Switch.
I set primary as follows:
  primary address: 104.238.130.180
  secondary address: 8.8.8.8
But, my PS4 has not been able to connect to the Internet after setting.

Why can't PS4 use this DNS server directly?
Or, do you have any way to use this on PS4 through iPhone?

**Comment by Pugmatt** [comment]
This is a known issue with the main DNS https://github.com/Pugmatt/BedrockConnect/issues/154

If you haven't already, try one of the other listed DNSs: https://github.com/Pugmatt/BedrockConnect#publicly-available-bedrockconnect-instances
Supposedly jdextraze's (173.82.100.84) works on PS4 without issue.

**Comment by masaomi-yamaguchi** [comment]
All problems are solved by using 173.82.100.84!
Thank you for your reply and this great project!
(I recommend you add this topic to README)
