### ISSUE TITLE
173.82.100.84 by jdextraze Giving Server Out of Date Error on PS4

### ISSUE THREAD

**Issue by blizzzardofoz-dev** [Pugmatt/BedrockConnect#168]
My brother has been sending me texts over the past few days saying that he is still getting the Server Out of Date error on his PS4. He is using the 173.82.100.84 DNS server maintained by jdextraze - do we know if that has been updated to the latest version yet? I am not sure if it is just happening for my brother or if it is a more prolific issue.

**Comment by blizzzardofoz-dev** [comment]
Can confirm, I switched my girlfrinds' Switch from the main DNS to the one my brother is using, and it gave us the same outdated error. Switched it back to the main server and it is workin just fine.

**Comment by Pugmatt** [comment]
Not sure. It does appear to be out of date. @jdextraze 

You can also try using one of kmpoppe's DNSs in the meantime which are currently up to date, not sure if his are working on PS4 or not.

**Comment by jdextraze** [comment]
Sorry, I've been busy and didn't have time to update yet. It's now updated. I'll create an automatic update script over the weekend.

**Comment by blizzzardofoz-dev** [comment]
No problem at all, this is my first week of playing with this so I didn't know if I was the problem or not. Thanks for your services, this is awesome! And my self hosted server runs better than the Realm do, so it's great. Keep up the good work! :)
