### ISSUE TITLE
[Feature] Supporting multiple Bedrock versions

### ISSUE THREAD

**Issue by Camotoy** [Pugmatt/BedrockConnect#170]
The update process for 1.16.210 was particularly bad over on Geyser's end - the update suddenly left everyone being unable to connect to BedrockConnect. However, the Protocol library has ridiculously easy multiversion support. What I propose is refactoring the codec system to translate and allow multiple Bedrock clients to be supported - once we anticipate an update to be nearing, BedrockConnect can update to support the current release and the next release, allowing a seamless transition.

(I would be willing to code this myself; just making it an issue first for discussion)

**Comment by Pugmatt** [comment]
Thanks for bringing this up. I went ahead and made the changes, feel free to look it over, seems to be working from my testing: https://github.com/Pugmatt/BedrockConnect/commit/ce07489fb06d06614943515b5e5cd6656832b8a5

**Comment by Camotoy** [comment]
Looks good! Thanks.
