### ISSUE TITLE
Patched for PS4 Edition

### ISSUE THREAD

**Issue by anaskatt** [Pugmatt/BedrockConnect#171]
Whenever i try to join it brings me into actual servers/doesnt bring up menu

**Comment by Pugmatt** [comment]
The main instance 104.238.130.180 currently has issues with PS4. I would try this one if you haven't already: 173.82.100.84

**Comment by anaskatt** [comment]
> The main instance 104.238.130.180 currently has issues with PS4. I would try this one if you haven't already: 173.82.100.84

i did its patched that is the only one i used because your dns doesnt work, Also if i wanted to host my own how would i get the public dns?

**Comment by anaskatt** [comment]
also you need to check your disc server they be pinging @everyone every 20 seconds

**Comment by Pugmatt** [comment]
It's currently working for others, so I would not say it's patched. Hosting your own instance can be found at the bottom of the troubleshooting page: https://github.com/Pugmatt/BedrockConnect/wiki/Troubleshooting#im-having-lag-issues-or-getting-disconnected-when-on-or-trying-to-connect-to-the-bedrockconnect-serverlist

**Comment by anaskatt** [comment]
Yeah i successfully hosted my own, but how do i get the public dns?

**Comment by Pugmatt** [comment]
If you're hosting your own serverlist server on the same network, you shouldn't need the DNS, and should be able to join through the "Friends" tab in Minecraft under "LAN Servers"

**Comment by anaskatt** [comment]
The reason i need it is because i host the dns on a server far away

**Comment by Pugmatt** [comment]
What do you currently have setup? Your previous question was how to get the DNS, but you said you have a DNS on a server far away, so I'm a bit confused on your current setup.

**Comment by anaskatt** [comment]
> What do you currently have setup? Your previous question was asking how to get the DNS, but you said now you have a DNS on a server far away, so I'm a bit confused on your current setup and the question.

My windows 10 pc is whats hosting my dns server, But the connection isnt local so i need the public dns address instead of the private dns address,How would i get that?

**Comment by Pugmatt** [comment]
It should just be the public IPv4 address of on your windows 10 pc: https://www.whatismyip.com/

**Comment by anaskatt** [comment]
> It should just be the public IPv4 address of on your windows 10 pc: https://www.whatismyip.com/

Thanks
