### ISSUE TITLE
DNS Redirection

### ISSUE THREAD

**Issue by borjita2019** [Pugmatt/BedrockConnect#172]
I wanna know how this project did the dns thing (make the dns change the game servers to the list), i wanna know because i'm trying to get custom among us server's to work on nintendo switch

**Comment by borjita2019** [comment]
and if you can, code

**Comment by kmpoppe** [comment]
There are quite a few YouTube videos in the Readme that tell you how to set up your own local DNS on a Windows PC - alternatively, if you have another intelligent device in your network (Raspberry pi or a NAS with a custom DNS), you can use that to make the DNS work.

There are literally millions of videos and descriptions Google'able on how to make DNS, from the most basic to some very elaborate ones, IMHO there's no need to describe this process step-by-step in this project.

K.

**Comment by anaskatt** [comment]
bruh just search it up on yt there is millions of results

**Comment by Turtley12** [comment]
BedrockConnect itself does not have a internal DNS server, so for it you have to run a separate DNS server.

For my BedrockConnect server, I am using [CoreDNS](https://coredns.io ) as my DNS server. 

I used the [hosts](https://coredns.io/plugins/hosts/) feature to map the public ip address of my bedrock connect server to an unlikely to be used domain such as `unlikelydomain.domain`. That would look similar to this:

Hosts file:
```
00.00.00.0    unlikelydomain.domain
```

Then for CoreDNS to use that hosts file and to make the bedrock server domains point to `unlikelydomain.domain` we need to add a Corefile file in the same directory as the CoreDNS executable.

```
.:53 {
    hosts /path/to/hosts/file/Hosts
	rewrite name exact hivebedrock.network unlikelydomain.domain
	rewrite name exact geo.hivebedrock.network unlikelydomain.domain
	rewrite name exact mco.mineplex.com unlikelydomain.domain
	
	forward . 8.8.8.8:53
}
```
Above I specified the Hosts file shown earlier, then I added some of the bedrock addresses pointing to the domain I specified in the Hosts file above. Those bedrock addresses could be changed to other addresses you want to replace by simply changing the featured server address to something else such as the among server address you want to redirect.

The part at the bottom with `forward` forwards any other requests to a "real" dns serer, in this case i used Google's primary DNS, some other DNS servers that could be used are listed [here](https://github.com/Pugmatt/BedrockConnect/wiki/Troubleshooting#the-internet-on-my-console-is-not-working-at-all-now). For example, to change the DNS server that it forwards requests to Cloudflare's DNS server, we can that line to `forward . 1.1.1.1:53`

Hope that this helped!

Turtley12
