### ISSUE TITLE
[Feature Request] Let user set a custom name for a server in the server list

### ISSUE THREAD

**Issue by Rexogamer** [Pugmatt/BedrockConnect#173]
For example: if I had a server with an IP of `elongatedservername.example.org`, that and the IP would (and do) look rather ugly in the list. The ability to set a simple name to show in the custom server list would make it look much nicer (eg `Elong. Server`). This would mainly require another text input (if possible, make it optional? Not sure if that's possible with Bedrock UI elements) and storage of the resulting text.

**Comment by Pugmatt** [comment]
Setting custom/display names when adding servers has now been pushed to the live servers, and latest release.
