### ISSUE TITLE
my switch doesn't connect

### ISSUE THREAD

**Issue by danilacasito** [Pugmatt/BedrockConnect#174]
You cannot join cross-platform games without a Microsoft account and a Nintendo Switch account, please login with both accounts to join the servers

that appear, I have connected DNS to 192.168.1.133

ip address shows that:
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: enp7s0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc fq_codel state DOWN group default qlen 1000
    link/ether 8c:16:45:b0:4f:d2 brd ff:ff:ff:ff:ff:ff
3: wlp0s20f3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether c0:b6:f9:f8:da:8b brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.133/24 brd 192.168.1.255 scope global dynamic noprefixroute wlp0s20f3
       valid_lft 73938sec preferred_lft 73938sec
    inet6 fe80::b81b:5541:60a:b0c9/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever

systemctl status bind9 shows that:
● named.service - BIND Domain Name Server
     Loaded: loaded (/lib/systemd/system/named.service; enabled; vendor preset: enabled)
     Active: active (running) since Sat 2021-03-27 11:07:39 CET; 6min ago
       Docs: man:named(8)
   Main PID: 1145664 (named)
      Tasks: 38 (limit: 9324)
     Memory: 148.4M
     CGroup: /system.slice/named.service
             └─1145664 /usr/sbin/named -f -u bind

mar 27 11:13:42 daniel-Lenovo-Legion-Y530-15ICH named[1145664]: network unreachable resolving 'ns-cloud-a2.googledomains.com/A/IN': 2001:4860:4802:38::a#53
mar 27 11:13:42 daniel-Lenovo-Legion-Y530-15ICH named[1145664]: network unreachable resolving 'ns-cloud-a2.googledomains.com/A/IN': 2001:4860:4802:36::a#53
mar 27 11:13:42 daniel-Lenovo-Legion-Y530-15ICH named[1145664]: network unreachable resolving 'ns-cloud-a4.googledomains.com/AAAA/IN': 2001:4860:4802:36::a#53
mar 27 11:13:48 daniel-Lenovo-Legion-Y530-15ICH named[1145664]: network unreachable resolving 'achievements.xboxlive.com.akadns.net/A/IN': 2600:1406:32::83#53
mar 27 11:13:48 daniel-Lenovo-Legion-Y530-15ICH named[1145664]: network unreachable resolving 'privacy.xboxlive.com.akadns.net/A/IN': 2600:1406:32::83#53
mar 27 11:13:58 daniel-Lenovo-Legion-Y530-15ICH named[1145664]: network unreachable resolving '_.realms.minecraft.net/A/IN': 2600:9000:5305:7300::1#53
mar 27 11:13:58 daniel-Lenovo-Legion-Y530-15ICH named[1145664]: network unreachable resolving '_.realms.minecraft.net/A/IN': 2600:9000:5300:9a00::1#53
mar 27 11:13:58 daniel-Lenovo-Legion-Y530-15ICH named[1145664]: network unreachable resolving '_.realms.minecraft.net/A/IN': 2600:9000:5307:ec00::1#53
mar 27 11:13:58 daniel-Lenovo-Legion-Y530-15ICH named[1145664]: network unreachable resolving 'pocket.realms.minecraft.net/A/IN': 2600:9000:5307:9000::1#53
mar 27 11:14:09 daniel-Lenovo-Legion-Y530-15ICH named[1145664]: network unreachable resolving 'realms-bedrock-production.eastus2.cloudapp.azure.com/A/IN': 2603:1061::6#53
~
~
~

SOmeone can help me?

All the ip records points to 192.168.1.133 and bedrock connect is running too in the same computer

-= BedrockConnect =-

Server Limit: 100
Port: 19132

Loaded 0 custom servers
Bedrock Connection Started: 0.0.0.0:19132

**Comment by danilacasito** [comment]
ok, I started bind9 with -4 option but still can't see the list

**Comment by Pugmatt** [comment]
"You cannot join cross-platform games without a Microsoft account and a Nintendo Switch account, please login with both accounts to join the servers"

Assuming the obvious, make sure you're logged into both your Microsoft account and Nintendo Switch account. You also need a Nintendo online membership.

Make sure you have your secondary DNS on your console set. Might have to try different ones depending on your location:
- 1.1.1.1
- 1.0.0.1
- 8.8.4.4
- 8.8.8.8

**Comment by a-m-s** [comment]
It might be good to add the Nintendo subscription to the troubleshooting guide. I did not know this as I had not tried to take the Switch online before, and the game does not give a helpful error message.
