### ISSUE TITLE
BedrockConnect not working on switch or xbox

### ISSUE THREAD

**Issue by Raxcental** [Pugmatt/BedrockConnect#175]
On both my Switch and my brother's switch and his Xbox. bedrock connect is not working. Attempting to use any of the publicly available connect servers results in connecting to an official sponsored server instead. We have tried on 3 different internet networks. We've use each of the publicly available connect servers. This is on two different switch systems and an Xbox. 

Not sure where to go from here. The whole point of my server is so that all my family can play in one place. Bedrock connect is required to make that work.

**Comment by Pugmatt** [comment]
Honestly not sure what it could be, the consoles sometimes will just not respond to the DNS changes. Or your location could be far from the serverlist servers. If you haven't already, you can also try hosting your own instance of BedrockConnect:

PC: https://www.youtube.com/watch?v=AW5X7-qnvLk

Android: https://www.youtube.com/watch?v=ND_VFaAXC8M

iPhone: https://www.youtube.com/watch?v=y2X_hhrsSAk

**Comment by Raxcental** [comment]
Not everyone can host a bedrock connect instance. All troubleshooting steps have been followed. All systems were able to use bedrock connect properly before. It worked before. Nothing has changed on the systems other than system updates and game updates.

**Comment by Pugmatt** [comment]
> Not everyone can host a bedrock connect instance. All troubleshooting steps have been followed. All systems were able to use bedrock connect properly before. It worked before. Nothing has changed on the systems other than system updates and game updates.

I realize not everyone can host a BedrockConnect instance, it was just a suggestion, since there really isn't much else that can be done unfortunately past what's listed in the troubleshooting.

**Comment by Raxcental** [comment]
I tried setting dns on the routers themselves, not resolution there. Connection is indeed ipv4. Is this issue common since 1.16.210?

**Comment by Raxcental** [comment]
Pinging Galaxie returns with an ip address of 54.39.243.200. This is despite having the dns set on both my computer and the router. IPv6 is disabled on my pc. I'm not sure what else could be the issue on my end as every location in my network has the dns set to the bedrock connect address. Unless my ISP is somehow? I can try using a VPN.

**Comment by Raxcental** [comment]
Using a VPN with the dns set through the vpn. Pinging Galaxie resulted in a ping sent to 104.238.179.174. Returned a timed out message 4 times.

**Comment by Pugmatt** [comment]
Your ISP might be blocking the DNSs.

As for the VPN, the IP being returned is probably the VPN IP I imagine, so probably hard to tell from the ping. Unless the pinging is through a tool on your VPN.

**Comment by Raxcental** [comment]
Do you know of anyway to get around my ISP blocking bedrock connect?

**Comment by Pugmatt** [comment]
I do not, you would have to contact your ISP.

**Comment by LeontKing2** [comment]
> Do you know of anyway to get around my ISP blocking bedrock connect?

I know a way 
You can use playit.gg or hamachi VPN

**Comment by bllocky** [comment]
I have spent 30 bucks and nintendo switch online to try and connect to the server list. On my xbox, I have tried all dns’s, ipv6 is off on both my switch and xbox. I have tried all the featured servers, it goes to the normal server. I have been trying tactics for a couple months now, None of them work. I need help with this so please reply

**Comment by bllocky** [comment]
I hope there is some concrete on the road that i can drive on. All of my tries are roadblocks. All I can think of is trying mcpe with a wired keyboard and wireless mouse. But there’s no way that’s gonna happen. For now I can stick with regular mcpe.

**Comment by Pugmatt** [comment]
> I have spent 30 bucks and nintendo switch online to try and connect to the server list. On my xbox, I have tried all dns’s, ipv6 is off on both my switch and xbox. I have tried all the featured servers, it goes to the normal server. I have been trying tactics for a couple months now, None of them work. I need help with this so please reply

If you haven't already, you can try setting turning IPv6 back on, and set your router's DNS settings directly to the BedrockConnect DNS with the IPv6 DNS address (IPv6 address can be found in the troubleshooting page)
For Xbox, you can try hosting the BedrockConnect server locally, and join through LAN in the "Friends" tab of the Minecraft main menu.

Passed that, if nothing else works, not much else can be done. It's an unofficial bypass at the end of the day, it's not guaranteed to work.
