### ISSUE TITLE
*.network domain names are invalid

### ISSUE THREAD

**Issue by markbrouch** [Pugmatt/BedrockConnect#176]
`*.network` domain names (e.g. `test.example.network`) are invalid when entered and result in the following error:
```
Enter a valid address. (E.g. play.example.net, 172.16.254.1)
```

I think you just need to adjust the regex at https://github.com/Pugmatt/BedrockConnect/blob/ce07489fb06d06614943515b5e5cd6656832b8a5/serverlist-server/src/main/com/pyratron/pugmatt/bedrockconnect/listeners/PacketHandler.java#L190 to allow for longer domain names.

**Comment by Pugmatt** [comment]
Good catch, thanks for posting this. Surprised this hasn't been caught until now. A bug fix has now been released on the latest version and main public instance.

**Comment by markbrouch** [comment]
working great now, thanks for the quick fix!
