### ISSUE TITLE
Xbox one and switch error I can’t find the problem

### ISSUE THREAD

**Issue by TheSquirrelGod** [Pugmatt/BedrockConnect#177]
When attempting to connect to a server ive added to the list on Xbox one or switch I received the error “ java.lang.IllegalStateException: failed to create a child event loop” I have verified that both dns and port for the server are correct as well as having ipv4 and I’m not sure what the issue is, I was able to get into the server once after trying repeatedly for a long while but only on Xbox one. Any help would be great.

**Comment by Pugmatt** [comment]
Is that error happening when you're joining a server from the BedrockConnect serverlist? If so, that's an error from the server you're trying to join, not BedrockConnect.

**Comment by TheSquirrelGod** [comment]
Yes it’s when I try to join a server from the bedrockconnect servers list. I’m not sure why it worked only sometimes.. I will look further into the issue. Good to know that the server is the problem! Just as a note I was attempting to connect to mc.thealater.tk
