### ISSUE TITLE
Not connecting to server list [Xbox] [1.14.30]

### ISSUE THREAD

**Issue by DoggNeedsThis** [Pugmatt/BedrockConnect#18]
I forgot to clarify, I'v tried everything you said, Including commenting. No help.

**Comment by Pugmatt** [comment]
Don't see a comment from you on that video.

**Comment by DoggNeedsThis** [comment]
Yes

**Comment by DoggNeedsThis** [comment]
Iv looked in the description and everything

**Comment by Pugmatt** [comment]
Could you send a screenshot of both the programs open?

**Comment by DoggNeedsThis** [comment]
Iv been using DNS: 104.238.130.180

I dont have a pc and I dont know how to link photos, sorry.

**Comment by Pugmatt** [comment]
Then you're not doing the local solution, you had said you were following the link I had sent which was for setting up Bedrock connect locally on your PC.

If you have no PC, you can try the Android solution. If you don't have an android, then unfortunately nothing can really be done, as that's all the solutions available currently.

Step 1. Download the PocketMine-MP App it's on the Google Playstore. 
Step 2. Download this file: https://www.mediafire.com/file/6col1xvcisf0pcs/PocketMine-MP.phar/file
Step 3. Go to the PocketMine-MP "my files" tab & press "Downloads" then press "Move" chose "internal storage"
Step 4. Scroll down until you see PocketMin-MP press it & once again scroll down until you see "PocketMine-MP.phar" then press that.
Step 5. You should be given the option to either "Replace or Rename" the file chose to replace it.
Step 6. Go back into the App & start your Server open the console menu & type "op [username]" this will allow you to take control of the Server when you join.
Step 7. Reload Minecraft (with your phone still on) go to the Friends tab then you should see the Server under "LAN Games"
Step 9. Once inside the Server type "/transferserver 104.238.130.180 19132"
