### ISSUE TITLE
Update server to support 1.16.220

### ISSUE THREAD

**Issue by epiixgd76** [Pugmatt/BedrockConnect#182]
On nintendo switch the system forces to update minecraft to use online features, and 1.16.220 is unsupported

**Comment by Pugmatt** [comment]
The servers were fully updated 30 minutes ago, and 1.16.220 supported. When did you last try to connect?

**Comment by Pugmatt** [comment]
One of the servers was having issues since the update, which should be fixed now. Give it another try.
