### ISSUE TITLE
Nintendo Switch no longer works for me...

### ISSUE THREAD

**Issue by HuskyPuppers** [Pugmatt/BedrockConnect#183]
Just connects right to cubecraft, lifeboat, the hive, etc.

**Comment by Pugmatt** [comment]
If you haven't already, please check the troubleshooting, as it has a section on this: https://github.com/Pugmatt/BedrockConnect/wiki/Troubleshooting#joining-the-featured-servers-still-directs-to-the-actual-servers-and-not-the-serverlist

**Comment by HuskyPuppers** [comment]
Solved the issue, apparently xfinity blocks custom dns on its cheaper plans.

**Comment by HuskyPuppers** [comment]
Solved it by creating a custom hosts file on my PC and hotspotting in using my Switch,

**Comment by Pugmatt** [comment]
> Solved it by creating a custom hosts file on my PC and hotspotting in using my Switch,

Glad to hear you got it working. Interesting solution, thanks for sharing. I'll take note of this.
