### ISSUE TITLE
no luck getting this to work remotely

### ISSUE THREAD

**Issue by enlighten1self** [Pugmatt/BedrockConnect#185]
do i need to run server and bedrock connect on separate local computers? do you recommend hosting bedrock connect by other means? i cannot connect to my server using the provided DNS either. does VPN affect connection? thank you!

**Comment by Pugmatt** [comment]
Can you expand on what part of the process it stops working? Does it throw an error, or does it just currently go to the default official servers?

Depending on the VPN, it might be overriding the DNS. Do you have any DNS settings for your VPN that can be configured?

**Comment by enlighten1self** [comment]
> Can you expand on what part of the process it stops working? Does it throw an error, or does it just currently go to the default official servers?
> 
> 
> 
> Depending on the VPN, it might be overriding the DNS. Do you have any DNS settings for your VPN that can be configured?

i am running on my comcast router without VPN. but i am trying to access from a VPN router remotely. im not getting any errors, only showing featured servers. at most sometimes it will say cant connect to world. but can server and bedrock connect run together? i changed MC port to avoid an error where bedrock connect and server couldnt share the port

**Comment by Pugmatt** [comment]
Yes, you can host the server and BedrockConnect instance on the same machine. Just make sure you changed the port of the Minecraft server, and not the BedrockConnect server, as BedrockConnect needs to be on port 19132.

Just to clarify about your setup, the servers are running on the machine connected to the Comcast router without VPN, and your game console is connected to a VPN, correct?

**Comment by enlighten1self** [comment]
yes that is right! i might give it another shot, but pretty much only thing i cant do, is turn off ipv6 ok router. i can do it on laptop if that will help?

**Comment by Pugmatt** [comment]
You can try on the laptop, but I imagine the issue is somehow the VPN connection is ignoring the DNS set in the game console settings, if that's currently where you have the DNS set.

Not sure how you have the VPN setup, but if it's like a hotspot hosted from your computer to allow your game console to connect to, you can try setting the DNS address directly into the internet settings. (Similiar to https://support.nordvpn.com/Connectivity/Windows/1088041672/Change-your-DNS-servers-on-Windows.htm)

Also make sure that all ports are port forwarded correctly, port 19132, 53, and whatever the port number is for your Minecraft server.

**Comment by enlighten1self** [comment]
i will try this again and report my outcome. thank you for taking the time to address my issue!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by enlighten1self** [comment]
it didnt work for me. mainly came back with an error even on a local client. do i need to run docker?

**Comment by Pugmatt** [comment]
What was the error? And you shouldn't need docker.

**Comment by enlighten1self** [comment]
im going to set it up on another device and will see if that helps.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
