### ISSUE TITLE
Can we Use This for PC also 

### ISSUE THREAD

**Issue by LeontKing2** [Pugmatt/BedrockConnect#186]

**Comment by kmpoppe** [comment]
Yes, if you're playing the Windows Store provided Bedrock Version, than this server can also be used - YET, you don't need it, because on PC Bedrock you can manually add other server addresses, something the console editions don't allow.

Kai

**Comment by LeontKing2** [comment]
Cool But when i join by the local server lists it doesnt work

**Comment by LeontKing2** [comment]
Its say Unable to connect

**Comment by LeontKing2** [comment]
?

**Comment by LeontKing2** [comment]
@kmpoppe ?

**Comment by kmpoppe** [comment]
I cannot really service that because I don't know your settings and everything. If you have the Serverlist Server on your PC and want to connect to it, there's a YouTube tutorial Video in the README that you can follow. 

There are quite a few steps to follow but they are relatively easy.

**Comment by LeontKing2** [comment]
Ok what is the link to that video @kmpoppe

**Comment by kmpoppe** [comment]
You should read this section: Hosting your own serverlist server
Because you need to check what things your PC needs.

**Comment by LeontKing2** [comment]
Ok

**Comment by LeontKing2** [comment]
I am not able to Join the server but it shows the server name

**Comment by LeontKing2** [comment]
Should i turn of ipv6?

**Comment by LeontKing2** [comment]
I dont think i have to since i am hosting this locally right?

**Comment by LeontKing2** [comment]
@Pugmatt can you help?

**Comment by Pugmatt** [comment]
Can you expand what you mean by "shows the server name"?

You still might have to turn off IPv6, as it has more to do with how the console connects to any DNS server, local or not.

**Comment by LeontKing2** [comment]
I mean that it shows the server list at the friends list locally but i cannot connect @Pugmatt

**Comment by Pugmatt** [comment]
I see, odd. Any errors in the BedrockConnect server window on your computer?

**Comment by timvandenhof** [comment]
The Windows store (UWP) apps, can not connect to localhost by default. It's a security feature.

You can bypass it:
`checknetisolation loopbackexempt -a -n=<package family name>`
Where package family name is the name of the Minecraft UWP app.
Replace `-a` widh `-d` to undo the bypass.

Documentation:
https://docs.microsoft.com/en-us/windows/uwp/communication/interprocess-communication#loopback

This is usefull for developing purposes, for bedrock connect or just a regular localhost hosted minecraft server.

**Comment by LeontKing2** [comment]
I already did that

**Comment by LeontKing2** [comment]
I did that when i hosted my own pocketmine-mp server

**Comment by LeontKing2** [comment]
@timvandenhof anyother solution?

**Comment by LeontKing2** [comment]
I am pretty sure that other public servers are running properly like the official bedrockconnect official server 
I tried to connect to it it worked but why not localhost:(

**Comment by LeontKing2** [comment]
~~~
Why:(

**Comment by LeontKing2** [comment]
~~~
-= BedrockConnect =-
Local IPv4 IPs:
VirtualBox Host-Only Ethernet Adapter: 192.168.56.1
Realtek PCIe GbE Family Controller: 192.168.0.107
LogMeIn Hamachi Virtual Ethernet Adapter: 25.31.164.122

Which IP should be used for the DNS records: 192.168.0.107

Server Limit: 100
Port: 19132

Loaded 0 custom servers
Bedrock Connection Started: 0.0.0.0:19132
null disconnected

**Comment by LeontKing2** [comment]
@Puggmat

**Comment by LeontKing2** [comment]
@Pugmatt

**Comment by Pugmatt** [comment]
Can you confirm that you're on the latest JAR version, https://github.com/Pugmatt/BedrockConnect/releases/tag/1.6.4?

Also no need to @ me, I'll get to you when I can.

**Comment by LeontKing2** [comment]
?

**Comment by LeontKing2** [comment]
@Pugmatt  I have java 16 and 11 and jre 1.8.0 
And the latest BedrockConnect Jar

**Comment by LeontKing2** [comment]
... i am running the server locally on my pc and i am joining from the same pc

**Comment by LeontKing2** [comment]
> Have you tried starting up a local bedrock edition server and verified that that works with the same endpoint (localhost, default port)? If that is not working, than it probably is an isolation and/or firewall related issue. Please try that and have some patience, we are all doing this in our spare time.
> 
> No need to ping us, we do receive notifications for each reply already.

I dont think its a firewall issue since its showing me the server list locally

**Comment by LeontKing2** [comment]
Just in case  i am pinging @Pugmatt

**Comment by Pugmatt** [comment]
- Try downgrading to Java 8. It shouldn't need to do from what I know, but worth a try
- I've noticed you only mentioned it popping up and showing on the "Friends" tab. Have you tried joining it through the "Servers" tab by adding it? As that's an option on the PC version.

**Comment by LeontKing2** [comment]
wait i have jdk 11

**Comment by LeontKing2** [comment]
should i downgrade to jdk 8?

**Comment by LeontKing2** [comment]
nvm 
i know why it didnt work

**Comment by LeontKing2** [comment]
generatedns = true was not there

**Comment by kmpoppe** [comment]
@Pugmatt I think you can close this.
