### ISSUE TITLE
unable to stop BedrockConnect with stop or end command in the console

### ISSUE THREAD

**Issue by lcswolf** [Pugmatt/BedrockConnect#188]
I have tried to stop the bedrockconnect server with the normal stop/end command but unable is there a different command being used? just like to be able to restart it once a day via my control panel mostly for my OCD

**Comment by Pugmatt** [comment]
There isn't currently a designated stop/end command implemented. I'll see if I can get one implemented though.

**Comment by lcswolf** [comment]
Awesome thank you :)

**Comment by Pugmatt** [comment]
Latest release now has a stop/end command implementation (can stop the server with either "stop" or "end"): https://github.com/Pugmatt/BedrockConnect/releases/tag/1.6.5

Let me know if that works for your control panel.

**Comment by lcswolf** [comment]
Just tested and works a treat it's great to be able to stop the server gracefully to do any tweaking if/when needed awesome work :)

**Comment by Pugmatt** [comment]
Awesome, glad to hear it works!
