### ISSUE TITLE
Nintendo switch. Unable to connect to world 

### ISSUE THREAD

**Issue by bonedaddycj** [Pugmatt/BedrockConnect#189]
I have done about everything in the books to try and get my servers back but no matter what I do it says " Unable to connect to world" Even the regular Microsoft server I am unable to connect to.

I have tried deleting the game, changing the dns, and turning the switch on and off yet nothing has worked to get my servers back. 

Someone please help.

**Comment by Pugmatt** [comment]
If you have the DNS completely reverted back to normal, and set to "Automatic", I'm unfortunately unsure what it could be, as the system would no longer be connected at all to BedrockConnect.

I would make sure the DNS is completely changed to default, set to Automatic, and I would contact Mojang/Microsoft support and see what they know.

**Comment by Pugmatt** [comment]
If you haven't tried already, you can try setting _**both**_ your primary and secondary to 8.8.8.8 (or 1.1.1.1, 1.0.0.1, 8.8.4.4).

Ultimately what's probably going on, is the Switch's DNS cache isn't clearing, which there isn't much that can be done past setting the DNS back to Automatic (or possibly both to 8.8.8.8 as stated above), and giving it time to clear. If you have access to another internet connection, whether it's at someone else's house or location, try connecting to that, which might clear the DNS cache as well.

I'm not 100% sure how it works, as it has more to do with how the Nintendo Switch system itself functions, but all that is just based off what I know from past experimentation.

**Comment by kylevardy1** [comment]
This is now fixed in minecraft 1.17.1
