### ISSUE TITLE
runtime_block_states.dat in wrong place

### ISSUE THREAD

**Issue by RadiatedMonkey** [Pugmatt/BedrockConnect#19]
The runtime_block_states.dat file is located in the src folder, but I think it's supposed to be in the src/main/resources/tables folder. I can't compile the program without moving it there

**Comment by Pugmatt** [comment]
Sorry for the late response on this. You are correct, thanks for bringing this up. I'm unsure why my compiler has been letting me compile it without it in that folder, but none of the less I moved it and it still works on my side after doing that, so I assume that should now let it work for you.
