### ISSUE TITLE
Ipv6 DNS

### ISSUE THREAD

**Issue by coltonbyu** [Pugmatt/BedrockConnect#190]
I am experiencing an issue with DNS not working due to the Xbox using ipv6. 

Xbox does not allow for ipv6 to be disabled or altered, so the advice as noted in the threads is to disable ipv6 on the router level. Unfortunately, there are many routers out there that dubiously do not allow that, as is the case with the Netgear c7000v2. 

Since I am unable to disable ipv6 for the Xbox or the network, is there a possibility that there is an ipv6 DNS for BedrockConnect that I can set in the router settings? 

I am aware that ipv6 DNS configuration is not available on the Xbox itself, which appears to be the a reason there is no IPv6 DNS address listed in the info (that I can find), but if it's possible for BedrockConnect to support IPv6, I do have the ability to enter that in.

(I would self host to resolve this, but this issue as described is for one of the members of my private bedrock server, who would not be comfortable with this option)

**Comment by Pugmatt** [comment]
Technically I have the main DNS set to accept IPv6 connections, but I've never been able to test it.  Feel free to give it a try with this IPv6 address: 2001:19f0:4009:4126:5400:00ff:fe22:0d52

**Comment by coltonbyu** [comment]
That resolved it perfectly! If anybody has any similar problems this is a very viable solution. Just changed the ipv6 on the router (since the xbox can't) and it was all good. 

This is a netgear nighthawk, so a super common router too.

**Comment by Pugmatt** [comment]
Great to hear! This should come in handy. I'll update the documentation.
