### ISSUE TITLE
Preparation for 1.17

### ISSUE THREAD

**Issue by kmpoppe** [Pugmatt/BedrockConnect#191]
As per [this tweet](https://twitter.com/Minecraft/status/1399380652261265414?s=19) 1.17 will release on Java **and** Bedrock on June 8th.
We should check how to make the protocol update available.

**Comment by Pugmatt** [comment]
The guys over at https://github.com/CloudburstMC/Protocol (The library BedrockConnect uses for protocol) are always on top of it, so I'll be sure to hop on importing the new version of the library once it's ready, or any beta versions.

**Comment by kmpoppe** [comment]
With #192 already merged, I rest my case :-)
Now, onto updating the community servers 🐑

**Comment by Pugmatt** [comment]
New version now released: https://github.com/Pugmatt/BedrockConnect/releases/tag/1.7

Main instance is now updated.

**Comment by kmpoppe** [comment]
I will update my small instances later today, got an appointment without my PC ;-)

I'm very happy, that we are on top of the new protocol version before it releases and so people can start using 1.17 the minute it's available to them. Well done @Pugmatt and @Camotoy :)
