### ISSUE TITLE
xBox One : Unable to join server (UK)

### ISSUE THREAD

**Issue by z1haze** [Pugmatt/BedrockConnect#194]
I am acting as a middleman for this issue, so I want to apologize beforehand on the limited information.

I recently setup a bedrock dedicated server for our community xBox players, and all of them have been able to connect, except one. This one player is in the UK, where all others are in the US. I do not know if this is a coincidence or not. The user has setup the DNS IP's correct, and after locating this github, I even attempted to send him the UK DNS IP thats listed in the readme, but that did not work either.

What I mean by not working: When loading up the game, and going to the 'servers' tab, the server list on the left side seems to populate, but the right panel never actually loads in, therefore they cannot click the join server button. Screenshot for clarity:
https://media.discordapp.net/attachments/797305747066847272/851108833987788870/image0.jpg?width=560&height=747

**Comment by kmpoppe** [comment]
Hey Stephen,

as I'm the culprit of creating the UK server listed, I must tell you that both servers that I provide DO NOT have a DNS service running (I must add this in the README...). That means, if you add those IP addresses as DNSs in the XBOX that won't work (which MIGHT lead to the behaviour shown in your screenshot).

I have learned that's imperative to setup the DNS settings of the consoles correctly and have a working fallback. Has you friend followed the tutorial for the XBOX (https://www.youtube.com/watch?v=g8mHvasVHMs)? Also: I had the same problem on my Switch and it only started working after so many tries...

Also it still also MIGHT have something to do with your friend's ISP as they could have any strange way of preventing any custom settings that I could never ever find out from here.

I think his best chance is to use the main serverlist-server IP as shown in the video.

I'm sorry that I can't provide any more insight.

K

**Comment by z1haze** [comment]
Thanks for your response,

I originally had him using 104.238.130.180 and 8.8.8.8 

When the above configuration, the network connects fine, all checks out, just like in the vids, but when he goes to that server browser, it just shows the infinite loading bar

Im not seeing how or why the ISP would interfere with this process. So far, 15/17 users have been able to connect with the exact same steps.

Do you think If i host my own instance of this tool that it would make a difference? The only difference is just the servers in the list, right?

**Comment by kmpoppe** [comment]
If you host your own instance of the server (and your own DNS that allows everything to work) it will most likely work - the main instance of Pugmatt sometimes has a high load which could also, together with a slow ping from the UK to the US lead the XBOX to not get the Serverlist to work.

The servers on the left will always be the same because they are "Featured" - that's why you use the DNS server to override their addresses with the IP of the Serverlist Server.

K

**Comment by z1haze** [comment]
Yeah, the problem is though that the servers on the left .. they are not even loading their server window on the right where the ‘join’ button would be. So this using cannot even click join server to even be proxied over to the new server Sent from Mail for Windows 10 From: Kai Michael PoppeSent: Sunday, June 6, 2021 11:05 AMTo: Pugmatt/BedrockConnectCc: Stephen Hendricks; AuthorSubject: Re: [Pugmatt/BedrockConnect] xBox One : Unable to join server (UK) (#194) If you host your own instance of the server (and your own DNS that allows everything to work) it will most likely work - the main instance of Pugmatt sometimes has a high load which could also, together with a slow ping from the UK to the US lead the XBOX to not get the Serverlist to work.The servers on the left will always be the same because they are "Featured" - that's why you use the DNS server to override their addresses with the IP of the Serverlist Server.K—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Pugmatt** [comment]
Do you know if the player was able to join the original featured servers before changing the DNS? If the DNS was correctly overriding, the featured server motds (Message under the icons) should be saying "Join To Open Server List", but they have the original featured server motds showing as seen in the screenshot. Which makes me think the infinite loading is a separate issue, as even if the right side loads it wouldn't probably connect to the BedrockConnect serverlist.

As for why the DNS might not be correctly overriding, the user's network might be on IPv6. I would have the user check their router settings to check for this, and if they do, they have two options: 
  * Disable IPv6 on your router, if possible. Here's a tutorial by jbob3mm that shows how to disable this: https://www.youtube.com/watch?v=3FhBEI55__s
  * Set the DNS directly in your router settings, using 2001:19f0:4009:4126:5400:00ff:fe22:0d52 as the primary, and 2001:4860:4860::8888 as the secondary (or any other popular DNS that supports IPv6 for the secondary)

**Comment by z1haze** [comment]
What would the user do if they do not have a computer or device to access their router? I think ipv4 might be an issue here. Sent from Mail for Windows 10 From: MatthewSent: Sunday, June 6, 2021 11:11 AMTo: Pugmatt/BedrockConnectCc: Stephen Hendricks; AuthorSubject: Re: [Pugmatt/BedrockConnect] xBox One : Unable to join server (UK) (#194) Do you know if the player was able to join the original featured servers before changing the DNS? If the DNS was correctly overriding, the featured server motds (Message under the icons) should be saying "Join To Open Server List", but they have the original featured server motds showing as seen in the screenshot. Which makes me think the infinite loading is a separate issue, as even if the right side loads it wouldn't probably connect to the BedrockConnect serverlist.As for why the DNS might not be correctly overriding, the user's network might be on IPv6. I would have the user check their router settings to check for this, and if they do, they have two options:Disable IPv6 on your router, if possible. Here's a tutorial by jbob3mm that shows how to disable this: https://www.youtube.com/watch?v=3FhBEI55__sSet the DNS directly in your router settings, using 2001:19f0:4009:4126:5400:00ff:fe22:0d52 as the primary, and 2001:4860:4860::8888 as the secondary (or any other popular DNS that supports IPv6 for the secondary)—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Pugmatt** [comment]
There wouldn't be much that can be done unfortunately. Do they have a phone or any kind of device to access a web browser?

**Comment by z1haze** [comment]
I actually just asked. Ill report back with any progress. Thanks for your help Sent from Mail for Windows 10 From: MatthewSent: Sunday, June 6, 2021 11:13 AMTo: Pugmatt/BedrockConnectCc: Stephen Hendricks; AuthorSubject: Re: [Pugmatt/BedrockConnect] xBox One : Unable to join server (UK) (#194) There wouldn't be much that can be done unfortunately. Do they have a phone or any kind of device to access a web browser?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by z1haze** [comment]
ok, nevermind .. the dude is unwilling to try to get into his router, so i dont really care to help him then. thanks for your time.
