### ISSUE TITLE
Connecting from 1.17 PC Java Edition not working

### ISSUE THREAD

**Issue by paul** [Pugmatt/BedrockConnect#197]
Downloaded the latest 1.17 updates for Bedrock connect, and the bedrock server. I'm able to connect from the Switch. On PC with the 1.17 java edition, when I add the bedrock connect server by IP, I get an error:

> Failed to connect to the server
> 
> io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: filetank3.home/192.168.0.60:25565

(where `filetank3.home` is the hostname of the server with ip `192.168.0.60`, running bedrock connect)

If I manually specify the port `19132`, I get the same error message, with the port changed `filetank3.home/192.168.0.60:19132`.

It seems like the "Java Edition" port is `25565` and bedrock is `19132`. I don't recall the last version of the Java edition I tried when this worked, but it did work in the past. Is this expected to work, or has something changed between the Java and Bedrock version in 1.17?

Thanks!

**Comment by Pugmatt** [comment]
BedrockConnect is running the Bedrock Edition protocol, so it only accepts connections from Minecraft Bedrock Edition, not Java edition. Bedrock Edition runs on a completely different protocol from Java edition, so if it did work in the past that would be very strange.

Only thing currently possible in relation to Java Edition, is players playing on Bedrock Edition can join Java Edition servers using a tool called Geyser, which some people will use BedrockConnect to connect to a Geyser instance proxy to join a Java Edition server. Maybe this is what you're thinking of?

**Comment by paul** [comment]
It turns out I actually have both, and only thought I was running the Java edition in the past. During some update in the last few weeks, Windows removed the "Minecraft" shortcut from my desktop that launched the Windows 10 version. And if I hit "Start", type "Minecraft", all the entries that come up start the Java edition. 

I now have to go through the Microsoft Store, find Minecraft in my library, and launch it from there. Anything else launches the Java edition, and I can't even figure out how to uninstall that one so it doesn't happen.

Anyways, not a BedrockConnect problem, so closing. Thanks for looking.
