### ISSUE TITLE
Nintendo Switch Error

### ISSUE THREAD

**Issue by stationswift001** [Pugmatt/BedrockConnect#198]
Whenever I try to connect to my aternos sever on switch, I get the error:
![2021-06-12-173241](https://user-images.githubusercontent.com/36418561/121790377-6ab11f80-cba4-11eb-828f-fd4aab8289f1.jpg)

**Comment by stationswift001** [comment]
(you need to authenticate to microsoft services)

**Comment by Pugmatt** [comment]
If it's an error thrown when you join your server, it's already off the BedrockConnect connection, so it would be an issue with the server you're trying to join.

So I would ask Aternos support or check if your settings are setup correctly.

**Comment by stationswift001** [comment]
Got it, it was temporary, doesn't throw that now. Thanks for your help anyways.
