### ISSUE TITLE
PaletteManager ClassCastException

### ISSUE THREAD

**Issue by RadiatedMonkey** [Pugmatt/BedrockConnect#20]
![image](https://user-images.githubusercontent.com/44266876/77906716-b53cc980-7288-11ea-8657-de024eacede6.png)

When I have compiled the program and try to run it, I get this error

**Comment by jokarwent** [comment]
Same here.

**Comment by Gouster4** [comment]
Here too.

**Comment by Pugmatt** [comment]
Could you guys supply the name of the IDE you're using, and the version of Java? I haven't been able to replicate this in IntelliJ, but if I match the setup I might be able to.

**Comment by Gouster4** [comment]
IntelliJ Ultimate 2019.3.5
Java 11 while building.
OpenJDK 8 when testing.

**Comment by Pugmatt** [comment]
I think my dependencies weren't correctly synced up, was now able to replicate this. My latest push should fix the issue. Pull and see if the issue still occurs.

**Comment by Gouster4** [comment]
@MartinX3

**Comment by MartinX3** [comment]
Thank you, it's fixed! :)
