### ISSUE TITLE
Xbox One - Unable to connect to world

### ISSUE THREAD

**Issue by IndigoAlkali** [Pugmatt/BedrockConnect#201]
Currently receiving an error when trying to join on Xbox One (Bedrock 1.17). I've repeatedly checked the primary and secondary DNS settings, tried the fix posted previously in #196, and also ensured that the server I'm trying to join is online, properly updated and working properly, all to no avail. I still get the "Unable to connect to world" error.

**Comment by Pugmatt** [comment]
Just to double-check, the "Unable to connect to world" error comes when trying to join the serverlist server, correct? Or are you getting it when joining your server from the serverlist server.

**Comment by IndigoAlkali** [comment]
> Just to double-check, the "Unable to connect to world" error comes when trying to join the serverlist server, correct? Or are you getting it when joining your server from the serverlist server.

I'm getting it when I'm trying to join my server from the serverlist.

**Comment by djm228** [comment]
> 
> 
> > Just to double-check, the "Unable to connect to world" error comes when trying to join the serverlist server, correct? Or are you getting it when joining your server from the serverlist server.
> 
> I'm getting it when I'm trying to join my server from the serverlist.
> 
> Edit: Here is a video of what happens when I try to connect:
> https://1drv.ms/v/s!Ahtlkt_MR8CsgjH8T26rMKpfskUa?e=Ee4H7y

I'm experiencing the same issue on my Xbox Series X. I'm able to connect to the server(s) from my PC on the same network, so the server is up and working like it should.

**Comment by Pugmatt** [comment]
Once you begin joining a server from the BedrockConnect serverlist, it's completely off the BedrockConnect connection, so any errors being thrown are from the server you're trying to join. So I'm unsure what the issue here could be.

Currently, I think it's an issue with the game itself with all the recent bugs introduced since the update, but I'll see what I can find.

**Comment by IndigoAlkali** [comment]
> Once you begin joining a server from the BedrockConnect serverlist, it's completely off the BedrockConnect connection, so any errors being thrown at that point are from the server you're trying to join. So I'm unsure what the issue here could be.
> 
> Currently, I think it's an issue with the game itself with all the recent bugs introduced since the update, but I'll see what I can find.

Any fixes?

**Comment by Pugmatt** [comment]
> > Once you begin joining a server from the BedrockConnect serverlist, it's completely off the BedrockConnect connection, so any errors being thrown at that point are from the server you're trying to join. So I'm unsure what the issue here could be.
> > Currently, I think it's an issue with the game itself with all the recent bugs introduced since the update, but I'll see what I can find.
> 
> Any fixes?

Unfortunetly not. Again, this would be a problem with the game itself or the server you're trying to join, so not much that can be done on my end unfortunetly.
