### ISSUE TITLE
Doesnt Work With New Switch Update 1.17.2

### ISSUE THREAD

**Issue by rafesoft** [Pugmatt/BedrockConnect#202]
This appears to have stopped working on switch as of version 1.17.2 (Released on switch a day or two ago)
I have done every troubleshooting method possible multiple times. I hope they didn't permanently patch it in a way that makes this no longer possible.

**Comment by Pugmatt** [comment]
Can you expand on what part is not working, and what errors are throwing if any? Is it just connecting to the original featured servers, or is it throwing an error of some kind?

**Comment by rafesoft** [comment]
Sorry, yes I should have provided that information :) 
It's just connecting to the original featured servers. No error message, no connection trouble. 
Feel free to let me know if I can provide any other details!

**Comment by Pugmatt** [comment]
It appears to still be redirecting to the serverlist for others, so I don't think it's patched.

I'm unsure what to suggest if you've gone through every troubleshooting method already. The issue that causes this is usually IPv6 being enabled on your network, if you haven't checked your router already. Even if you don't have IPv6 enabled though, you can still try setting the DNS directly into your router settings (with the regular IPv4 addresses).

**Comment by rafesoft** [comment]
Hmm, sounds like it is for sure a problem with my environment then. Feel free to close the issue. Thanks For your assistance! 
I will have to try setting my router DNS, I skipped that troubleshooting step because I wasn't sure what implication that would have for other services I host on my network.
