### ISSUE TITLE
Issue with connecting

### ISSUE THREAD

**Issue by JJoshua04** [Pugmatt/BedrockConnect#203]
Hi when I open a featured server it plays the normal server and I have the DNS on so idk what's happening u might have to fix it and my router I checked that so I think it's the dns well the ipv6 stuff I think rn it doesn't work so u might have to fix it

**Comment by Pugmatt** [comment]
The DNS is currently functional for others, so it's either your network or the game console.

Check all the troubleshooting under "Joining the Featured Servers still directs to the actual servers and not the serverlist..." if you haven't already: https://github.com/Pugmatt/BedrockConnect/wiki/Troubleshooting

If nothing works, I recommend setting the DNS directly through your router.
