### ISSUE TITLE
Uninstall/Fix Problem

### ISSUE THREAD

**Issue by aparker87** [Pugmatt/BedrockConnect#207]
Is there any way that I could uninstall Bedrock Connect? Now that I downloaded it I can’t get into the Hive and it’s really annoying. I know that this problem was caused by Bedrock Connect.

**Comment by Pugmatt** [comment]
Simply set the DNS settings in your game console network settings back to Automatic, and wait for the DNS cache to clear.

I'll look into the Hive issue. Hive has always been a bit of an issue due to their IPs always changing.

**Comment by aparker87** [comment]
Thank you so much. About how long does it usually take the cache to clear?

**Comment by Pugmatt** [comment]
Maybe about 5-10 minutes. Really isn't a set time. You can try setting both DNS's to 8.8.8.8 to try and force it.

I also released a patch for the main instance (104.238.130.180) just now that should fix the issue with the Hive.
