### ISSUE TITLE
Xbox: Subnet Mask

### ISSUE THREAD

**Issue by rockdude129** [Pugmatt/BedrockConnect#208]
I enter 8 8 8 8 in the subnet mask (secondary dns now changed to subnet mask) and it's not working

**Comment by tomrow** [comment]
Subnet mask is not a DNS address, and if changed to a differing value, your network access will stop working. If your private (LAN/WLAN) IP address starts with 192.168, set the subnet mask to 255.255.255.0.

**Comment by tomrow** [comment]
The easiest way is to re-enable DHCP or Auto-obtain settings for your IP address (not DNS). This should be a check-box or toggle switch on the setting screen for your console.

If this is not an option for you, or the console does not have special exceptions for DNS settings, then you do still have other options:
If you have a Windows computer, you can find your Subnet Mask by running `ipconfig` from the Windows command line (`cmd`).
You will see a list of all network adapters on the system with their set configuration. Look for one containing a default gateway, and a name that matches the way your computer is connected. The adapter may look something like this: 
```
Ethernet adapter Ethernet:

   Connection-specific DNS Suffix  . : home
   IPv4 Address. . . . . . . . . . . : 192.168.1.162
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . : 192.168.1.254
                                       
```
If you want to connect to the same network device as the computer (doesn't matter through Ethernet or WiFi), input the same subnet mask into your console as is displayed on the computer.
