### ISSUE TITLE
Could Not Connect: Outdated Server

### ISSUE THREAD

**Issue by PatMillman** [Pugmatt/BedrockConnect#211]
So, my friends and I are trying to connect to my Minecraft Server. 
Whenever we try to join on one of our switches, we get the error "Could Not Connect: Outdated Server"
We're all running the latest versions of the game, 1.17.10- and I can connect, so can the others. Just not on this one switch can we access the server menu.

**Comment by Pugmatt** [comment]
Just to clarify, is that error thrown when you're connecting to the BedrockConnect serverlist, or when joining your server from the BedrockConnect serverlist?

**Comment by PatMillman** [comment]
When we're connecting to the BedrockConnect Server List. (or at least, that's what I've been told.)
Also, it seems to have fixed itself! I think it has fixed itself. I don't know if there's any info you may need otherwise!

**Comment by DinkleMinded** [comment]
Same issue here, started at the same time as @PatMillman .  Getting "Could Not Connect: Outdated Server!" on the client (W10 v1.17.10) about 2 seconds after clicking "Join server".  I don't get the BedrockConnect serverlist at all.

Quick look with Wireshark shows me a few handshake messages (conenction request, reply, connected ping, connected pong), then a larger message (fragmented into 28 parts) going from the client to the BedrockConnect server, some NAKs from BedrockConnect through all of that but the retries seem to go through.

But after the 28th fragment BC sends the following:

`
0020   ............................................................ 80 04 00 00 60 00   
0030   48 04 00 00 00 00 00 00 fe 63 65 62 60 60 60 02   H........ceb```.
0040   00                                                .
`
(ethernet, IPv4 and UDP layers removed for privacy)

...and that's the last thing sent by BC.  The client responds with 3 packets then calls it quits as well.

**Comment by Pugmatt** [comment]
> Same issue here, started at the same time as @PatMillman . Getting "Could Not Connect: Outdated Server!" on the client (W10 v1.17.10) about 2 seconds after clicking "Join server". I don't get the BedrockConnect serverlist at all.
> 
> Quick look with Wireshark shows me a few handshake messages (conenction request, reply, connected ping, connected pong), then a larger message (fragmented into 28 parts) going from the client to the BedrockConnect server, some NAKs from BedrockConnect through all of that but the retries seem to go through.
> 
> But after the 28th fragment BC sends the following:
> 
> ```
> 0020   ............................. 80 04 00 00 60 00   
> 0030   48 04 00 00 00 00 00 00 fe 63 65 62 60 60 60 02   H........ceb```.
> 0040   00                                                .
> ```
> 
> (ethernet, IPv4 and UDP layers removed for privacy)
> 
> ...and that's the last thing sent by BC. The client responds with 3 packets then calls it quits as well.

Thanks for looking into this and posting the Wireshark log. I'm not able to replicate this on my end, on either Windows 10 or Switch, both on latest version.

Are you currently connecting to this main instance 104.238.130.180, or a different one from the list? (https://github.com/Pugmatt/BedrockConnect#publicly-available-bedrockconnect-instances) I did receive the error when connecting to the instances maintained by @kmpoppe and @darkmoi3108 , but I believe that is because they haven't been updated to the 1.17.10 release.

**Comment by DinkleMinded** [comment]
Using my own instance on the LAN, and I had totally missed your merge that specifically said "1.17.10".  😞 
Just pulled the latest and restarted... all works fine for me now.  😳 Sorry for the bother, and thanks for tolerating us.

**Comment by kmpoppe** [comment]
Sorry for the late update, my two instances are now updated, was away on a business trip.
Happy mineing and crafting yall!

**Comment by iAmStoni** [comment]
Problem Came again. Minecraft uploaded yesterday to 1.21.60 and Since this changin the screen calls "host using an older version. Everyone should upload and try again." And Exit with a ^^
