### ISSUE TITLE
Server Outdated?! ;(

### ISSUE THREAD

**Issue by wrybit** [Pugmatt/BedrockConnect#217]
Hi,

sadly recently I always get the MSG: "Server Outdated" if I use the DNS Workaround on any of the default 7 Servers.
I'm using a xBox One and the current Minecraft Bedrock Edition 1.17.11 and an IPv4 Network.

Any Suggestions?

Greez Jens

**Comment by Pugmatt** [comment]
Can you double-check that you're not opted-in to any beta versions of the game? Also, is this through the main DNS instance or are you hosting your own?

The server is currently up to date, and this is the first complaint I've heard, so I'm not sure currently what the issue could be.

**Comment by wrybit** [comment]
Thanks for the quick reply! :)
I use the DNS → 104.238.130.180 & 8.8.8.8 ← and after a Router Restart, it worked fine again. 
Sorry for the Issue.
