### ISSUE TITLE
Error while attempting to install jar file on Ubuntu

### ISSUE THREAD

**Issue by cogitate228** [Pugmatt/BedrockConnect#218]
Hi,

Not sure what I am doing wrong, but I download the jar file via curl but encounter the following error:

:/var/tmp$ curl -O -# https://github.com/Pugmatt/BedrockConnect/releases/BedrockConnect-1.0-SNAPSHOT.jar
################################################################################################################################################################################################################### 100.0%
:/var/tmp$ sudo java -jar BedrockConnect-1.0-SNAPSHOT.jar
Error: Invalid or corrupt jarfile BedrockConnect-1.0-SNAPSHOT.jar
$ uname -r
5.4.0-81-generic
:/var/tmp$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"

**Comment by Pugmatt** [comment]
The URL you're trying to curl from is 404'ing, plus GitHub's release URL's typically require some more parameters in curl since it redirects. Try:

`curl -LJO https://github.com/Pugmatt/BedrockConnect/releases/download/1.8/BedrockConnect-1.0-SNAPSHOT.jar`
