### ISSUE TITLE
Arch support

### ISSUE THREAD

**Issue by FivePixels** [Pugmatt/BedrockConnect#219]
Is there going to be any Arch support added? I tried running the install_bind script, and it failed saying the OS was unsupported.

**Comment by Pugmatt** [comment]
Starting on line 67 of the install_bind script, it has a check for the OS so it knows what commands to run. You would just need to add your version to the check, and change any commands in the file that Arch might not support. As long as Arch can run bind it should be possible.

**Comment by FivePixels** [comment]
Got it, opening a PR for the install.
