### ISSUE TITLE
public BedrockConnect serverlist server down? 

### ISSUE THREAD

**Issue by NicolasHelb** [Pugmatt/BedrockConnect#22]
As of today 4 hours ago my console friends can't connect to the bedrock serverlist,
I tested on my own on w10 and can't directly connect to it which lead me to believe it is a minecraft server (the serverlist) problem and not a dns server one.
Is there any way to get update from this problem, do you not have the fund/want to maintain it (which is perfectly understandable), do i need to set up my own for my friends? sorry for the off topic on this ticket but i could not find another way to contact you (discord, email, any other way)

Thanks for your hard work.

**Comment by Pugmatt** [comment]
Server was having some issues and stopped running, should be back up and running now. Give it another try.
