### ISSUE TITLE
Xbox Live Gold required?

### ISSUE THREAD

**Issue by JonTabor** [Pugmatt/BedrockConnect#220]
Couldn't find this in the documentation, but is Xbox Live Gold required to use this? I don't have it, and as such I get the "could not join Realms" message on the servers tab instead of a server list.

**Comment by Pugmatt** [comment]
Yes, Xbox Live Gold is needed to join servers.

**Comment by JonTabor** [comment]
Thought so, thanks.  The reason I ask is, the original implementation of Bedrock Dedicated Server worked flawlessly without Xbox Live Gold, and it suddenly needed it (in fact, they have a bug, BDS-1634, about it).  Was hoping this was a viable workaround.
