### ISSUE TITLE
Nintendo Switch Connection Error

### ISSUE THREAD

**Issue by stationswift001** [Pugmatt/BedrockConnect#224]
After updating to 1.17.30, I get an error when trying to join the BedrockConnect server:
"Could not connect: Outdated server!"

**Comment by z1haze** [comment]
same! (xbox)

**Comment by Annyzzang** [comment]
Same hope it could be resolved soon

**Comment by marcb1387** [comment]
this was released to everyone on bedrock today so just need to give it time for the update to get to everyone and the servers.

**Comment by Pugmatt** [comment]
The update has now been released. Thank you for everyone's patience.

**Comment by kmpoppe** [comment]
My instances will update once I'm fully awake.

**Comment by z1haze** [comment]
🎆 thanks!
