### ISSUE TITLE
Use PiHole instead?

### ISSUE THREAD

**Issue by joshbgosh10592** [Pugmatt/BedrockConnect#232]
Not really an issue, but more of a question...
Could we just use another DNS server like Pi.Hole and just redirect DNS queries so we don't have to modify the Switch network settings (since it's already set to point to my Pi.Hole for it's DNS)?
If so, what values?
Would it just be [THIS](https://github.com/Pugmatt/BedrockConnect#using-your-own-dns-server) info? Then, any time any switch connected to my network (DHCP issues out Pi.Hole as it's DNS server), it would just work?

**Comment by kmpoppe** [comment]
Hi Josh!

Apart from me using a local instance of Bedrock Connect on my Pi, that Pi is also the central DNS on my network that has zones for every of the listed servers that redirect to the local instance.

Works absolutely fine and my switch just gets it's settings via DHCP :)

Kai

**Comment by adamlocker** [comment]
> Not really an issue, but more of a question... Could we just use another DNS server like Pi.Hole and just redirect DNS queries so we don't have to modify the Switch network settings (since it's already set to point to my Pi.Hole for it's DNS)? If so, what values? Would it just be [THIS](https://github.com/Pugmatt/BedrockConnect#using-your-own-dns-server) info? Then, any time any switch connected to my network (DHCP issues out Pi.Hole as it's DNS server), it would just work?

Just confirming that this works for me (on XB1) for anyone who like me finds this several months later. Added the DNS from the table linked to the local DNS on the Pi Hole admin page and worked first time.

**Comment by kmpoppe** [comment]
@Pugmatt I think this was answered and the issue could be closed?

**Comment by Warmax356** [comment]
> Not really an issue, but more of a question... Could we just use another DNS server like Pi.Hole and just redirect DNS queries so we don't have to modify the Switch network settings (since it's already set to point to my Pi.Hole for it's DNS)? If so, what values? Would it just be [THIS](https://github.com/Pugmatt/BedrockConnect#using-your-own-dns-server) info? Then, any time any switch connected to my network (DHCP issues out Pi.Hole as it's DNS server), it would just work?

what solution did you take?

i currently have a PIhole setup and looking to run bedrock connect on it aswell, but my concearn is with the DNS server deployed with it, as i see it as a possible clash, hence why i am asking.

**Comment by Warmax356** [comment]
> > Not really an issue, but more of a question... Could we just use another DNS server like Pi.Hole and just redirect DNS queries so we don't have to modify the Switch network settings (since it's already set to point to my Pi.Hole for it's DNS)? If so, what values? Would it just be [THIS](https://github.com/Pugmatt/BedrockConnect#using-your-own-dns-server) info? Then, any time any switch connected to my network (DHCP issues out Pi.Hole as it's DNS server), it would just work?
> 
> Just confirming that this works for me (on XB1) for anyone who like me finds this several months later. Added the DNS from the table linked to the local DNS on the Pi Hole admin page and worked first time.

i did this for the US offical, and the 3 european ones (based in the med so the eu ones are closest with lowest latency)
sadly the EU ones aren't up-to-date and tend to be out-of-date most of the time, though i think the OP originally asked if he can self host on the same PI that Pihole runs on
