### ISSUE TITLE
Having Trouble Recieving Player Data...

### ISSUE THREAD

**Issue by dent41** [Pugmatt/BedrockConnect#234]
I have the server working fine on JAVA as expected. Attempted to join on Bedrock (PC) and is able to locate the server and attempt to join, however is stuck on Recieving Player Data.
Has anyone else have this/similar issue?
Let me know if there is a similar issue.
Cheers

p.s. I do have the same MC User for both versions (Java/Bedrock) I have a feeling that could be the reason why I can't join, but I dont know for sure.

**Comment by Pugmatt** [comment]
Assuming this is about the same issue from https://github.com/Pugmatt/BedrockConnect/issues/235 , closing this as well.
