### ISSUE TITLE
Nintendo Switch - "Unable to connect to world."

### ISSUE THREAD

**Issue by MechDragon108** [Pugmatt/BedrockConnect#236]
I followed the YouTube tutorial, changing the both the Primary and Secondary DNS.
When I log into a server I still get the Server List, but when I try to log into a custom server I added to the list, it gives me the error message: "Unable to connect to world.".

I've tried 3 different public server IPs and they all result in the same error message. Please help.

**Comment by Pugmatt** [comment]
If you haven't already, please check the troubleshooting, as it mentions this issue: https://github.com/Pugmatt/BedrockConnect/wiki/Troubleshooting#im-able-to-get-on-the-bedrockconnect-serverlist-but-retrieving-a-cant-connect-to-world-when-joining-a-server

If you're looking at a serverlist with Java Edition servers, this could be why.

**Comment by kmpoppe** [comment]
@MechDragon108 Please report back if you're still having this issue, without your response I'll close it in a weeks' time. Thank you.
