### ISSUE TITLE
Obsolete Server

### ISSUE THREAD

**Issue by Furetto126** [Pugmatt/BedrockConnect#239]
I'm trying to connect from my nintendo switch to the BedrockConnect menu screen, but, when clicking a server it says that is obsolete (after 1.18 update) , even if i can connect to the same one but with the automatic DNS.
Can BedrockConnect be upgraded to the new version?

**Comment by TheMax07** [comment]
yes, please fix this, i cannot join a server... same message after i clicked the server...

**Comment by kmpoppe** [comment]
I mean, guys, there's a fix already booked (#238). This is a volunteer project after all. Please have some patience! I'm sure @Pugmatt will look into this as soon as he possibly can!

**Comment by metulburr** [comment]
Crap. I will have to play my server on my phone then until this is fixed.

**Comment by Pugmatt** [comment]
Should be updated now. Thank you for everyone's patience.
