### ISSUE TITLE
Question about dns

### ISSUE THREAD

**Issue by Meganium97** [Pugmatt/BedrockConnect#246]
Will changing the DNS to use BedrockConnect affect other games such as Forza Horizon? I'm thinking to use this with my Xbox (I already have it set up on my switch with a custom connection) but it'd be such a hassle to constantly change the AP on my Xbox. Thanks in advance.

**Comment by Pugmatt** [comment]
If setup correctly, it will only affect Minecraft, no other games will be touched.

The DNS is setup to only change the domains of the servers listed in the Minecraft featured server list, and everything else goes through whatever DNS you have set the secondary. (With the case of the tutorial, 8.8.8.8, Google' DNS)

**Comment by Meganium97** [comment]
Ah, thanks for the clarification, although it appears that many xbox users are not able to use it at the moment.
