### ISSUE TITLE
Does not work on 1.18 for Nintendo Switch.

### ISSUE THREAD

**Issue by republicationenterprises** [Pugmatt/BedrockConnect#248]
Entered correct DNS servers as shown in tutorial, yet connecting to the server still directs to the intended.

**Comment by PaulW** [comment]
Could be a few things:

- On the switch, the overriding DNS server needs to be set first, with then either 8.8.8.8 or 1.1.1.1 as the secondary
- Your ISP is forcing the use of their own DNS servers regardless of client requests (Sky UK did this, not sure if they still do) in which case you either need to use your own modem/router as it's usually done at that point.

**Comment by CrafterPika** [comment]
As PaulW said above it can be many circumstances, therefore it's quite hard to point exactly at the issue which is causing this
so just like back in #251 try hosting your own local instance, as it may be more reliable.
Here are some tutorials:
- [Windows](https://www.youtube.com/watch?v=AW5X7-qnvLk)
- [Linux](https://github.com/Pugmatt/BedrockConnect/wiki/Setting-up-on-Linux)
