### ISSUE TITLE
Not working on Nintendo Switch 1.18.2

### ISSUE THREAD

**Issue by augustt0** [Pugmatt/BedrockConnect#251]
None of the servers says "Join to open server list" nor show current players or ping, whenever I join any of these servers it just says "Unable to connect to world".

I'm using 104.238.130.180 as primary DNS and tried every secondary DNS suggested.

Console version 13.2.0
Ping to 104.238.130.180 from Windows is okay (approx. 160ms)

**Comment by CrafterPika** [comment]
Works on Switch here, you could try running your own dns server which is sometimes more reliable:
- [Linux Tutorial ](https://github.com/Pugmatt/BedrockConnect/wiki/Setting-up-on-Linux)
- [Windows Tutorial](https://www.youtube.com/watch?v=AW5X7-qnvLk)

**Comment by augustt0** [comment]
> Works on Switch here, you could try running your own dns server which is sometimes more reliable:
> 
> * [Linux Tutorial ](https://github.com/Pugmatt/BedrockConnect/wiki/Setting-up-on-Linux)
> * [Windows Tutorial](https://www.youtube.com/watch?v=AW5X7-qnvLk)

Okay I've just made my dns server, while being on the same network as the dns server which ip should I use on switch's settings? The local ip or public?

**Comment by CrafterPika** [comment]
the local ip

**Comment by augustt0** [comment]
It's kinda weird since I can't connect by using the BedrockConnect's DNS nor my own dns and even if I set it to automatic I can't connect, hope Mojang solves this in next versions, I can only connect to realms. Anyway, thank you for your help!

**Comment by augustt0** [comment]
Okay update here, I've started another dns server but this time on my windows computer instead of my linux server and this time it's working. Thank you! Closing issue.

**Comment by CrafterPika** [comment]
:+1:

**Comment by Pugmatt** [comment]
Looks like one of the BedrockConnect instances that the official DNS redirects to had some downtime today, which might explain the issues. The instance is now back up and running, so it should fix the issues you were having. That being said I'd recommend continuing to use your local instance anyway as you would have a better connection to that.
