### ISSUE TITLE
Server icon loading

### ISSUE THREAD

**Issue by kmpoppe** [Pugmatt/BedrockConnect#253]
When connected to any BedrockConnect instance from

a) my Android phone, the server icons do not load at all, no matter how much I scroll

b) my Nintendo Switch, the server icons do not load unless I use the crosshair for scrolling - if scrolling with the right analog stick they don't load.

There's no rush to checking up on this, just an "I have no idea how this happens, maybe somebody else has"!

K

**Comment by Pugmatt** [comment]
This issue should now be fixed in the latest update. Let me know if the issue still occurs.

**Comment by kmpoppe** [comment]
Will do, thanks!
