### ISSUE TITLE
Custom messages

### ISSUE THREAD

**Issue by YTiceice** [Pugmatt/BedrockConnect#256]
How to custom button messages?

**Comment by Pugmatt** [comment]
Not sure what you mean by this. Can you expand on what you mean?

**Comment by YTiceice** [comment]
There are many buttons to choose from when a player joins
For example: official server
And how to custom this button messages?

**Comment by Pugmatt** [comment]
If you're looking to put a custom button message on a server in the list, you can already do that with the "Display Name on Server List" field when adding a server. If you're hosting your own instance and want to add default servers, there is configuration to set the name/message on those server buttons: https://github.com/Pugmatt/BedrockConnect#defining-your-own-custom-servers

As for the other buttons like the featured servers and Add/Remove/Exit buttons, there is not currently a way to customize these, but you can download the source yourself and compile your own version if you want to modify these. I'm not really sure if there's a purpose in adding configuration for these outside of that.

**Comment by CrafterPika** [comment]
> As for the other buttons like the featured servers and Add/Remove/Exit buttons, there is not currently a way to customize these, but you can download the source yourself and compile your own version if you want to modify these.

The "official server" part in
> For example: official server

gives me the feeling he is referring to GeyserConnect, because well...
![IMG_4273](https://user-images.githubusercontent.com/48294025/150238358-f1ebc045-782e-4a28-b374-7280352b0722.PNG)

I have quite the same trouble to really figure out what he means...

**Comment by Pugmatt** [comment]
True. Looks like this issue was also posted in GeyserConnect's issues, not sure if this was meant to be posted there in the first place. Either way, I guess I could see the use in configuration for these buttons if someone would like to host an instance in a different language, which isn't the worst idea to add support for. Something I can look into.

**Comment by YTiceice** [comment]
Yes,I referring to GeyserConnect

**Comment by YTiceice** [comment]
Beacause on GeyserConnect GitHub:
https://github.com/GeyserMC/GeyserConnect
On "code" page give me a link to here

**Comment by YTiceice** [comment]
> 至於其他按鈕，如特色服務器和添加/刪除/退出按鈕，目前還沒有自定義這些按鈕的方法，但是如果您想為您的用例修改這些，您可以自己下載源代碼並編譯您自己的版本. 我不確定是否有為這些之外添加配置的目的。

Where would these buttons be in the source code?

**Comment by Pugmatt** [comment]
If you're looking for a solution for GeyserConnect, we can't help since this issues section and repository is for BedrockConnect, a separate project from GeyserConnect. You will need to wait for a response in the issue you posted in their repository if this is the case.

If you are looking for a solution for BedrockConnect (Again, this is not GeyserConnect), you can find the code for where the labels/messages on the buttons are defined in this file here: https://github.com/Pugmatt/BedrockConnect/blob/5d12938fbf9dce4127edb16afa7378888a9692a9/serverlist-server/src/main/com/pyratron/pugmatt/bedrockconnect/gui/UIForms.java#L23

**Comment by YTiceice** [comment]
Ok thanks

**Comment by YTiceice** [comment]
I fined it
https://github.com/GeyserMC/GeyserConnect/blob/5e46415ac97121399d2875b9fdbc2e3d93325d07/src/main/java/org/geysermc/connect/ui/UIHandler.java

**Comment by YTiceice** [comment]
How to edit?

**Comment by CrafterPika** [comment]
> I guess I could see the use in configuration for these buttons if someone would like to host an instance in a different language.

For language translations you probably wanna use i18n, ig.

**Comment by YTiceice** [comment]
I download UIHandler.java file,then edit it
Then I use winrar open the .jar file,and put in the UIHandler.java file.

May I edit it in this way

**Comment by YTiceice** [comment]
> > 如果有人想以不同的語言託管實例，我想我可以看到這些按鈕在配置中的用途。
> 
> 對於語言翻譯，您可能想要使用 i18n，例如。

How to use?

**Comment by CrafterPika** [comment]
> Then I use winrar open the .jar file,and put in the UIHandler.java file.

1. You can’t use .java in a .jar, because .java is the source file and a .class is the compile file which is then used in the jar

> How to use?

2. if you can’t figure out how to compile a project like this with [maven](https://maven.apache.org/), then you shouldn’t do it in the first place.

**Comment by YTiceice** [comment]
Ok

**Comment by YTiceice** [comment]
I download GeyserConnect code from GitHub
And I run command"javac UIHandler.java"
But it appeared many errors.

**Comment by CrafterPika** [comment]
> I download GeyserConnect code from GitHub
> And I run command"javac UIHandler.java"
> But it appeared many errors.

For once and for all you compile a project like this with maven, not javac, as it doesn’t account for all the dependencies. Take a look at the [workflow file](https://github.com/Pugmatt/BedrockConnect/blob/master/.github/workflows/ci.yml#L21) at Line 21. 

if you can’t figure out how to install maven.
pretty much every package manager has it, including:
- [scoop](https://scoop.sh) if you are on windows (via `scoop install maven`)
- [homebrew](https://brew.sh) if you are on a mac (via `brew install maven`)
- and pretty every package manager on linux (like `apt`, `yum`, `pacman`)

**Comment by YTiceice** [comment]
> > 我從 GitHub 下載 GeyserConnect 代碼
> > 並運行命令“javac UIHandler.java”
> > 但它出現了很多錯誤。
> 
> 一勞永逸地用[maven](https://maven.apache.org/)編譯這樣的項目，而不是 javac，因為它沒有考慮所有的依賴關係。查看第 21 行的[工作流文件](https://github.com/Pugmatt/BedrockConnect/blob/master/.github/workflows/ci.yml#L21)。
> 
> 如果你不知道如何安裝 Maven。 幾乎每個包管理器都有它，包括：
> 
> * [](https://scoop.sh)如果您在 Windows 上，請[舀](https://scoop.sh)`scoop install maven`（通過）
> * [](https://brew.sh)如果您在 Mac 上使用[自製軟件](https://brew.sh)`brew install maven`（通過）
> * 幾乎所有 Linux 上的包管理器（如`apt`, `yum`, `pacman`）
> 
> 編譯 GeyserConnect 101：
> 
> 1. `git clone https://github.com/GeyserMC/GeyserConnect.git`（假設你已經安裝了[git](https://git-scm.com/)）
> 2. `cd GeyserConnect`
> 3. 編輯`./src/main/java/org/geysermc/connect/ui/UIHandler.java`您想要的方式
> 4. `mvn -B package --file pom.xml`
> 5. 利潤？
> 
> 旁注 BedrockConnect v1.14 啟用更改按鈕請參閱[自述](https://github.com/Pugmatt/BedrockConnect#change-wording-of-serverlist)文件。

But error appeared
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project geyser-connect: Fatal error compiling: error: invalid target release: 16 -> [Help 1]

**Comment by CrafterPika** [comment]
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project geyser-connect: Fatal error compiling: error: invalid target release: 16 -> [Help 1]

Ensure you are at least running Java 16 or newer https://github.com/GeyserMC/GeyserConnect/blob/master/pom.xml#L19-L20

**Comment by YTiceice** [comment]
It work, thanks you
