### ISSUE TITLE
Missing player data

### ISSUE THREAD

**Issue by plsHelpMa** [Pugmatt/BedrockConnect#258]
### What happened?

I try to go into and server and it won’t load then tells me that’s it can’t  find my player data

### Excepted Behaviour?

It loaded

### Steps to reproduce.

Open Minecraft click on any server not load try again get error message 

### Minecraft Bedrock Version

1.18

### Console

Xbox

### Additional Context

It worked before third time using special servers on bedrock

**Comment by FrostyLosty1** [comment]
Same thing is happening to me. I left to eat lunch around 8:00 EST, and when I came back at 9:00 EST, it was doing the same thing. Lets just hope its a server interruption, and not something else. I Originally thought they changed the DNS number that you have to put in to join other servers. Hope thats not the case!

**Comment by Pugmatt** [comment]
Host experienced some outages today, should be good now. Let me know if it continues to happen.
