### ISSUE TITLE
Stopped working on xbox and switch

### ISSUE THREAD

**Issue by Jobinrandhawa** [Pugmatt/BedrockConnect#259]
### What happened?

Was working earlier today. went to reconnect after break and says cannot connect to server.

### Excepted Behaviour?

to connect and show options for external servers

### Console

Nintendo switch and Xbox

**Comment by Jayem1225** [comment]
I think it was just a short service interruption. I had the same issue on Switch but its working again for me.

**Comment by Jobinrandhawa** [comment]
> I think it was just a short service interruption. I had the same issue on Switch but its working again for me.

tried again on both xbox and switch and its still not working, tried restarting both devices and double checked DNS settings

**Comment by FrostyLosty1** [comment]
Same thing is happening to me. I left to eat lunch around 8:00 EST, and when I came back at 9:00 EST, it was doing the same thing. Lets just hope its a server interruption, and not something else. I Originally thought they changed the DNS number that you have to put in to join other servers. Hope thats not the case!

**Comment by Jobinrandhawa** [comment]
> Same thing is happening to me. I left to eat lunch around 8:00 EST, and when I came back at 9:00 EST, it was doing the same thing. Lets just hope its a server interruption, and not something else. I Originally thought they changed the DNS number that you have to put in to join other servers. Hope thats not the case!

mine actually just starting working again.

**Comment by Pugmatt** [comment]
Host experienced some outages today, should be good now. Let me know if it continues to happen.
