### ISSUE TITLE
trouble receiving player data

### ISSUE THREAD

**Issue by Cunk41** [Pugmatt/BedrockConnect#260]
### What happened?

unable to open external server list, either get a "unable to connect to world" error or a "we had some trouble receiving your player data message."

### Excepted Behaviour?

The external server list to load

### Steps to reproduce.

press the "join server" button to open the external server list

### Minecraft Bedrock Version

1.18.2

### Console

Nintendo Switch

**Comment by CrimsnDawn** [comment]
![F0FD4081-06F4-4551-B2C6-60C144618105](https://user-images.githubusercontent.com/98295222/150712799-1a6bcb43-d8d6-4364-8930-a2dafcbaefb4.jpeg)

Experiencing the same issue on Nintendo Switch, on two separate consoles and accounts, unable to receive player data. Wondering how to resolve the issue.

**Comment by FrostyLosty1** [comment]
Same thing is happening to me. I left to eat lunch around 8:00 EST, and when I came back at 9:00 EST, it was doing the same thing. Lets just hope its a server interruption, and not something else. I Originally thought they changed the DNS number that you have to put in to join other servers. Hope thats not the case!

**Comment by Pugmatt** [comment]
Host experienced some outages today, should be good now. Please reply in the following issue if the issue is still happening (Trying to keep it in one issue): https://github.com/Pugmatt/BedrockConnect/issues/258
