### ISSUE TITLE
Trouble reciving player data

### ISSUE THREAD

**Issue by Alextroll7XD** [Pugmatt/BedrockConnect#261]
### What happened?

It says that it has problems of reving my player 

### Excepted Behaviour?

i tried restarting my console the game and my account but it didnt work

### Steps to reproduce.

1. open minecraft
2. try ton enter a server (in my case Hive)

### Minecraft Bedrock Version

1.18.2

### Console

Xbox

### Additional Context

IDK why it lets me play other servers

**Comment by FrostyLosty1** [comment]
Same thing is happening to me. I left to eat lunch around 8:00 EST, and when I came back at 9:00 EST, it was doing the same thing. Lets just hope its a server interruption, and not something else. I Originally thought they changed the DNS number that you have to put in to join other servers. Hope thats not the case!

**Comment by Pugmatt** [comment]
Host experienced some outages today, should be good now. Please reply in the following issue if the issue is still happening (Trying to keep it in one issue): https://github.com/Pugmatt/BedrockConnect/issues/258
