### ISSUE TITLE
Trouble receiving your player data 

### ISSUE THREAD

**Issue by xtheoldgodsx** [Pugmatt/BedrockConnect#262]
### What happened?

Won't load server list. I get either an error saying cannot connect to world or the aforementioned screen saying that my player data isn't being received. 

### Excepted Behaviour?

For the server list to open. 

### Steps to reproduce.

Click on servers tab
Click on a server to open server list
One of two error messages appears

### Minecraft Bedrock Version

1.18

### Console

Nintendo Switch

**Comment by FrostyLosty1** [comment]
Same thing is happening to me. I left to eat lunch around 8:00 EST, and when I came back at 9:00 EST, it was doing the same thing. Lets just hope its a server interruption, and not something else. I Originally thought they changed the DNS number that you have to put in to join other servers. Hope thats not the case!

**Comment by Pugmatt** [comment]
Host experienced some outages today, should be good now. Please reply in the following issue if the issue is still happening (Trying to keep it in one issue): https://github.com/Pugmatt/BedrockConnect/issues/258
