### ISSUE TITLE
Unable to receive player data

### ISSUE THREAD

**Issue by FrostyLosty1** [Pugmatt/BedrockConnect#263]
### What happened?

For the past hour of writing this, whenever I try to join a server, it either says "Unable to connect to world" or "We had some trouble receiving your player data. Please report this to BedrockConnect GitHub if the issue continues.". 

### Excepted Behaviour?

When you click on the server tab you are supposed to be able to click on a server to join it, and it either lets you join the server, or it pulls up a list for java servers to add.

### Steps to reproduce.

1. Go to Server Tab
2. Click on Server
3. Joins server / opens server list for Java servers

### Minecraft Bedrock Version

1.18.2

### Console

Nintendo Switch

### Additional Context

Some other background info is that I have my DNS settings on my Switch set to a certain number so I can join Java servers, I dont know if that is part of it or not. I really hope this gets fixed because I'm trying to play on a server with other people, but I can't join.

**Comment by Pugmatt** [comment]
Host experienced some outages today, should be good now. Please reply in the following issue if the issue is still happening (Trying to keep it in one issue): https://github.com/Pugmatt/BedrockConnect/issues/258

**Comment by FrostyLosty1** [comment]
It works now!
