### ISSUE TITLE
Constant loading

### ISSUE THREAD

**Issue by Kylianlol13** [Pugmatt/BedrockConnect#267]
### What happened?

On switch it stays stuck at locating server when trying to join a server

### Excepted Behaviour?

That it doesn't het stuck

### Screenshots/Videos

![16439866876607620821516252570375](https://user-images.githubusercontent.com/99032256/152550886-dcf502c2-4087-4a52-8739-fba507005387.jpg)

### Minecraft Bedrock Version

1.18.2

### Console

Nintendo switch

**Comment by Pugmatt** [comment]
Is this happening with all servers? Or just Nether Games? Either way, issues that occur once you begin joining a server from the list are issues in terms of the server you're trying to join, or a different issue unrelated. Can also try restarting the game/system if this is happening for all servers.
