### ISSUE TITLE
[Feature Request] Server Groups

### ISSUE THREAD

**Issue by Kee7702** [Pugmatt/BedrockConnect#268]
**Is your feature request related to a problem? Please describe.**
I honestly think that BedrockConnect could use some organization for externally hosted instances. Although this feature wouldn't be enabled by default it'd be a cool feature to eventually see added to BedrockConnect.

**Describe the solution you'd like**
A simple way to add this to the servers json file would be most practical, an example of a possible format is shown below.
```
[
  {
    "name": "Template Group 1",
    "iconUrl": "https://i.imgur.com/3BmFZRE.png",
    "contents": [
      {
        "name": "Template Server In Group",
        "iconUrl": "https://i.imgur.com/3BmFZRE.png",
        "address": "104.238.130.180",
        "port": 19132
      }
    ]
  },
  {
    "name": "Template Server 1",
    "iconUrl": "https://i.imgur.com/3BmFZRE.png",
    "address": "104.238.130.180",
    "port": 19132
  },
  {
    "name": "Template Server 2",
    "iconUrl": "https://i.imgur.com/3BmFZRE.png",
    "address": "104.238.130.180",
    "port": 19132
  }
]
```
The format would then give an output like what is shown below:
![image](https://user-images.githubusercontent.com/48420101/152564667-bb12e0e5-babd-4c58-aea2-e07173b00bc2.png)
![image](https://user-images.githubusercontent.com/48420101/152565188-c452bf3f-d546-47af-9f36-4fe526ed6b4b.png)

**Comment by Pugmatt** [comment]
Neat idea, I think it would be a nice addition, and shouldn't be too hard to implement for this case. I'll look into it.

**Comment by Pugmatt** [comment]
Custom server groups can now be created in the latest version https://github.com/Pugmatt/BedrockConnect/releases/tag/1.17
