### ISSUE TITLE
It does not work with Xbox cause of ipv6

### ISSUE THREAD

**Issue by Masonisbetter** [Pugmatt/BedrockConnect#273]
### What happened?

It does not work with Xbox cause of ipv6

### Excepted Behaviour?

It does not work with Xbox cause of ipv6

### Minecraft Bedrock Version

1.18.10

### Console

Xbox

**Comment by CrafterPika** [comment]
known issue #25

**Comment by Pugmatt** [comment]
Known issue, and troubleshooting mentions the current only known solutions: https://github.com/Pugmatt/BedrockConnect/wiki/Troubleshooting#joining-the-featured-servers-still-directs-to-the-actual-servers-and-not-the-serverlist
