### ISSUE TITLE
Joining server goes back to server list on some 1.18 servers 

### ISSUE THREAD

**Issue by xtheoldgodsx** [Pugmatt/BedrockConnect#275]
### What happened?

Some 1.18 servers won't connect. Attempting to do so just boots me back to the server list. I can connect to a handful of 1.18 servers but others won't. 

### Excepted Behaviour?

Joining server 

### Steps to reproduce.

Open server tab 
Click open server list
Click on server name to join 

### Minecraft Bedrock Version

1.18. 2

### Console

Nintendo Switch 

### Additional Context

As I said, not all servers are doing this. It seems to be an issue on only one of the servers i play on.

**Comment by kmpoppe** [comment]
This Issue is already addressed in #272, please close this one, thanks!

**Comment by Pugmatt** [comment]
According to the version they specified, 1.18.2, this might actually be a different issue since that would mean they're still on the version before 1.18.10 and haven't updated yet.

@xtheoldgodsx Out of curiosity do you know what version the server that you can't currently join is running on?

**Comment by kmpoppe** [comment]
No response from OP, I guess the issue has outlived itself @Pugmatt ?

**Comment by Pugmatt** [comment]
I believe so
