### ISSUE TITLE
Outdated version

### ISSUE THREAD

**Issue by sitapea1337** [Pugmatt/BedrockConnect#276]
### What happened?

Hello!

When trying to connect to BedrockConnect server user gets error Outdated client.
Yes, downloaded latest version, still outdated.

### Excepted Behaviour?

Should not be outdated.

### Minecraft Bedrock Version

1.18.10

### Console

Windows 10 Bedrock 1.18.10

**Comment by CrafterPika** [comment]
Are you really sure it’s the latest? Ensure its [1.15](https://github.com/Pugmatt/BedrockConnect/releases/tag/1.15) or newer. If you 100% sure try the [GH CI builds](https://nightly.link/Pugmatt/BedrockConnect/workflows/ci/master/build-artifact) which are literally being build of the master branch.

**Comment by sitapea1337** [comment]
You are absolutely right, I downloaded version from incognito window and now doesn't display error. Maybe need to delete browser cache or something.
