### ISSUE TITLE
Beta / New Version Support

### ISSUE THREAD

**Issue by DovydasTEDS** [Pugmatt/BedrockConnect#279]
**Is your feature request related to a problem? Please describe.**
When testing betas/playing on newer versions of minecraft, I cannot connect.

**Describe the solution you'd like**
Support for beta/auto updates.

**Comment by Camotoy** [comment]
This is unlikely to happen - it's tough to update the Bedrock protocol, unlike Java Edition. It's not bothered until we anticipate a release.

**Comment by Pugmatt** [comment]
Basically what Camotoy said. The protocol has to be updated manually, it's not something that can be done automatically.
