### ISSUE TITLE
Servers won’t work when sever IP is put in

### ISSUE THREAD

**Issue by rocketfist** [Pugmatt/BedrockConnect#28]
I’ve put in three sever IPs and they all say “unable to connect to world”

**Comment by rocketfist** [comment]
Also I’m on switch

**Comment by Pugmatt** [comment]
Make sure you're joining Bedrock Edition servers, and not Java Edition. Servers such as these should work: https://minecraftpocket-servers.com/

**Comment by rocketfist** [comment]
Ok thanks
