### ISSUE TITLE
Not letting me join servers

### ISSUE THREAD

**Issue by FrostyLosty1** [Pugmatt/BedrockConnect#284]
### What happened?

When I try to join a server on bedrock, it fails and gives me this message: "An internal error happened while handling Floodgate data, Try logging in again or contact a server administrator if the issue persists." I've tried logging out and back in, and restarting my console (Switch) many times. I know it's gotta be something with bedrock because my friends are able to join the same server on Java (its a cross platform server).

### Excepted Behaviour?

It's suppose to join the server.

### Steps to reproduce.

Open server tab
Join server
Choose server in server list

### Minecraft Bedrock Version

Whatever the latest version is, I think it's 1.18.2

### Console

Nintendo Switch

### Additional Context

It's a cross platform server, if that helps. But it does the same thing with the default servers aswell.

**Comment by Pugmatt** [comment]
"Floodgate" is a Geyser project, and this error sounds like it's happening from the server you're trying to join's end, in which case it's out of BedrockConnect's connection. So we can't really help as it's unrelated to BedrockConnect. Recommend posting in https://github.com/GeyserMC/Floodgate or contacting the server you're trying to join.
