### ISSUE TITLE
104.238.130.180 unresponsive?

### ISSUE THREAD

**Issue by jkrauska** [Pugmatt/BedrockConnect#288]
### What happened?

Could not get dns responses from first DNS server.

### Excepted Behaviour?

Get DNS responses.

### Steps to reproduce.

❯ dig @104.238.130.180 www.google.com

; <<>> DiG 9.10.6 <<>> @104.238.130.180 www.google.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: REFUSED, id: 17137
;; flags: qr rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;www.google.com.			IN	A

;; Query time: 130 msec
;; SERVER: 104.238.130.180#53(104.238.130.180)
;; WHEN: Tue Apr 12 10:10:08 PDT 2022
;; MSG SIZE  rcvd: 43

❯ dig @173.82.100.84 www.google.com

; <<>> DiG 9.10.6 <<>> @173.82.100.84 www.google.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 17975
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;www.google.com.			IN	A

;; ANSWER SECTION:
www.google.com.		157	IN	A	172.217.14.100

;; Query time: 169 msec
;; SERVER: 173.82.100.84#53(173.82.100.84)
;; WHEN: Tue Apr 12 10:10:24 PDT 2022
;; MSG SIZE  rcvd: 59

**Comment by Pugmatt** [comment]
The first DNS (104.238.130.180) only has records for the Minecraft featured servers' domains, it will not respond to any domains outside of that. That is why when setting up the DNS on a device you need to put another DNS in the secondary DNS such as 8.8.8.8 in order for it to fully work.

If you re-run the command with the domain of a featured server, you should retrieve a response. (Can find a list here: https://github.com/Pugmatt/BedrockConnect#using-your-own-dns-server) I tested just now and it appears to be responding correctly and up and running.

**Comment by RemovingRobin15** [comment]
Hay un error con la dns o almenos con nintendo switch todo iva normal ayer pero hoy al intentar entrar a servidores externos me aparecia que el servidor estaba lleno y desde la tarde no me deja entrar a ellos porfavor arreglenlo

**Comment by Pugmatt** [comment]
> Hay un error con la dns o almenos con nintendo switch todo iva normal ayer pero hoy al intentar entrar a servidores externos me aparecia que el servidor estaba lleno y desde la tarde no me deja entrar a ellos porfavor arreglenlo

Super heavy traffic tonight on main instance. Gave the servers a restart, should be good for now. If you continue to have issues today try one of the other DNS's https://github.com/Pugmatt/BedrockConnect#publicly-available-bedrockconnect-instances
