### ISSUE TITLE
Did they patch this??

### ISSUE THREAD

**Issue by tubmaster3** [Pugmatt/BedrockConnect#292]
saw I was connected to ipv6. minecraft bedrock is actually pointless

**Comment by tubmaster3** [comment]
It was working 2 days ago now nothing since this recent update as well so maybe thats it? idk hope my info helps

**Comment by Pugmatt** [comment]
It is still working for others, it has not been patched.

Make sure you've gone through the Troubleshooting page if you haven't already.

https://github.com/Pugmatt/BedrockConnect/wiki/Troubleshooting

If you need further assistance, please give more information for us to help you. Does it just go to the regular servers and not the BedrockConnect server?
