### ISSUE TITLE
Self-hosted BedrockConnect not working.

### ISSUE THREAD

**Issue by Corbinator333** [Pugmatt/BedrockConnect#294]
### What happened?

When I choose a server from the list that allows me to access the server list, I get this error: "We had some trouble receiving your player data. Please report this to the BedrockConnect GitHub if the issue continues."

### Excepted Behaviour?

I should just be able to connect just fine and be able to connect to my minecraft bedrock esrver.

### Screenshots/Videos

![2022051212010800_s](https://user-images.githubusercontent.com/63374705/168149958-61782919-974d-4d0a-a2db-866250e6bd9c.jpg)

### Minecraft Bedrock Version

1.18.2

### Console

Nintendo Switch

**Comment by Pugmatt** [comment]
This error can arise if there's an issue with creating the player files, or communicating with the database if database mode is on. If you don't have a database setup and are using files for player data, make sure you have ```nodb=true``` added to your startup command, such as the following:

```
java -jar BedrockConnect-1.0-SNAPSHOT.jar nodb=true
```

If you still have issues, please reply with the full command you're using to launch the BedrockConnect instance.

**Comment by Corbinator333** [comment]
Thank you, this worked!
