### ISSUE TITLE
Kick on Death

### ISSUE THREAD

**Issue by Corbinator333** [Pugmatt/BedrockConnect#295]
### What happened?

When my friend dies in game, his minecraft crashes.

### Excepted Behaviour?

He should just die and go back to his spawn point.

### Steps to reproduce.

**Players online:** My friend (xbox one s using pugmatt dns), Me (java 1.18.2), and my other friend (java 1.18.2)
**Plugins that may be involved with this issue:** GeyserMC
**How error occured:** He would die from anything (fall damage, death by mob, etc.) and his whole minecraft game would crash.

### Minecraft Bedrock Version

Latest

### Console

Xbox One S

### Additional Context

I don't know if this is an issue with Geyser or BedrockConnect but I need to know.

**Comment by Pugmatt** [comment]
Once you connect to a server from the BedrockConnect serverlist, the connection is completely off of BedrockConnect. So, issues at that point would be occurring on the game server and unrelated to BedrockConnect.
