### ISSUE TITLE
Patched???

### ISSUE THREAD

**Issue by GGCoder098** [Pugmatt/BedrockConnect#299]
### What happened?

It wouldnt come up with the menu whe i jined a server

### Excepted Behaviour?

the menu would pop up

### Minecraft Bedrock Version

1.18.3

### Console

xbox

**Comment by TheWilbo** [comment]
This sometimes happens to me. I just retry and it usually works the next time.

**Comment by WoodlandJay** [comment]
> This sometimes happens to me. I just retry and it usually works the next time.

Have you tried recently? I've been trying for weeks and there is no server connect menu that pops up.

**Comment by Pugmatt** [comment]
This has not been patched, it is still working for others. The DNS either needs to be re-configured in your console's internet settings, or there was a change to your network/router. All known solutions for fixing this issue can be found on the troubleshooting page: https://github.com/Pugmatt/BedrockConnect/wiki/Troubleshooting#joining-the-featured-servers-still-directs-to-the-actual-servers-and-not-the-serverlist
