### ISSUE TITLE
Server list down.

### ISSUE THREAD

**Issue by Wazk26** [Pugmatt/BedrockConnect#30]
The server list doesn't show up when I join servers. When I join a server it says unable to connect to world and thats it. I noticed on http://nginx.org/ there was a new release today and I was wondering if that was involved. Me and my friends are trying to play on my server and haste in a response would be appreciated

**Comment by Pugmatt** [comment]
Everything appears to still be up and running. Make sure you're on 1.14.6. If restarting the game and game console doesn't do anything, you can also try using the local solution: https://www.youtube.com/watch?v=AW5X7-qnvLk

**Comment by Wazk26** [comment]
Is there a way to setup my own public DNS server like the one you provide?

**Comment by Pugmatt** [comment]
You would follow the same instructions like in the video I posted, but if you want to host a BedrockConnect that's not just local, and one that you want friends to be able to connect to outside your WiFi network, you'll need to go into your router settings and port forward ports 53 and 19132. When starting up the BedrockConnect software, you would also enter your PUBLIC IPv4, which can be found here: https://www.whatismyip.com/. The game console's Primary DNS address would be set to this as well.

There might be some issues with this currently hosting it publicly with that method, so I can't guarantee anything.
