### ISSUE TITLE
Manage Server List -> Remove a Server does not work

### ISSUE THREAD

**Issue by loudddddddd** [Pugmatt/BedrockConnect#313]
### What happened?

When logging into the server list, going to Manage Server List and pressing Remove a Server does not do anything and redirects back to the menu where you pick a server to join

### Excepted Behaviour?

When pressing Remove a Server I expect it to open up a menu where I can select a server to remove

### Steps to reproduce.

1. Join the server-list
2. Click “Manage Server List”
3. Click “Remove a Server”

### Screenshots/Videos

I cannot as I’m on switch and I do not know how to share that.

### Minecraft Bedrock Version

1.19.20

### Console

Nintendo Switch

**Comment by loudddddddd** [comment]
I also noticed that anything (not just Remove a Server) in the Manage Server List menu redirects back to the server list.

**Comment by Pugmatt** [comment]
Thank you for reporting this, currently looking into it.

**Comment by loudddddddd** [comment]
I think it mightve been an issue on my part considering it works now after I restarted my game.

**Comment by Pugmatt** [comment]
Hmm, I'm able to replicate it, but seems to happen randomly. Will continue to look into it.

**Comment by loudddddddd** [comment]
That probably makes sense as this is the only time it has happened to me. Thanks

**Comment by Pugmatt** [comment]
I believe the latest commit/update fixed this, but if anyone is still experiencing this issue please comment here.
