### ISSUE TITLE
1.19.20 Server Outdated

### ISSUE THREAD

**Issue by RoGuE001** [Pugmatt/BedrockConnect#315]
### What happened?

Since updating the game on switch earlier today ive gotten outdated server soon as I try joining the featured server to get to my server list. I understand theres already been other issues with this, but Ive only seen people mention unable to connect and not outdated server so I wanted to bring this up. 

### Excepted Behaviour?

.....Do I need to really say anything here. I think we all know lol. 

### Steps to reproduce.

Just try joining a featured server as I did (see video below) and you should get the same error.

### Screenshots/Videos

https://user-images.githubusercontent.com/44219454/183785282-9662655a-06ed-4565-a3f8-582dd02758d6.mp4

### Minecraft Bedrock Version

1.19.20

### Console

Nintendo switch

### Additional Context

N/A

**Comment by Pugmatt** [comment]
Server was updated about 45 minutes ago. If you haven't tested in a couple of hours, try again.

If you're using a BedrockConnect DNS other than the main one, 104.238.130.180, it's probably currently outdated. The main one is currently the only one updated.

**Comment by RoGuE001** [comment]
I'll try the other one and let you know.

**Comment by loudddddddd** [comment]
I believe BedrockConnect has been updated (Pugmatt’s server works fine for me). I believe you have to wait for the server your using to update

**Comment by RoGuE001** [comment]
> Server was updated about 45 minutes ago. If you haven't tested in a couple of hours, try again.
> 
> If you're using a BedrockConnect DNS other than the main one, 104.238.130.180, it's probably currently outdated. The main one is currently the only one updated. Once the JAR is released, the other ones in the "Publicly available BedrockConnect instances" should be updated shortly.

yup, using that one works. Thanks

**Comment by kmpoppe** [comment]
I have updated the instances in Germany and the UK now as well.

**Comment by kmpoppe** [comment]
This issue is solved as per the discussion
