### ISSUE TITLE
Not working at all

### ISSUE THREAD

**Issue by Who-Cares69** [Pugmatt/BedrockConnect#317]
### What happened?

I tried to use bedrock connect to go on a server today and nothing showed up on my server list all the servers were normal so I tried every method I could think if to resolve this and nothing worked I even tried on all of the instances listed and it was the same and none of the servers had the join to access server list description

### Excepted Behaviour?

Load minecraft on instance go to server tab see a server that says join to access server list then join 

### Steps to reproduce.

1- use a bedrock connect DNS instance 
2-liad Minecraft
3-go servers tab
4 get disappointed as it didn't work

### Minecraft Bedrock Version

1.19.20

### Console

Xbox 1S

### Additional Context

I don't know why this is happening I have tried everything and would very much like to play on servers so I hope this is fixed soon

**Comment by Pugmatt** [comment]
All known ways to fix this can be found on the troubleshooting under "Joining the Featured Servers still directs to the actual servers and not the serverlist...", including alternative solutions at the bottom of that section: https://github.com/Pugmatt/BedrockConnect/wiki/Troubleshooting#joining-the-featured-servers-still-directs-to-the-actual-servers-and-not-the-serverlist

Unfortunately sometimes depending on your network and console, the game console will still try to read from the default network or console DNS, which is unfortunetly out of our control. Only thing we can recommend is follow the steps in the link above, or you can try setting up a local instance and join through LAN by doing the following:

- On PC, Mac, or Linux, download this JAR: https://github.com/Pugmatt/BedrockConnect/releases
- Make sure Java 8 or higher is installed.
- In command prompt or terminal, run the following command:
  ```java -jar BedrockConnect-1.0-SNAPSHOT.jar nodb=true```
- When in Minecraft on Xbox, go to the "Friends" tab, and the server-list server should be showing under LAN servers and available to join.
