### ISSUE TITLE
Command Line Option for Listen IP

### ISSUE THREAD

**Issue by MarcProe** [Pugmatt/BedrockConnect#32]
Would it be possible to create an option to give the listen ip in the batch file?

This would make it possible to start the server without user intraction.

**Comment by Pugmatt** [comment]
Yes, I could do this. Only reason why I didn't add this at first is because the local IP can occasionally change, but I'll add the option for people who know what they're doing.

**Comment by MarcProe** [comment]
My use case is that I want to run it in docker on a rasbpi... This was the first issue I ran into.

**Comment by MarcProe** [comment]
I just realized that there is no ip input if you omit ```generatedns```. I don't need that, so I have it now running on my Raspberry Pi in Docker.

Here's the ```Dockerfile```, for anyone interessted.
```
FROM hypriot/rpi-java
RUN mkdir /brc
COPY BedrockConnect-1.0-SNAPSHOT.jar /brc
WORKDIR /brc
EXPOSE 19132/udp
CMD ["java", "-Xms1G", "-Xmx1G", "-jar", "BedrockConnect-1.0-SNAPSHOT.jar", "nodb=true"]
```

Docker command line: 
```
docker run --name "bedrock-c" -d --restart always -p 19132:19132/udp bedrock-connect
```

**Comment by Pugmatt** [comment]
Ah okay, I didn't realize you were trying to do a solution outside of the video tutorial. The generatedns is done specifically for the DNS software used in the video tutorial I have for setting BedrockConnect locally, so in cases like yours where you already have a DNS software, it would not be required. Glad to see you got it working!

**Comment by cjr222** [comment]
@MarcProe I was working on the same container setup today today. If you set it to nodb, it's supposed to save the serverlist to a file.  Have you figured out a way to make that persistent in the container with a volume?

**Comment by MarcProe** [comment]
@cjr222 yes.

Change the ```mkdir``` command in the Dockerfile above to
```RUN mkdir -p /brc/players```

and mount that directory as volume:

```-v /opt/bedrockconnect/:/brc/players```

This will store the "nodb" file in ```/opt/bedrockconnect``` (create it first)

**Comment by MarcProe** [comment]
> Ah okay, I didn't realize you were trying to do a solution outside of the video tutorial. 

Yes, sorry for the confusion. 
This issue is a little bit derailed now, feel free to just close it unless you intend to implement the static ip swich nevertheless.

 _Thanks for your great work! Now my son, his friend and the dads can play on one server using a Switch, a PS4 and two Laptops._
