### ISSUE TITLE
Says "Coming soon"

### ISSUE THREAD

**Issue by PizzaGod999873** [Pugmatt/BedrockConnect#320]
### What happened?

So when you load up minecraft, then go tho the servers tab, it says "coming soon" I use nintendo switch also. can this be fixed please?

### Expected Behaviour?

I expected for it to show the servers then when i enter one it would bring me to a external server thing.

### Screenshots/Videos

![2022081510162700-11B64E28AD7A49CA9EC8AC007BE858C6](https://user-images.githubusercontent.com/111541762/185508417-16f2c997-5f3f-4437-88f9-4a61f7638102.jpg)

### Minecraft Bedrock Version

1.19.20

### Console

Nintendo switch

**Comment by Pugmatt** [comment]
This is an issue with the Minecraft game itself, not BedrockConnect. Try signing out of your Microsoft account ingame, and signing back in. You can also try reloading the "Servers" tab by hitting B until your back to the main screen, then go back to servers.

**Comment by PizzaGod999873** [comment]
thanks!
