### ISSUE TITLE
run.bat file missing from bedrock connect folder  

### ISSUE THREAD

**Issue by lexitheknifegirl** [Pugmatt/BedrockConnect#324]
### What happened?

I downloaded bedrock connect for 1.19.21 and the run.bat file is not in there. I don't know if it's like hidden but I did the same thing I always do extract the zip and open the folder

### Expected Behaviour?

n/a

### Screenshots/Videos

![image](https://user-images.githubusercontent.com/112129484/186777726-de8ea192-a781-41e8-a19e-95407e97c820.png)

### Minecraft Bedrock Version

1.19.21

### Console

xbox one

**Comment by Pugmatt** [comment]
Oops, you are correct it is indeed not there, thank you for pointing that out. I have now updated the release, so if you re-download it should be there now.
