### ISSUE TITLE
Ability to remove featured servers

### ISSUE THREAD

**Issue by SirFluffDev** [Pugmatt/BedrockConnect#351]
I'd like to be able to remove the featured servers from the list.
If there's already a way to do this, please let me know.

**Comment by Pugmatt** [comment]
If you're hosting your own instance, this can be done by adding ```featured_servers=false``` to the startup command. Example:

```java -jar BedrockConnect-1.0-SNAPSHOT.jar nodb=true featured_servers=false```

If you mean through the main instance through the UI, there is not a way to do this, you would need to host your own instance to remove the featured servers.

**Comment by SirFluffDev** [comment]
That's exactly what I was looking for!
I just noticed that this was in the already readme. Sorry for the pointless issue.
Have a good day!
