### ISSUE TITLE
Host Bedrock-Connect DNS server on my public IP?

### ISSUE THREAD

**Issue by SolidSouless** [Pugmatt/BedrockConnect#359]
I prefer to have full control over my setup. I was wondering if there is a way to host the bedrock connect dns over my public ip instead of exclusively local, so that my friends can join my server by using my public ip as their dns instead of the public one everyone else uses.

**Comment by xTITUSMAXIMUSX** [comment]
Wouldn't you just need to port forward your internal DNS server from your firewall?

**Comment by kmpoppe** [comment]
This is not a BedrockConnect related issue.
Please check this [handy guide on how port forward works](https://stevessmarthomeguide.com/understanding-port-forwarding/) and apply this to your setup at home.
