### ISSUE TITLE
install-bind.sh fails on Raspberry Pi OS

### ISSUE THREAD

**Issue by PedroClemo** [Pugmatt/BedrockConnect#362]
### What happened?

When running **install-bind.sh** on a Raspberry Pi (in my case Raspberry Pi Zero) that's running Raspberry Pi OS (formally Raspbian) it fails with the following output:

> Unsupported OS

This is easily fixed with the following command (assuming you downloaded the script to the current user's home directory):

`sed -i 's/"$ID" == "debian"/"$ID" == "debian" || "$ID_LIKE" == "debian"/g' ~/install-bind.sh`

or with a manual edit of the file (line 93) where you change:

`elif [[ "$ID" == "debian" ]]; then`

to

`elif [[ "$ID" == "debian" || "$ID_LIKE" == "debian" ]]; then`

and the script then runs flawlessly.

### Expected Behaviour?

The script complete all steps and install/configure BIND9 in the necessary manner.

**Comment by Pugmatt** [comment]
Thank you for reporting this, it has now been updated in the repository.
