### ISSUE TITLE
When to use 104.238.130.180 and when to use a Local IP address

### ISSUE THREAD

**Issue by Dark1886** [Pugmatt/BedrockConnect#37]
I have read the documentation and read through some of the issues, but am confused about where to be using the 104.238.130.180 for DNS server and when to be using a local IP address.

My goal is to be hosting a bedrock server at my location and have my brother connect with his Xbox one from his house. Does this mean he needs to have the bedrock connect service running at his house? What IP address would he need to use for the DNS, local or 104.238.130.180? 

P.S. this is an awesome program because servers are what really made minecraft, hope I can get this working.

**Comment by Pugmatt** [comment]
If you're hosting BedrockConnect locally, you should be using your local IP address. 104.238.130.180 is used if you want to use the public DNS server I have running.

Your brother doesn't need to have a BedrockConnect instance running on his network, he should be able to use the 104.238.130.180 DNS server. If that DNS doesn't work for him, he would then need to setup a bedrockconnect instance locally.
