### ISSUE TITLE
Stuck in bubble world on Switch

### ISSUE THREAD

**Issue by BlackberryCabbit** [Pugmatt/BedrockConnect#377]
### What happened?

I log in to Microsoft using the link and it doesn't clear, server says I joined but I never actually load in

### Expected Behaviour?

Loading in instantly, not getting stuck on the aka.ms screen

### Steps to reproduce.

Use any DNS, log into a server, try to log into microsoft, it'll fail

### Screenshots/Videos

[https://drive.google.com/file/d/1OMgYkiW9AonHjqWeeGq7UuO_HW9HJz1T/view?usp=share_link](url)

I was waiting a minute for this

### Minecraft Bedrock Version

1.19.63

### Console

Nintendo Switch

**Comment by BlackberryCabbit** [comment]
This does the same thing on IOS bedrock edition too.

**Comment by Pugmatt** [comment]
Can't say I've ever seen the login dialogue box before as displayed in the video, that isn't currently something that's in BedrockConnect. Is that showing upon connecting to BedrockConnect (Connecting to a Featured Server to open BedrockConnect), or is that showing when you join a game server from BedrockConnect?

**Comment by BlackberryCabbit** [comment]
> Can't say I've ever seen that login dialogue box before as displayed in the video, that isn't currently something that's in BedrockConnect. Is that showing upon connecting to BedrockConnect (Connecting to a Featured Server to open BedrockConnect), or is that showing when you join a game server from BedrockConnect?

A game server, atleast any java server. Not sure if this is something on your all's end or Geyser's.

**Comment by BlackberryCabbit** [comment]
BedrockConnect and Geyser were working perfectly a month or so ago though

**Comment by Pugmatt** [comment]
> > Can't say I've ever seen that login dialogue box before as displayed in the video, that isn't currently something that's in BedrockConnect. Is that showing upon connecting to BedrockConnect (Connecting to a Featured Server to open BedrockConnect), or is that showing when you join a game server from BedrockConnect?
> 
> A game server, atleast any java server. Not sure if this is something on your all's end or Geyser's.

Got it. At that point the game is completely off the BedrockConnect connection and on the game server, so the issue in this case would be happening either from the game server or Geyser. I would reach out to either the runner of the game server or [Geyser](https://github.com/GeyserMC/Geyser) and see if they know what's up.

**Comment by BlackberryCabbit** [comment]
https://github.com/GeyserMC/Geyser/issues/3591
