### ISSUE TITLE
Sever is outdated error msg.

### ISSUE THREAD

**Issue by AssasinFox69** [Pugmatt/BedrockConnect#378]
### What happened?

Hi. Me and other users noticed that this popped I don't and I don't know a lot. Please msg on discord for a video of the error. 
I am AssasinFox69#6360 
Thank you!

### Expected Behaviour?

Idk?

### Console

Xbox

**Comment by Pugmatt** [comment]
Are you using one of the community hosted BedrockConnect instances, or hosting your own?

**Comment by kmpoppe** [comment]
This issue refers to an old version of Bedrock Connect and Minecraft Bedrock and has most likely been a time-constrained error.
If this issue still persists @AssasinFox69, please say so within one week (until Jun 17th 2023), otherwise this issue will be closed.
