### ISSUE TITLE
What domains need to redirect?

### ISSUE THREAD

**Issue by travisboss** [Pugmatt/BedrockConnect#379]
### What happened?

I am just curious if you know what domains actually need to redirect?  I am not in a position to change overall DNS like this but I can redirect per domain on AGH.

### Expected Behaviour?

Redirect when certain domains are loaded.

### Console

Nintendo Switch

**Comment by travisboss** [comment]
I found it `[/mco.lbsg.net/]104.238.130.180`  this would work for anyone using adguard home.

**Comment by travisboss** [comment]
Nevermind, there seem to be more, do you just need to redirect the Servers to your DNS IP?

**Comment by travisboss** [comment]
Thanks!  got it `[/mco.lbsg.net/mco.cubecraft.net/play.galaxite.net/geo.hivebedrock.network/mco.mineplex.com/play.pixelparadise.gg/]104.238.130.180`

**Comment by TechGamer49** [comment]
Hello, thanks for providing how to do that is AdGuard!! How would I go about doing it in NextDNS? Here is a screenshot of the add rewrite screen.
![IMG_0925](https://github.com/Pugmatt/BedrockConnect/assets/156289496/e2e0b818-6884-40c4-b8f2-10eeb023d500)
