### ISSUE TITLE
IPv6 Address

### ISSUE THREAD

**Issue by noamalffasy** [Pugmatt/BedrockConnect#38]
I’m unable to use the DNS server using IPv4 because the router supports IPv6 and I can’t find a way to disable it (and to be honest, I’m not sure if it’s the right thing to do).

I can however, change the DNS servers of the LAN. That includes the IPv6 addresses.

Because of that I would like to know, is there an IPv6 address for the currently available DNS server?

**Comment by suerion** [comment]
Whats router you have

**Comment by noamalffasy** [comment]
An xfinity router

**Comment by suerion** [comment]
I thin in advanced mode, there should be an ipv6 menu

**Comment by noamalffasy** [comment]
![photo_2020-05-05 21 29 13](https://user-images.githubusercontent.com/7583207/81101916-7c42e500-8f17-11ea-967f-ae1cbc32410d.jpeg)

This is what I see.
Can't seem to find anything ipv6 related.

**Comment by Pugmatt** [comment]
You can also try hosting a local instance of BedrockConnect, and connecting to it from the LAN menu in Minecraft:

- On PC, Mac, or Linux, download this JAR: https://github.com/Pugmatt/BedrockConnect/releases
- Make sure you have Java 8 or higher installed.
- In command prompt or terminal, run the following command:
```java -jar BedrockConnect-1.0-SNAPSHOT.jar nodb=true```

At this point the serverlist server should be running. Make sure this is also running on the same network as the Xbox. When in Minecraft, go to the "Friends" tab, and the server should be showing under LAN servers and available to join.
