### ISSUE TITLE
Can't join serverlist from 1.19.63

### ISSUE THREAD

**Issue by MADKINGSINT** [Pugmatt/BedrockConnect#380]
I can't join server list (version 1.19.63) from minecraft bedrock ps4 edition(1.19.63 ) Error: old server

**Comment by Pugmatt** [comment]
Which DNS server are you using? (https://github.com/Pugmatt/BedrockConnect#publicly-available-bedrockconnect-instances) Or are you hosting a local BedrockConnect instance?

**Comment by kmpoppe** [comment]
This issue refers to an old version of Bedrock Connect and Minecraft Bedrock and has most likely been a time-constrained error.
If this issue still persists @MADKINGSINT, please say so within one week (until Jun 17th 2023), otherwise this issue will be closed.
