### ISSUE TITLE
Cant connect to bedrockconnect server

### ISSUE THREAD

**Issue by HammySammy98** [Pugmatt/BedrockConnect#387]
### What happened?

I am on Nintendo switch. My version is 1.19.70 and my switch says that I'm running the latest version. I input the correct dns settings and the "join to open server list" shows up, however upon selecting that, it attempts to send me to the bedrockconnect server and then gives the error "cannot connect to world." Its been like this for a few days now. Please help!

### Expected Behaviour?

I expected to select "join to open server list" and get directed to the gateway menu where i can input and adjust external server ip settings.

### Steps to reproduce.

1. Input dns settings on switch
2. Open minecraft 
3. Navigate to servers tab
4. Select any of them to "join to open server list"
5. I get "cannot connect to world" every time.

### Screenshots/Videos

![20230317_202115](https://user-images.githubusercontent.com/110793837/226211414-a6d358af-1faf-494f-a985-6b7d3aab40c6.jpg)

### Minecraft Bedrock Version

1.19.70

### Console

Nintendo switch

### Additional Context

I attempted to contact pugmatt on twitter and got an unhelpful "and who r u??"

**Comment by Pugmatt** [comment]
One of the instances apart of the main (104.238.130.180) was having some issues the past day or two, so might have been related to that. Should be good now though. There are also other instances available if the main is not working https://github.com/Pugmatt/BedrockConnect#publicly-available-bedrockconnect-instances

> I attempted to contact pugmatt on twitter and got an unhelpful "and who r u??"

I haven't used Twitter in years, so who ever you spoke to was definitely not me. 🤷

**Comment by kmpoppe** [comment]
This issue refers to an old version of Bedrock Connect and Minecraft Bedrock and has most likely been a time-constrained error.
If this issue still persists @MADKINGSINT, please say so within one week (until Jun 17th 2023), otherwise this issue will be closed.
