### ISSUE TITLE
Intermittent Issues When Connecting To Any Servers in Server LIST

### ISSUE THREAD

**Issue by Dirt-Nasty** [Pugmatt/BedrockConnect#39]
I've been using BedrockConnect public DNS flawlessly for the past month.  As of the past few days I've been having a hard time connecting to any of the servers in the server list.  This issue is intermittent.  Sometimes it works without issue like it has in the past and sometimes I get Unable to connect to world.  Is there any steps I can take to troubleshoot?  I am using an Xbox to connect.

**Comment by Pugmatt** [comment]
Server was having some issues in the past hour. I gave it a reset and should be working now.  As for other times this happens, could be a bad connection. Can also try hosting a local instance: https://www.youtube.com/watch?v=AW5X7-qnvLk

**Comment by Dirt-Nasty** [comment]
Looks good now @Pugmatt Thanks for the restart

**Comment by Dirt-Nasty** [comment]
@Pugmatt I believe they are down again?

**Comment by Pugmatt** [comment]
Oops, should be working again now.

**Comment by Dirt-Nasty** [comment]
@Pugmatt That worked!  Thanks!  Do you have a video on setting this up locally for others to use?  For example - Setting this up on my home server and allowing others to use it to connect to servers on that same machine?  I see videos regarding setting it up for local use but what about outside network like you have?

**Comment by Dirt-Nasty** [comment]
@Pugmatt I think servers might be down again.

**Comment by Pugmatt** [comment]
Should be back up now, think it was having some issues for a bit. To answer your other question (sorry I had missed it), you can technically do the same method as shown here: https://www.youtube.com/watch?v=AW5X7-qnvLk

You would just need to open port 53 and port 19132, and you would use your external IPv4 for the DNS records and for your game console's DNS settings. Only thing currently wrong with this method is that you can't connect yourself if your local on that network, only external connections. I'm currently working on a better solution for that.

What I host my stuff on a Linux server using BIND for the DNS server, so it's all seperate from my network.
