### ISSUE TITLE
AdamAtomus just gives Unable to connect to world

### ISSUE THREAD

**Issue by travisboss** [Pugmatt/BedrockConnect#403]
### What happened?

Trying to connect to my own instance of Minecraft using Bedrock Connect public address.

### Expected Behaviour?

Connect to my instance of Bedrock.

### Steps to reproduce.

1. Change DNS to `207.244.229.200` on Nintendo Switch
2. Open Minecraft
3. Click on Server

### Minecraft Bedrock Version

1.19.81

### Console

Nintendo Switch

### Additional Context

I only do a redirect for the domains listed on your github homepage, I do not change the DNS on my switch to only use your DNS services.  

I wanted to move to this service since it is much closer to my location.

Also looking at the link provided for Adam he does have a BedrockConnect instance forked, but I am unable to add an issue there.

If I switch back to your instance everything works fine.

**Comment by Pugmatt** [comment]
Can confirm that 207.244.229.200 appears to be down @AdamAtomus 

As for the main instance, 104.238.130.180, it is still accepting users and online. It was having some heavy traffic the last couple of days, but I've put some additional optimizations the last couple of days to hopefully help the load. If connection still fails on your end, then a local instance is recommended.

As for 188.165.49.178, this also appears to be down, and the Maintainer's GitHub profile is no longer active it appears, so I've gone ahead and removed that one from the list.

**Comment by AdamAtomus** [comment]
Should be fixed, Contabo had some maintenance and it seemed the docker failed to start when it came back online.

**Comment by AdamAtomus** [comment]
@travisboss did this solve your issue?

**Comment by travisboss** [comment]
> @travisboss did this solve your issue?

Thanks for checking in, unfortunately I am dealing with some other issues connecting to my minecraft instance, @klacointe @Pugmatt are either of you able to test this?

**Comment by Pugmatt** [comment]
Feel free to list the issue that is happening here.

**Comment by Pugmatt** [comment]
@AdamAtomus Noticed 207.244.229.200 appears to be out of date when joining, might need to upgrade the JAR to the [latest release](https://github.com/Pugmatt/BedrockConnect/releases).

**Comment by AdamAtomus** [comment]
> @AdamAtomus Noticed 207.244.229.200 appears to be out of date when joining, might need to upgrade the JAR to the [latest release](https://github.com/Pugmatt/BedrockConnect/releases).

Updated the jar, should be latest now.

**Comment by Pugmatt** [comment]
> > @AdamAtomus Noticed 207.244.229.200 appears to be out of date when joining, might need to upgrade the JAR to the [latest release](https://github.com/Pugmatt/BedrockConnect/releases).
> 
> Updated the jar, should be latest now.

Looks good 👍 Works on my end
