### ISSUE TITLE
Different ZIP folder structure for Git and manual releases

### ISSUE THREAD

**Issue by strausmann** [Pugmatt/BedrockConnect#404]
### What happened?

Since release 1.30 we have the following problem. If the release was created by GitHub Actions, the .JAR file is in the root of the archive when extracting. If the file was published by Pugmatt itself, the file is located in the "BedrockConnect-setup" folder after extraction.

### Expected Behaviour?

Can you please unify this once again? That with a normal extract the files always end up in the folder itself and not in a subfolder "BedrockConnect-setup"?

### Steps to reproduce.

```shell
echo "Downloading now Bedrock Connect JAR - version: $brc_version"
easy-add --var version=$brc_version --from https://github.com/Pugmatt/BedrockConnect/releases/download/{{.version}}/BedrockConnect-setup.zip --file $brc_source_file -to /docker/brc
```

### Minecraft Bedrock Version

1.30,1.31,1.33

**Comment by Pugmatt** [comment]
Hmm, weird. Did not notice that, thanks for pointing it out. I've updated the three versions 1.30, 1.31, and 1.33, and they should now have the same layout as the GitHub actions. (No sub-folder)

**Comment by strausmann** [comment]
seems to be working. Thanks very much
