### ISSUE TITLE
Preview/Beta version support

### ISSUE THREAD

**Issue by AJ-Stevens** [Pugmatt/BedrockConnect#405]
**Is your feature request related to a problem? Please describe.**
Tried to use the public instance of BedrockConnect to connect Preview version on Xbox (1.20.0.23 at time of this ticket), but it's unable to open the serverlist as server is out of date.

**Describe the solution you'd like**
I imagine a BedrockConnect that has the latest Preview/Beta Minecraft protocol, ideally a public hosted one, but if not then will have to install a local one on Windows/Linux.

**Comment by CrafterPika** [comment]
the issue about supporting has appeared multiple times now, see #279/#298. 
The TL;DR is updating the bedrock protocol to complicated to do it for every beta.

**Comment by CrafterPika** [comment]
@Pugmatt btw i am going to pin this issue.

**Comment by AJ-Stevens** [comment]
Sorry, I searched for “Preview” and didn’t see a mention of it.

Maybe have an entry in the FAQ and/or “Read before submitting an issue” that mentions Preview/Beta.

But I suppose this pin is good too.
