### ISSUE TITLE
[Feature request]

### ISSUE THREAD

**Issue by Gouster4** [Pugmatt/BedrockConnect#41]
Add custom servers to list for all players using some config file... Usefull for server owners.

**Comment by Pugmatt** [comment]
Currently looking into this.

**Comment by Gouster4** [comment]
I did customized it for my server.
https://github.com/Gouster4/BedrockConnect/commits/my-server

But idk how to implement using config files.

**Comment by DespicableKee** [comment]
Maybe certain players could be known as administrators, and the saved servers of those users would be shown for all users(if enabled) below default built-in servers? Maybe those users have the ability to add custom icons and names as well, making it look more like the original servers. Maybe administrators even have a settings menu with 2 options, 1 would be to show their saved servers to all, and 2 would be to remove the default servers.
I'm sure toggle options are possible with FormUI, if not the following note is not applicable:
There would be a Settings menu visible to only administrators. In that menu, the two settings listed above + any extras you add will be listed there.

**Comment by Pugmatt** [comment]
Newest version now has support for custom servers in list: https://github.com/Pugmatt/BedrockConnect/releases/tag/1.6
