### ISSUE TITLE
Server outdated because of 1.20.11 how to fix 

### ISSUE THREAD

**Issue by Brady210** [Pugmatt/BedrockConnect#422]
### What happened?

Minecraft updated and now the server is outdated how to fix

### Expected Behaviour?

Answer on how to fix it

### Steps to reproduce.

Open Minecraft 
Go to server list
Outdated server 

### Minecraft Bedrock Version

1.20.11

### Console

Xbox one x

**Comment by SirFluffDev** [comment]
Just wait a while. They'll update their server sooner or later. Somebody already asked this in #420 if that helps

**Comment by gabessdsp** [comment]
They will update. Read the "Read me before you post" https://github.com/Pugmatt/BedrockConnect/issues/144

**Comment by kmpoppe** [comment]
Good timezone everyone.

The update will be communicated in #420 and through a new [release](https://github.com/Pugmatt/BedrockConnect/releases) being published.

As this project relies on external projects also updating, we ask for your patience.

I will close this issue as it describes well known behaviour after an update to Minecraft Bedrock.

Kai
