### ISSUE TITLE
Switch error: software closed bc of unexpected error. w

### ISSUE THREAD

**Issue by ChaoticMurderLlama** [Pugmatt/BedrockConnect#424]
### What happened?

DNS settings set to 104.238.130.180 also tried 173.82.100.84. Switch progresses through normal start up. Recommended server is selected. The server list opens as expected. Selecting my desired server results in Switch closing Minecraft with the above noted (and included image) error. This is a Switch system error message and not an error from Minecraft. Minecraft needs to be fully reatarted. I am able to successfully connect to Cube Craft and other recommended servers. I am not able to connect to servers outside of the recommended list. I tested other servers. My desired server is operational with users successfully logging in from mobile, PC, and Xbox. I am able to log into the desired server from PC. I have uninstalled and reinstalled minecraft. Not sure what else to test. 

### Expected Behaviour?

Progress through typical system start up. Select a recommended server. Server list displays. Select desired server. Successfully connect to desired server. 

### Screenshots/Videos

![abefd5f3-8737-4784-9af6-2f35a0e7dbc2](https://github.com/Pugmatt/BedrockConnect/assets/139397030/13c6b6ed-956c-408b-8e62-fd14a98ce53e)

### Minecraft Bedrock Version

1.20.1

### Console

Nintendo Switch

**Comment by pallebone** [comment]
Is switch expected to be working or is there a known issue with switch?

**Comment by kmpoppe** [comment]
It works perfectly with my Switch, the error description doesn't look like anything I've seen before.

@ChaoticMurderLlama, did you try to connect to one of the recommended server from within Bedrock Connect or only on the "recommended servers " list that Minecraft Switch shows you?

K

**Comment by ChaoticMurderLlama** [comment]
I was able to successfully connect to a recommended server within Bedrock Connect.

**Comment by pallebone** [comment]
Custom servers do not work.

**Comment by ChaoticMurderLlama** [comment]
They worked before the .10 update, so what changed? How do I connect now?

**Comment by tomrow** [comment]
Works for me, but I can't use the List editor because I get an `Abandoned connection closed` error. I have to use the direct connection option.

**Comment by Pugmatt** [comment]
I'm not sure about the 'Software was closed error' crash currently, but the ```Abandoned connection closed``` error appears to be a frequent error that is occurring sporadically on most servers since 1.20.10 dropped, including outside of BedrockConnect, and there is currently an open bug report on Minecraft's bug tracker: https://bugs.mojang.com/browse/MCPE-172980

Unfortunately since this appears to be a game-sided bug, there isn't much that can be done on BedrockConnect's end at this time.

**Comment by ChaoticMurderLlama** [comment]
Thanks Mattie. I'll keep an eye on the Mojang bug reports list. Appreciate your help and Bedrock Connect.
