### ISSUE TITLE
Abandoned / Closed

### ISSUE THREAD

**Issue by bitofanooob** [Pugmatt/BedrockConnect#425]
### What happened?

Hi, we wehre using the server withouth db on a synology nas and it worked fine until the update a few days ago.
the client was updated sooner so we got a out of dat message, however today i saw an update of your containter so i updates,
the issue at hand is:

When we connect now, we get in no problem.  then we "connect to server" and fill in all fields,
when we use the slider for saving the server to list we get kicked with the message:
abandoned /  closed.  also when just connection and not saving to list.
we hope it is a minor bugfix in our situation.
please let me know if u need more information from our side.
regards, us

### Expected Behaviour?

we where expecting ti save a new server to local list

### Minecraft Bedrock Version

1.20.10

### Console

xbox one s

### Additional Context

Hi, we wehre using the server withouth db on a synology nas and it worked fine until the update a few days ago.
the client was updated sooner so we got a out of dat message, however today i saw an update of your containter so i updates,
the issue at hand is:

When we connect now, we get in no problem.  then we "connect to server" and fill in all fields,
when we use the slider for saving the server to list we get kicked with the message:
abandoned /  closed.
we hope it is a minor bugfix in our situation.
please let me know if u need more information from our side.
regards, us

**Comment by JustAiden9** [comment]
Exactly the same thing I get when I try to join my server. It’s just a normal vanilla bedrock server.

**Comment by JustAiden9** [comment]
I can not join even if I don’t add it to the server list

**Comment by JustAiden9** [comment]
The funny thing is that I can join nether games using this method but not my normal server

**Comment by Pugmatt** [comment]
Unfortunately this appears to be a bug with the Minecraft game itself when joining a game server, so nothing we can do on our end currently. There's an open issue on the Minecraft bug tracker: https://bugs.mojang.com/browse/MCPE-172980

**Comment by JustAiden9** [comment]
So the only way to fix it is just to wait till Minecraft updates the game?

**Comment by JustAiden9** [comment]
Do you think if I changed server software it would work?

**Comment by Pugmatt** [comment]
Yes, we would need to wait until Mojang updates the game, as it appears this is a bug occurring on all servers.

**Comment by JustAiden9** [comment]
Nethergames seems to work completely fine though

**Comment by kmpoppe** [comment]
I haven't updated my Bedrock Server to 1.20.10.x (it's still 1.20.0.x) and Minecraft for Windows is also not updated. The connection works flawlessly. I would imagine that Nethergames is a server that didn't update to the latest version as well.

**Comment by JustAiden9** [comment]
@kmpoppe Is there a way to downgrade my server to 1.20.0.x

**Comment by JustAiden9** [comment]
Ok, I downgraded to 1.20.0.01 and tried to join but I cant join, so what version are you on?

**Comment by kmpoppe** [comment]
1.20.0.01 just like you. It is possible that the world is the problem now because it was opened with a 1.20.10 server software.
I'm very sorry about this, but there's nothing we can do for you here I guess.

**Comment by JustAiden9** [comment]
I am on 1.20.10 on my windows pc and I am trying to join a 1.20.0.1 server and it just does not work. Are you on a 1.20.10 version of the game or something lower

**Comment by kmpoppe** [comment]
@bitofanooob @JustAiden9 @sircurse
Mojang has released a fix for this problem: https://feedback.minecraft.net/hc/en-us/articles/17690571678605 (Version 1.20.12, please update your servers and games when the fixed version releases for your Bedrock Platform)

**Comment by bitofanooob** [comment]
> Unfortunately this appears to be a bug with the Minecraft game itself when joining a game server, so nothing we can do on our end currently. There's an open issue on the Minecraft bug tracker: https://bugs.mojang.com/browse/MCPE-172980

its working again :) thanks for your quick reply!

**Comment by bitofanooob** [comment]
> @bitofanooob @JustAiden9 @sircurse Mojang has released a fix for this problem: https://feedback.minecraft.net/hc/en-us/articles/17690571678605 (Version 1.20.12, please update your servers and games when the fixed version releases for your Bedrock Platform)

much thanks!!! :)
