### ISSUE TITLE
Abandoned connection closed - not allowing players with poor connection to join

### ISSUE THREAD

**Issue by sircurse** [Pugmatt/BedrockConnect#426]
### What happened?

Hi, not sure if it is something that have changed, but after the last update if I let the server list opened for a while, like 1 minute or so and I try to connect to one of my servers I got the following error: 

**Abandoned connection closed**

It was not happening before, the problem I have with it is due to some players with slower connection, when they have to download a pack from my server, they will spent a period downloading this modpack and then they will be kicked with the same error message. So to summarize, these players with slower connections cannot play on my server without the modpack, and the server list is like "kicking them out" after a while.

I have forced to false the kick_inactive, but it doenst seems to have any effect. Is someone facing this issue or have a workaround for it?

### Expected Behaviour?

Allow players to wait for a while in the server list

### Steps to reproduce.

1. open server list
2. wait for 1 minute or so
3. try to connect to any custom server in the list

### Screenshots/Videos

![image](https://github.com/Pugmatt/BedrockConnect/assets/11935651/f3f5c38c-03e6-45bc-bc80-ad761c1794fc)

### Minecraft Bedrock Version

1.20.10

### Console

PS4/PS5

**Comment by kmpoppe** [comment]
This was already established not to be a BedrockConnect issue in #425, Mojang tracks this issue with Jura at this URL: https://bugs.mojang.com/browse/MCPE-172980
