### ISSUE TITLE
I can't connect to the server from my domain name.

### ISSUE THREAD

**Issue by ichirugame** [Pugmatt/BedrockConnect#428]
### What happened?

You can connect to BedrockConnect from the featured server.
However, when I try to connect from Connect to a Server with a domain name, the message "Abandoned connection closed" is displayed and I cannot connect.
I can connect from an IP address.

### Expected Behaviour?

You can also connect with a domain name.

### Minecraft Bedrock Version

1.20.10

### Console

Nintendo Switch

**Comment by Pugmatt** [comment]
This was already established not to be a BedrockConnect issue in #425, Mojang tracks this issue with Jira at this URL: https://bugs.mojang.com/browse/MCPE-172980

Mojang recently released 1.120.12 yesterday (https://feedback.minecraft.net/hc/en-us/articles/17690571678605-Minecraft-1-20-12-Bedrock-) which fixes this issue, but it appears it may not be released to Nintendo Switch yet, so we will need to wait for them to release the update for Switch as well.
