### ISSUE TITLE
is switch online required? i hope not.

### ISSUE THREAD

**Issue by Elikiller10562** [Pugmatt/BedrockConnect#430]

**Comment by kmpoppe** [comment]
When playing Minecraft Bedrock on the Switch online (not with a local world, not on your LAN), like on any other console, you need a Microsoft account that you log in to. The state of your Nintendo account shouldn't have any effect on how you can use Minecraft Bedrock online.

Is there a specific problem you're seeing?

**Comment by kmpoppe** [comment]
@Elikiller10562 please reply with an error message or something similar that we can check. This issue is due to close in 5 days without your reply.

**Comment by Elikiller10562** [comment]
i understand
ill close the issue thanks for the explanatiom

**Comment by Elikiller10562** [comment]
no yall gotta close it i think
