### ISSUE TITLE
I think it's a symbol problem

### ISSUE THREAD

**Issue by altat2021** [Pugmatt/BedrockConnect#436]
An error occurred when trying to join with the server's address in Minecraft. I think it's a symbol issue, but can I use the _ symbol?
(By the way, it's the switch version.)

https://github.com/Pugmatt/BedrockConnect/assets/95462070/df7adcee-96a9-4386-aa71-58eb3c3527b5

**Comment by Pugmatt** [comment]
Thank you for reporting this, the underscores indeed were not working with the previous server address validation. The latest BedrockConnect release that was released just now should now allow underscores for the server address. The main instance (104.238.130.180) has been updated, will need to wait a bit for the other instances to update, or update yours to the latest release if you are using a self-hosted instance.

**Comment by altat2021** [comment]
thank you!
