### ISSUE TITLE
Switch Game Version after joining the server

### ISSUE THREAD

**Issue by Bladestar2105** [Pugmatt/BedrockConnect#44]
Hello guys,

first of all congratulations to that great work!
I have a problem. When I try to connect to my own home-hosted server the Player joins the server and immediately disconnects. On the switch it shows "The Software Was Closed Because An Error Occurred". I use your Bedrockconnect server with my own DNS.
In my server console I see the connection: 
> 06:19:02 Player connected: Playername, xuid: 123456789
> 06:19:13 Player disconnected: Playername, xuid: 123456789

Do you have any idea? Version is 1.14.60 for Server and switch. Other players with PS4, Android or PC can join my server without any problems.

Thank you!

**Comment by Pugmatt** [comment]
Honestly not too sure. Just so I'm reading it correctly, the Switch is able to connect to the BedrockConnect serverlist fine, but throws the error when connecting to your game server?

**Comment by Bladestar2105** [comment]
Yes, That‘s right. It connects to my Server and after that the game crashes.

**Comment by Pugmatt** [comment]
Hmm, if that's the case it seems more like an issue with the game server software. BedrockConnect just sends the packet to the client to connect to the server ip, so once it makes the connection to the game server, BedrockConnect is out of the equation.

Might find some luck asking on a discussion board for the server software, unless you're using the default server software from Mojang. I'll try my best to help though.

Does the Switch usually crash for any other server, like the featured servers?

**Comment by Bladestar2105** [comment]
I use the Bedrock default server software from Mojang on a Linux Debian server.
As I said other players with PS4, Android or PC can join my server without any problems.
The featured servers I can join without problems.
Thanks for your help!

**Comment by Microtill** [comment]
I am also having the same issue. Although it was working pre 1.16.0. Ever since the update (on the switch, server and bedrockconnect) I get the error detailed above.

**Comment by kmpoppe** [comment]
Has this problem been persisting even with the newest version of BedrockConnect and Minecraft on Switch?
If I don't hear back from you within a week, I will close this issue.

**Comment by Scott-Micro** [comment]
> Has this problem been persisting even with the newest version of BedrockConnect and Minecraft on Switch? If I don't hear back from you within a week, I will close this issue.

It was so long ago, I have forgotten now. 
Please close.
