### ISSUE TITLE
IPv6? 

### ISSUE THREAD

**Issue by F-alling** [Pugmatt/BedrockConnect#449]
So on xbox it seems if your network supports ipv6 it forces you to use it but, if you have IPv6 you cant use BedrockConnect DNS for custom servers, but I have my router and want to know if there is a IPv6 DNS for BedrockConnect?

**Comment by tomrow** [comment]
XBOX consoles don't have any user-configurable DNS settings for IPv6, so it would be impossible to use without reconfiguring your DHCP server's DNS information, which most home routers forbid. Your best option to use this would be to run the BedrockConnect JAR on another device on your network (a PC, Raspberry PI, or anything that can run Java SE) and connect to it from your console as if it were a LAN game (it should appear in the Friends menu).

**Comment by F-alling** [comment]
K

**Comment by F-alling** [comment]
Would that mess my pi-hole install?

**Comment by F-alling** [comment]
@tomrow  ^^^

**Comment by CrafterPika** [comment]
> So on xbox it seems if your network supports ipv6 it forces you to use it but, if you have IPv6 you cant use BedrockConnect DNS for custom servers, but I have my router and want to know if there is a IPv6 DNS for BedrockConnect?

Copied from [here](https://github.com/Pugmatt/BedrockConnect/wiki/Troubleshooting#joining-the-featured-servers-still-directs-to-the-actual-servers-and-not-the-serverlist)

> Set the DNS directly in your router settings, using 2001:19f0:4009:4126:5400:00ff:fe22:0d52 as the primary, and 2001:4860:4860::8888 as the secondary (or any other popular DNS that supports IPv6 for the secondary)

unfortunately there isn’t anything else that can be done as Console do not allow user configs of ipv6 so either disable ipv6 in your router or set your router dns

**Comment by F-alling** [comment]
I just solved it with hosting it without the DNS server.
