### ISSUE TITLE
Switch bedrock

### ISSUE THREAD

**Issue by dutchddv** [Pugmatt/BedrockConnect#45]
Hey, man, I have followed you clip for switch.  I have had no problem and start.  Only now 2 weeks later. I'm starting to have problems with it now. Now i don't get connected every time and if I do have a connection, he says I am not connected to Nintendo and then I check my internet connection and then he says I'm just connected to everything.

You got some advice?

**Comment by Pugmatt** [comment]
Sounds like Minecraft being buggy, if it's saying it's not able to connect to Nintendo. I usually have to restart Minecraft a few times to go it to load the servers tab sometimes.

**Comment by Heath123** [comment]
The Switch version is annoying... When you use BedrockConnect with it it keeps logging you out and not connecting for some reason
