### ISSUE TITLE
1.20.30 not supported

### ISSUE THREAD

**Issue by WrttenSkate522** [Pugmatt/BedrockConnect#451]
### What happened?

The minecraft version is not supported.

### Expected Behaviour?

My nintendo switch is running bedrock minecraft 1.20.30, and yes, it IS a STABLE release, not a beta or snapshot, and there is no way for me to roll back minecraft versions on the nintendo switch. How would I use Bedrockconnect then? I am trying to connect to play.slimesmp.net on the default port.

### Steps to reproduce.

1. Use one of the DNS servers on the list
2. Join a featured server that will redirect you to the custom server list
3. Try to join a custom server (in my case I'm trying to join play.slimesmp.net)
4. The error screen will pop up saying the version isn't supported.

### Screenshots/Videos

![IMG_20230925_214708](https://github.com/Pugmatt/BedrockConnect/assets/146045414/ab53e601-26b3-4802-a280-1aae0fea99e5)
![IMG_20230925_214634](https://github.com/Pugmatt/BedrockConnect/assets/146045414/311a9dd6-7bb1-4252-bbb2-ea39188be260)
![IMG_20230925_214608](https://github.com/Pugmatt/BedrockConnect/assets/146045414/f3ec999e-d30d-4afc-a8f2-7059a7e2856f)

### Minecraft Bedrock Version

1.20.30

### Console

Nintendo Switch

### Additional Context

What can I do?

**Comment by WrttenSkate522** [comment]
One other update, I tried the local version, I DOWNLOADED THE 1.20.30 REALEASE, AND IT STILL SAYS MY VERSION ISN'T SUPPORTED!

**Comment by Rahzadan** [comment]
AFAIK this is related to the destination server's Geyser plugin being outdated, and nothing to do with BedrockConnect. I just used the serverlist a few mins ago and I'm on version 1.20.31.

**Comment by Pugmatt** [comment]
As stated by Rahzadan, this is not BedrockConnect that is out of date, it is the Geyser proxy hosted by the server that you're trying to join that is out of date. The host of that will need to upgrade their Geyser proxy for their server to 1.20.31, which is not related to BedrockConnect.

**Comment by WrttenSkate522** [comment]
what Geyser proxy? I am tryed the public DNS too, but it gave me the same error? How can I update the Geyser proxy? I also tried the local version, and i downloaded the 1.20.30 VERSION, FROM THE RELEASES, and it still doesn't work.

**Comment by Rahzadan** [comment]
If you don't own or administer the server you're trying to connect to, then you can't update Geyser. You'll need to contact the owner of the server (slimesmp.net) and tell them that the Geyser proxy they're running is old and doesn't support 1.20.30.

**Comment by WrttenSkate522** [comment]
Oh ok thanks i get it now
