### ISSUE TITLE
Unable to connect with fetch_featured_ips=false?

### ISSUE THREAD

**Issue by hasankayra04** [Pugmatt/BedrockConnect#455]
### What happened?

So when fetch_featured_ips is set to true, when i tried to join any featured server from BedrockConnect it would connect me back to BedrockConnect. 
I am using a custom dns so i figured it must be dns, resolving domain to same ip.
So i set fetch_featured_ips to false, file was generated. And it looked fine.
But now if i try to connect i just get "Unable to connect to world"

### Expected Behaviour?

Connect to featured servers?

### Steps to reproduce.

1. Set fetch_featured_ips to false.
2. Join a featured server using BedrockConnect.

### Minecraft Bedrock Version

1.20.31

### Console

Testing with my mobile, since i don't have any consoles.

**Comment by Pugmatt** [comment]
The IPs contained in the generated file are most likely outdated at this point, which is to be expected as they can change frequently and is why a file is generated when fetch_featured_ips is false, so you can update the file when needed. You can use a website like https://www.nslookup.io/ to enter each domain name, get the IP address, and set the new IP address into the file.

**Comment by hasankayra04** [comment]
Ah thanks, i though they were up to date.

**Comment by hasankayra04** [comment]
Manually updating address fixed the issue.
