### ISSUE TITLE
Update to 1.20.50

### ISSUE THREAD

**Issue by JefferyPlayz** [Pugmatt/BedrockConnect#464]
### What happened?

All users are not able to connect to any DNS addresses. They get the error, 'The host is using an older version of Minecraft'.

### Expected Behaviour?

To be able to join the servers and access 3rd party server list

### Steps to reproduce.

1. Set your DNS to one of the provided in the GitHub
2. Open Minecraft Bedrock 1.20.50
3. Join a server in server tab

### Screenshots/Videos

![20231205_173954](https://github.com/Pugmatt/BedrockConnect/assets/146920696/70b7c448-a04c-4c1c-9bda-17cfa77ad8b6)

### Minecraft Bedrock Version

1.20.50

### Console

Nintendo Switch, PS5 and XBOX

**Comment by cyberops7** [comment]
I came to report the same issue for my self-hosted bedrock connect instance. It looks like their automation created an issue for the new version just now:
https://github.com/Pugmatt/BedrockConnect/issues/465
