### ISSUE TITLE
[Nintendo Switch] Cant connect to serverlist on ANY public DNS

### ISSUE THREAD

**Issue by RSChao1HM** [Pugmatt/BedrockConnect#466]
### What happened?

(This is my friends case, not my own) He tries to connect to every DNS available closest to us (we tried EU servers on that criteria but also USA servers just in case) Nothing works. We tried conexion tests beforehand, and nothing.

### Expected Behaviour?

On joining Galaxite (the server I mainly use) server list pops up and no pack is downloaded.

### Steps to reproduce.

Set to any EU or USA dns
Open Minecraft
Join Galaxite

### Minecraft Bedrock Version

1.20.50

### Console

Nintendo Switch

### Additional Context

Secondary DNS: 8.8.8.8 or 008.008.008.008

**Comment by Pugmatt** [comment]
Not sure what you mean by "no pack is download", can you expand on that? Is it just directing to Galaxite like usual?

**Comment by Pugmatt** [comment]
Nevermind I see what you mean. I would recommend your friend follow the steps under "Joining the Featured Servers still directs to the actual servers and not the serverlist..." in the troubleshooting if they haven't already: https://github.com/Pugmatt/BedrockConnect/wiki/Troubleshooting#joining-the-featured-servers-still-directs-to-the-actual-servers-and-not-the-serverlist

**Comment by RSChao1HM** [comment]
Unfortunately, I did read the guide. Since were both kids and bad at networking, I wont change the router. Otherwise, I will re-check this. Thank you very much
