### ISSUE TITLE
BedrockConnect Setup

### ISSUE THREAD

**Issue by TechGamer49** [Pugmatt/BedrockConnect#469]
### What happened?

Hello, I was wondering how you got the 45.55.68.52 address to work for the server list. I am using NextDNS and can’t get it to work but I managed to get it to run locally on my network but was wanting to have it public so other devices outside my local network can join

### Expected Behaviour?

I expected it to display correctly in the featured server list.

### Minecraft Bedrock Version

1.20.51

### Console

PlayStation 5

### Additional Context

I would like further help on getting this setup. I followed the video closely that was 3 years ago that explained how to do it.

**Comment by TechGamer49** [comment]
How did you get yours setup @Pugmatt? Like what all did you use DNS wise.

**Comment by Pugmatt** [comment]
I'm not really sure how NextDNS works, but will try my best to help. The video tutorial you're referencing is for how to host a setup for devices on your local network, making it public will require a bit more setup. My BedrockConnect setups are all hosted on Linux servers through a paid host, but if you're using NextDNS for your DNS and your own network for the BedrockConnect instance you will need to make sure the following is considered:

- Make sure you are using the featured server domains for your DNS records listed here: https://github.com/Pugmatt/BedrockConnect#using-your-own-dns-server
- Make sure port 19132 is port forwarded on your network
- When setting up the DNS records to redirect the featured server domains to the BedrockConnect instance, make sure you're using your PUBLIC IP address and not private (Like the one you see on https://whatismyipaddress.com/)
- You may notice devices outside your network can connect, but local devices on your network cannot. Please see the section "Making it so local/LAN devices can still connect" here if this occurs: https://github.com/Pugmatt/BedrockConnect/wiki/Allowing-outside-connections-to-connect-to-local-Windows-setup/_edit#making-it-so-locallan-devices-can-still-connect

**Comment by TechGamer49** [comment]
So would I port forward the Routers IP Address? The link that gives the IP Address is the same on button web pages. All the ports are forwarded to the public IP which include port 53, 19132-19133 and my computer uses ports 19134-19135 that is connected to the devices IP. And I see something about Internal for local and external for Public. What all configuration did you use @Pugmatt

**Comment by Pugmatt** [comment]
You would want to make sure you have the ports forwarded in your router's settings. Assuming you are hosting your BedrockConnect instance on that network. 

Your configuration will depend on how NextDNS works. On mine (Which uses bind9 for the DNS server, which is a self-hosed solution) I'm using the DNS domain records stated previously https://github.com/Pugmatt/BedrockConnect#using-your-own-dns-server, which redirects the domains to the public IP address of the Linux server hosting the BedrockConnect instance. 

In that doc above, by "external" I mean public IP, and "internal" I mean private IP address. What may be easier for your use-case, is use NextDNS for devices outside your network to join, and then continue using a locally-hosted DNS server like in the previous video tutorial for any local devices on your network. Have your NextDNS setup set to redirect the domains to your public IP address, and your locally-hosted DNS for your personal-use redirects to your private IP address as shown in the video tutorial. As you may be running into the issue stated in the "Making it so local/LAN devices can still connect" section.

**Comment by TechGamer49** [comment]
So it gives me two dns addresses that end in .235 and is also bind to the public ip address

**Comment by TechGamer49** [comment]
I will reply with screenshots

**Comment by TechGamer49** [comment]
So I did the public IP Address and the ports that are forward are 53, 19132-19133. Remote IP addresses is set to All

**Comment by TechGamer49** [comment]
The way I have NextDNS setup is it gives me 2 dns addresses to put in to the manual dns servers

**Comment by TechGamer49** [comment]
My external starts with 216 and my internal starts with 192

**Comment by TechGamer49** [comment]
My DNS starts with 45

**Comment by TechGamer49** [comment]
Would I have to port forward my DNS or Not? Can you list out the steps I need to take apart from the different faq sections in the troubleshooting?

**Comment by TechGamer49** [comment]
Am I allowed to post IP Addresses or not? Thought I would ask

**Comment by TechGamer49** [comment]
NextDNS doesn’t have an option to redirect but gives me the DNS info to setup on windows network adapters and the addresses for different devices

**Comment by TechGamer49** [comment]
![IMG_0922](https://github.com/Pugmatt/BedrockConnect/assets/156289496/fce1225e-ae2c-475e-9d5c-d47d330635e0)

**Comment by TechGamer49** [comment]
I found that in the settings tab on NextDNS

**Comment by TechGamer49** [comment]
If you want I could add you to my NextDNS dashboard so you can see what options are available? Let me know if you need access or not that’s fine

**Comment by TechGamer49** [comment]
![IMG_0923](https://github.com/Pugmatt/BedrockConnect/assets/156289496/8a1367ff-e1f8-49f7-aaf8-c9e5005c4163)

so I point it towards those zones? And do I use my own dns or the dns that’s listed in that table.

are there any other DNS services I could use to get the my own server going?

**Comment by TechGamer49** [comment]
I might try adguard out and see if that works

**Comment by TechGamer49** [comment]
And here is the add screen as you may have seen in other issue tickets. 
![IMG_0925](https://github.com/Pugmatt/BedrockConnect/assets/156289496/b3ef2cd9-a866-414e-b6db-ab0701f3435f)

**Comment by Pugmatt** [comment]
> Would I have to port forward my DNS or Not? Can you list out the steps I need to take apart from the different faq sections in the troubleshooting?

Port forwarding is needed when you need to allow outside devices onto your network for specific ports. NextDNS are pre-made services so all ports should already be public. Again, I do not have experience with these platforms so I can't list out steps here for you.

> so I point it towards those zones? And do I use my own dns or the dns that’s listed in that table.

You point those zones TOWARDS your BedrockConnect instance's IP address. The point of the DNS server is to redirect those featured server domains TO the BedrockConnect instance. The IP address listed in that table is not the DNS, it's the BedrockConnect instance. You can either use "104.238.130.180" which my already hosted BerockConnect instance, or you if you're hosting your own on your network you can use that one, in which case you would put in your public IP address.

**Comment by lixiaolong2007** [comment]
emm,I drew a schematic that may not be correct, but understanding it will be helpful for you to set up DNS![2024-01-13-02-11-17-768.jpg](https://github.com/Pugmatt/BedrockConnect/assets/93075973/00c0ee39-0e56-4602-abe7-bd687920abef)

**Comment by lixiaolong2007** [comment]
emm,I drew a schematic that may not be correct, but understanding it will be helpful for you to set up DNS![2024-01-13-02-12-19-441.jpg](https://github.com/Pugmatt/BedrockConnect/assets/93075973/0dfaaf96-e79b-4ad7-89e0-8179f653610e)

**Comment by lixiaolong2007** [comment]
I haven't used nextdns before, so I can only provide this help

**Comment by TechGamer49** [comment]
Thanks for all the help and I have seemed to finally figure it out so I put the Minecraft server domain and point it towards my Public IP Address when will go towards the bedrock connect server and so my Minecraft server since it’s local might be able to run on NextDNS as well!!


Sent from TechGamer49


On Friday, January 12, 2024, 11:14 AM, lixiaolong2007 ***@***.***> wrote:




I haven't used nextdns before, so I can only provide this help

**Comment by TechGamer49** [comment]
Did I do it correctly?



Sent from Yahoo Mail for iPhone


On Friday, January 12, 2024, 1:27 PM, Riley Liakos ***@***.***> wrote:

Thanks for all the help and I have seemed to finally figure it out so I put the Minecraft server domain and point it towards my Public IP Address when will go towards the bedrock connect server and so my Minecraft server since it’s local might be able to run on NextDNS as well!!


Sent from TechGamer49


On Friday, January 12, 2024, 11:14 AM, lixiaolong2007 ***@***.***> wrote:




I haven't used nextdns before, so I can only provide this help

**Comment by TechGamer49** [comment]
![IMG_0926](https://github.com/Pugmatt/BedrockConnect/assets/156289496/89fc1060-0128-4e69-a3d8-0e6d76864da5)

did I do it correctly?

**Comment by TechGamer49** [comment]
Update: I switched to Ubuntu server with bind9


Sent from Yahoo Mail for iPhone


On Friday, January 12, 2024, 4:10 PM, Riley Liakos ***@***.***> wrote:

Did I do it correctly?



Sent from Yahoo Mail for iPhone


On Friday, January 12, 2024, 1:27 PM, Riley Liakos ***@***.***> wrote:

Thanks for all the help and I have seemed to finally figure it out so I put the Minecraft server domain and point it towards my Public IP Address when will go towards the bedrock connect server and so my Minecraft server since it’s local might be able to run on NextDNS as well!!


Sent from TechGamer49


On Friday, January 12, 2024, 11:14 AM, lixiaolong2007 ***@***.***> wrote:




I haven't used nextdns before, so I can only provide this help

**Comment by TechGamer49** [comment]
I got the local ip to work and have it port forwarded and have my public ip address in the install-bind.sh file but I am unable to connect still. The sudo install-bind.sh command said it was invalid. I used nano to open the file and manually put it in the file and saved. 
![IMG_0929](https://github.com/Pugmatt/BedrockConnect/assets/156289496/feddccc7-5fd6-4d15-bffa-163bc9ed6280)
![IMG_0930](https://github.com/Pugmatt/BedrockConnect/assets/156289496/2cce884b-3d03-4066-af69-6549029b7a1d)
![IMG_0931](https://github.com/Pugmatt/BedrockConnect/assets/156289496/a9efa24f-5410-4c9b-a318-1740aeb7fd35)
![IMG_0932](https://github.com/Pugmatt/BedrockConnect/assets/156289496/b0bd0418-0549-4c98-9b7c-fa52f92815b2)

**Comment by TechGamer49** [comment]
This issue has been self-resolved :) thanks for the help @Pugmatt @lixiaolong2007

**Comment by TechGamer49** [comment]
This issue has been self-resolved :) thanks for the help @Pugmatt @lixiaolong2007
