### ISSUE TITLE
BedrockConnect serverlist server not up to date ?

### ISSUE THREAD

**Issue by Corenb** [Pugmatt/BedrockConnect#47]
Hello, I'm trying to use your DNS to connect to my bedrock server but it won't work.
Is you running server is up to date with your latest release? Cause server's motd showing "Join to open Server List - 1.14.0" instead of 1.14.60 ?

**Comment by Pugmatt** [comment]
The server works on all 1.14 versions. Is the issue occurring when getting on the serverlist, or when joining your server from the serverlist?

**Comment by Corenb** [comment]
When I try to join my server :/

**Comment by Corenb** [comment]
Have u a bedrock server on wich I can try to connect ?

**Comment by Pugmatt** [comment]
Sounds like a possible issue with the server you're trying to connect to then, as BedrockConnect just sends a packet that sends the player to the server and off of BedrockConnect. What is the error message or issue that causes it to not work?

The bedrock server I always use in my tutorials is ownagepe.com, which still currently works for me with BedrockConnect.

**Comment by Corenb** [comment]
The server just seem not available (can't connect to the world).

I gonna try with ownagepe.com

**Comment by tomwardrop** [comment]
No longer working? Have they patched it?

**Comment by Pugmatt** [comment]
Appears to be up currently. Its been under heavy load today, so might experience some lag.

**Comment by tomwardrop** [comment]
I can't get the server list to appear. I've updated dns server correctly. It just logs me in to the realms? I'm wired connection using IPV4 and have rebooted the box. Do I need to update my main router dns as well?

**Comment by Pugmatt** [comment]
Does the server list not appear as in the one on the main menu? Sounds like Minecraft glitching if it's not showing the featured servers at all.
