### ISSUE TITLE
Unable to connect to world. (Server list)

### ISSUE THREAD

**Issue by jmichaluk** [Pugmatt/BedrockConnect#48]
I’ve been having problems connecting since last night. I was playing on my sever and then it seemed to go down. Was able to connect again and it connected just fine, but booted me a few minutes later. 

After that I was no longer able to connect. I can’t remember the details beyond that from last night, but I’m still having issues this morning. 

When trying to connect to a server list I get the message “unable to connect to world.”  
A few times I’ve also received a “connection timed out” but usually it’s the first message without any clear error.

**Comment by Pugmatt** [comment]
Server was having a few issues, should be back up now.

**Comment by timvandenhof** [comment]
@Pugmatt Seems to be down again.

**Comment by Pugmatt** [comment]
Should be back up now.
