### ISSUE TITLE
Public DNS Server List redirecting back to iteself, not intended server IP (SOLVED)

### ISSUE THREAD

**Issue by mattingg** [Pugmatt/BedrockConnect#480]
### What happened?

I followed your installation guide on YouTube and GitHub and installed BedrockConnect to host my own Public DNS Server using my own IP. The server works, However i am unable to join any server IP on my switch, it just redirects straight back to the DNS Server menu after i try to connect.

### Expected Behaviour?

Connect to public server IP

### Screenshots/Videos

![image](https://github.com/Pugmatt/BedrockConnect/assets/139821784/f86e9bc3-52ef-4a9c-b8bc-c0a3f79b28ec)

https://youtu.be/g1DZPv275JI

### Minecraft Bedrock Version

1.20.71

### Console

Nintendo Switch

### Additional Context

I have tried 1.1.1.1 and 8.8.8.8 for the secondary DNS, and have also tried connecting to the internet via a different network (Mobile Data) but aside from this i'm lost for what i can do next to try and resolve this issue.

_No response_

**Comment by mattingg** [comment]
I think it may be because the Bedrock version is now 1.20.71 and the DNS server is for 1.20.70?

**Comment by mattingg** [comment]
Just to clarify also: I am hosting a Minecraft Geyser/Floodgate server on the same device & same IP address as the DNS Server, will this affect anything? I am still able to get the server list up on the switch, just not connect to the server, as per the YT video.

On the DNS Server '.bat' file, i sometimes get "java.net.BindException: Address already in use: bind" But only if i open the DNS server after i launch the Geyser/Floodgate server

**Comment by mattingg** [comment]
Turns out hosting the DNS server and Minecraft server on the same IP wasn't a good idea and wasn't allowing connections to the server itself through the bedrock port, as this was being used by the DNS server. Managed to use a public DNS in Germany from the list and it sorted itself haha. I'm new to this kind of issue lol i feel like i've achieved something by figuring this out hahaha

**Comment by Pugmatt** [comment]
As you discovered, the BedrockConnect port is the same as the default Minecraft game server software (As BedrockConnect is technically just a modified Minecraft server). So to host both a game server + BedrockConnect on the same machine, you would need to either:

- Change the port of your Minecraft game server (BedrockConnect would need to stay on port 19132, in order for the bypass method to work)
- Or, bind either the game server or BedrockConnect (See ```bindip``` launch argument in README) to a different IP address

Just changing the port on the game server would probably be easiest.
