### ISSUE TITLE
No serverlist is shown, world is empty

### ISSUE THREAD

**Issue by timvandenhof** [Pugmatt/BedrockConnect#49]
Today the public BedrockConnect server stopped working.

Players can succesfully enter the public BedrockConnect server using the public DNS as mentioned in the Readme. They however cannot join any server, as the serverlist popup is not showing up.

![image](https://user-images.githubusercontent.com/2083464/83173047-bec3a000-a118-11ea-865d-8ce577569f4a.png)

**Comment by Pugmatt** [comment]
Servers been under heavy load today for whatever reason. I gave it another restart and it should be back up now. I'll be keeping an eye on it.

**Comment by timvandenhof** [comment]
I can confirm it is back online now.
Thanks for the quick response and resolving this issue.
