### ISSUE TITLE
Server list does not appear at all. Switch v1.21.2

### ISSUE THREAD

**Issue by Raini-Water12** [Pugmatt/BedrockConnect#512]
### What happened?

I updated my game, and now the list does not appear at all. All the featured servers go to their server. I've tried every troubleshooting idea.

### Expected Behaviour?

Having the servers say "Go to server list" or whatever and then go to the server list.

### Steps to reproduce.

No idea, it worked perfectly fine until I updated the minecraft game.

### Screenshots/Videos

![20240712_231133](https://github.com/user-attachments/assets/ed9b0c7e-580d-467a-8672-9f5159d84262)
![20240712_231201](https://github.com/user-attachments/assets/d6536ad4-a6c2-457d-9155-fb6c39d145d3)
![20240712_231220](https://github.com/user-attachments/assets/e098676b-a7d1-4ddc-8b59-2dd751755418)

### Minecraft Bedrock Version

1.21.2

### Console

Nintendo Switch OLED

### Additional Context

I've tried every troubleshooting thing, but I cannot access the server list. Please help if you can.

**Comment by Pugmatt** [comment]
Couple of specific things you may want to try if none of the DNSs seem to be affecting your system:

- LazyBirb's hosted BedrockConnect instance has MCXboxBroadcast - In the Minecraft main menu, go to the "Friends" tab, click "Find Cross-Platform Friends", add the player McBEFC. Return to the Minecraft main menu. Wait a moment (may need to restart game), and the BedrockConnect instance should appear under the "Friends" tab in the section "Joinable Cross-Platftom Friends'.
- (If possible) Try setting the DNS directly in your router's settings. Where to set this would depend on what brand of router you have. (e.g. Netgear, TP-Link, etc) You can try googling "[your router brand here] router how to set dns in router settings"

**Comment by Raini-Water12** [comment]
The friend thing worked perfectly, thank you! ♡☆
