### ISSUE TITLE
MCXboxBroadcast for main bedrock connect instance seems to be offline.

### ISSUE THREAD

**Issue by CoveWolf** [Pugmatt/BedrockConnect#515]
Hello! I am a big fan of this project. It's incredibly easy to setup up with the "add friend" method. But the "BCMain" account seems to be offline and it doesn't show up in the friends tab as of typing. I was wondering what could be done and if it's anything on my end. Again big fan of the project and take your time. Thanks!

**Comment by CoveWolf** [comment]
Also apologies for putting it under the enhancement flag! I didn't mean to do that.

**Comment by Pugmatt** [comment]
Looks like Microsoft temporarily blocked the account, may have been from the burst of activity on it. Thankfully was able to unlock it. Will keep an eye on it.

If Microsoft takes it down again, LazyBirb also has the same "add friend" method available on their instance that can be used: https://github.com/LazyBirb/LazyBirb/blob/master/bedrockconnect/README.MD
