### ISSUE TITLE
Postgres support

### ISSUE THREAD

**Issue by samip5** [Pugmatt/BedrockConnect#519]
**Is your feature request related to a problem? Please describe.**
I don't want to run MariaDB/MySQL

**Describe the solution you'd like**
Proper support for PostgreSQL

**Describe alternatives you've considered**
Run MariaDB/MySQL

**Additional context**
I might just do it myself as it seems it should be fairly simple to do.

**Comment by Pugmatt** [comment]
Postgres support is now added in the latest release, 1.48. You will need to set db_type to *postgres*, and configure the other [db_* settings](https://github.com/Pugmatt/BedrockConnect#configuration) as needed
