### ISSUE TITLE
Bedrock connect hangs on connecting to server Switch.

### ISSUE THREAD

**Issue by NibblerJ2** [Pugmatt/BedrockConnect#527]
### What happened?

When you click the server list you don't get the server list it just sits there. Eventually ending out with cannot connect to world. The rare times it works it connects fine.  Use the option to join server list it waits about 2-3 minutes before failing 90% its also a local self hosted instance of BC. The previous entry before 1.21.20 worked just fine. This is hosted on a dedicated Linux machine always been working great using it for about a year.

### Expected Behaviour?

Well.. it was working so only thing changed was the updates. I figure it would connect I tried for a while now different instances. It so far connects once a day. 

### Minecraft Bedrock Version

1.21.20

### Console

Nintendo Switch

**Comment by Pugmatt** [comment]
Are you connecting using the DNS method, or "Add Friend" method / MCXboxBroadcast? If you are connecting using the "Add Friend" method, the recent update broke it and it's currently being looked into https://github.com/rtm516/MCXboxBroadcast/issues/122 If you are using this method you will need to use the DNS method for now.

**Comment by Pugmatt** [comment]
Hmm, if the DNS method is being used then it sounds like a possible connection issue to the BedrockConnect instance, your device for whatever reason is not seeing the connection. From my testing I have not seen any game-bug related connection issues introduced this 1.21.20 update when joining through the DNS method, including on Nintendo Switch.

The 1.21.20 did seem to bring a lot of game bugs related to connecting to servers, so it is possible there is something related to that causing your issue, but I can't seem to replicate on my end so I'm not sure what it could be.

> sounds very much like the behavior after its been running for a while.

If you have this running 24/7, I would recommend having some kind of cronjob or automated daily run on your Linux setup that restarts it once a day or at least once in a while.

**Comment by NibblerJ2** [comment]
Well i run it for a small instance 1-2 friends i turn it off at night. The server works great once connected. It might be the machine running bedrock connect. Although it does do it with the public one. I ran pktstat looking at connections the dns part is working every time for sure. There is a lot going on there so I cant say for certain as thats a laptop running BC.

**Comment by bstaxx** [comment]
I'm having the same issue. DNS methods seems to be broken

**Comment by bstaxx** [comment]
I'm on version 1.21.21

**Comment by netapy** [comment]
Also broken here on 1.21.20

**Comment by tolookah** [comment]
DNS is spotty at best with the switch.  I think this is a Minecraft bug with 1.21.20.

**Comment by sircurse** [comment]
I have the same issue on self hosted using DNS.
I also have a bedrock bot that was broken with that update because Mojang made a few changed to the network APIs, related to minecraft-data. It broken many bedrock bot to connect to the 1.21.20, it might be the reason for that issue too... Anyway restarting the services not always works, it is inconsistently so I cannot even create a macro to restart it time to time because it is not guaranteed that it will work. Right now I m trying to connect to my server after several minutes, restarting, stopping/starting the services and still not able to connect.

**Comment by Pugmatt** [comment]
Make sure you all are updated to 1.21.21 in your game version. I believe that version just dropped for the Nintendo Switch version yesterday (had already been available on other consoles since), which contains server connection fixes.

**Comment by tolookah** [comment]
Yes, the switch update came out, it works, thanks for the reminder.

**Comment by NibblerJ2** [comment]
1.21.21 actually seems to have less problems. *shrugs* maybe it was a bug
