### ISSUE TITLE
Cannot see server list in the game itself

### ISSUE THREAD

**Issue by omnidotnet** [Pugmatt/BedrockConnect#528]
### What happened?

When trying to go to the server list (latest version, Nintendo Switch, no online subscription, secondary DNS is 1.1.1.1, using the main DNS), instead of displaying the featured servers from which I could join the BedrockConnect server from, it says "You need a Microsoft and Nintendo account to play online." I have my Nintendo account linked to my profile in the console, and am signed in to my Microsoft account (it shows it inside the game)

### Expected Behaviour?

I would go to my server list in the game menus and see featured servers from which I can go to the BedrockConnect server.

### Minecraft Bedrock Version

1.21.20

### Console

Nintendo Switch

**Comment by Pugmatt** [comment]
> no online subscription

You need an online subscription to Switch Online in order to connect to the multiplayer servers. That is a limitation placed by Nintendo/Mojang.
