### ISSUE TITLE
Corrent wiki.

### ISSUE THREAD

**Issue by F-alling** [Pugmatt/BedrockConnect#529]
### What happened?

Remove or strike the "add friend" section since it is currently not working (under the troubleshooting section [here](https://github.com/Pugmatt/BedrockConnect/wiki/Troubleshooting#joining-the-featured-servers-still-directs-to-the-actual-servers-and-not-the-serverlist)

### Expected Behaviour?

N/A

### Additional Context

Hopefully this was the right type of issue.

**Comment by F-alling** [comment]
Related to https://github.com/rtm516/MCXboxBroadcast/issues/122

**Comment by LazyBirb** [comment]
There is no need of removing the guide as this bug is only temporary, a info about it had been already added to the repo
![image](https://github.com/user-attachments/assets/3dabe9a6-76c1-477c-8a49-5887deb2439a)
