### ISSUE TITLE
Not working on phone or pc

### ISSUE THREAD

**Issue by Loca123456** [Pugmatt/BedrockConnect#533]
### What happened?

I am testing the add the friend method on my phone and pc when I added the friend to the list nothing happend 

### Expected Behaviour?

Add the friend 20 secs later something shows up

### Screenshots/Videos

!
![Screenshot_2024-08-30-23-56-35-45_5c8300b655012b1930f2e0a7b81bf6a9](https://github.com/user-attachments/assets/a37e21de-ae1c-46dc-8625-71a033a427f4)
![IMG_20240831_000006](https://github.com/user-attachments/assets/73764ae4-366f-45cf-90e2-fad0f14d8022)

### Minecraft Bedrock Version

1.21.22

### Console

Phone pc bedrock

**Comment by Pugmatt** [comment]
Unfortunately Microsoft had locked both accounts over the weekend, I was out of town so did not see it until now. Both should now be unlocked and working again.
