### ISSUE TITLE
New Bedrock Version 1.21.30 has been published!

### ISSUE THREAD

**Issue by CoveWolf** [Pugmatt/BedrockConnect#538]
### What happened?

New Bedrock Version 1.21.30 has been published!

### Expected Behaviour?

expected to connect to the server menu but can't due to outdated server.

### Steps to reproduce.

1. Join via your preferred method
2. Fails to connect 

### Minecraft Bedrock Version

1.21.30

### Console

Xbox

**Comment by kmpoppe** [comment]
The new version hasn't yet been implemented in BedrockConnect because this is a voluntarily maintained project.
Watch this repository to get notified when a new release is published, which will then be pushed to the main BedrockConnect instance.
