### ISSUE TITLE
severs not working

### ISSUE THREAD

**Issue by Sammystar-a11y** [Pugmatt/BedrockConnect#540]
### What happened?

*I entered the code and now my servers just don't work* the ping just kept loding and I cant join.

### Expected Behaviour?

I followed the video and put * 104 238 130  180 (secondary)  8 8 8 8

### Steps to reproduce.

1 sherch up (how to get the add server button on bedrock 2024)   2 follow the video restart your xbox and enter minecraft  3 go to your server list and your ping wont stop loding

### Minecraft Bedrock Version

1.21

### Console

Xbox series s

### Additional Context

(*)

**Comment by F-alling** [comment]
It appears the main list is currently not working. Try using a different one.

**Comment by Pugmatt** [comment]
Main instance appears to be working okay, at least right now. (Can confirm from my end it's up and logs show successful connections from players) If none of the other instances work it could be a device issue connecting to custom DNSs, in which case I would recommend using the "Add friend" method instead (Which is easier anyway): https://github.com/Pugmatt/BedrockConnect?tab=readme-ov-file#add-friend-method

**Comment by Sammystar-a11y** [comment]
yeah it started working yesderday
