### ISSUE TITLE
Pls Update to Support 1.21.41

### ISSUE THREAD

**Issue by GERDominik165** [Pugmatt/BedrockConnect#547]
**Is your feature request related to a problem? Please describe.**
A clear and detailed description of what the problem is. Ex. I'm always frustrated when [...]

**Describe the solution you'd like**
A clear and detailed description of what you want to happen.

**Describe alternatives you've considered**
A clear and detailed description of any alternative solutions or features you've considered.

**Additional context**

**Comment by GERDominik165** [comment]
Hello there is something wrong with latent Version Support  @Pugmatt

**Comment by Pugmatt** [comment]
BedrockConnect is already updated to work with the latest version. What error are you seeing?

**Comment by GERDominik165** [comment]
"The host is using a older Version, all neid to Update Version of minecraft"

On Nintendo switch and Windows with 1.21.41 tested with Latest Bedrock Connect

**Comment by GERDominik165** [comment]
What ist latest protocol Version?
