### ISSUE TITLE
BedrockConnect update for 1.16

### ISSUE THREAD

**Issue by spydreb1t3** [Pugmatt/BedrockConnect#55]
Since the 1.16 update dropped today and the current version dies with a RuntimeException in RakNet: Unable to inflate buffer data.

Will there be an update that supports 1.16, so I can join my private server?

**Comment by Nagol12344** [comment]
i hope

**Comment by spydreb1t3** [comment]
Well, let's see, this is a project made as a labour of love and a gift to the community. I'm positive there will eventually be an update :)

**Comment by Hazzard13** [comment]
Pugmatt has confirmed in a [pinned youtube comment](https://www.youtube.com/watch?v=zalT_oR1nPM) that he's working on 1.16 compatibility.

**Comment by spydreb1t3** [comment]
Great stuff! I'm following the project so I check back in once it drops! Thanks for the update! Good luck! :)
