### ISSUE TITLE
Still using old following system 

### ISSUE THREAD

**Issue by henrydarklordofdeath** [Pugmatt/BedrockConnect#554]
### What happened?

The bot is constantly unfollowing me, so I must constantly re-add it.

### Expected Behaviour?

I want it to be able to except the new Xbox freand requests, instead of using the following system.

### Minecraft Bedrock Version

Don't matter 

### Console

Nintendo switch 

### Additional Context

This is not a bug for me, it is a bug for everyone.

**Comment by Pugmatt** [comment]
Which bot are you using? BCMain & BCMain1 are on the newest version of MCXboxBroadcast, they should already have support for this.

**Comment by Pugmatt** [comment]
Hmm, I tried adding one of the bots through the add friend button on the Xbox website, and can confirm the bot appears to be throwing an error when attempting to be added through this method. Seems to be a bug in MCXboxBroadcast or the response the Xbox servers are returning, as I can confirm the bots are on the newest version. Will see what's up.

For now please use the following system or add the bot through the Minecraft main menu as outlined in the [README tutorials section](https://github.com/Pugmatt/BedrockConnect?tab=readme-ov-file#add-friend-method).

**Comment by henrydarklordofdeath** [comment]
Ok thank you.
-------- Original message --------From: Matthew Hafner ***@***.***> Date: 12/5/24  6:39 AM  (GMT-08:00) To: Pugmatt/BedrockConnect ***@***.***> Cc: henrydarklordofdeath ***@***.***>, Author ***@***.***> Subject: Re: [Pugmatt/BedrockConnect] Still using old following system  (Issue #554) 
Hmm, I tried adding one of the bots through the add friend button on the Xbox website, and can confirm the bot appears to be throwing an error when attempting to be added through this method. Seems to be a bug in MCXboxBroadcast or the response the Xbox servers are returning, as I can confirm the bots are on the newest version. Will see what's up.
For now please use the following system or add the bot through the Minecraft main menu as outlined in the README tutorials section.

**Comment by henrydarklordofdeath** [comment]
Mcmain
-------- Original message --------From: Matthew Hafner ***@***.***> Date: 12/5/24  6:19 AM  (GMT-08:00) To: Pugmatt/BedrockConnect ***@***.***> Cc: henrydarklordofdeath ***@***.***>, Author ***@***.***> Subject: Re: [Pugmatt/BedrockConnect] Still using old following system  (Issue #554) 
Which bot are you using? BCMain & BCMain1 are on the newest version of MCXboxBroadcast, they should already have support for this.

**Comment by Pugmatt** [comment]
Okay should be working now. Bot was hitting some rate limits due to too many pending friend requests. Appears to be working now when adding through the add friend button.
