### ISSUE TITLE
Connection time out

### ISSUE THREAD

**Issue by LittleSshooter** [Pugmatt/BedrockConnect#57]
Just wondering will this be fixed by tomorrow some time for xbox?

**Comment by Pugmatt** [comment]
No current ETA, but working on it.

**Comment by LittleSshooter** [comment]
OK thanks, hopefully not too long but then again i don't know how this stuff works

**Comment by TomTje** [comment]
I would also be very happy if there is a quick solution.  :) we need it to gamble, otherwise the switch will not come to our server :( I hope the best. thanks for your work you are our hero :)

**Comment by Pugmatt** [comment]
BedrockConnect is now updated to 1.16! Thank you for everyone's patience. Keep in mind there a good amount of servers out there that are not 1.16 yet, so it's not going to work for all servers until they update as well.

**Comment by ismay** [comment]
> BedrockConnect is now updated to 1.16! Thank you for everyone's patience. Keep in mind there a good amount of servers out there that are not 1.16 yet, so it's not going to work for all servers until they update as well.

Awesome, thanks for the hard work and sharing this with the community 💪
