### ISSUE TITLE
Hows the progress so far? any news on an time?

### ISSUE THREAD

**Issue by LittleSshooter** [Pugmatt/BedrockConnect#58]
Just wondering

**Comment by Tristan7s** [comment]
He will update us when he has something to update us on :) patience friend no point in rushing him, as I'm sure he is doing what he can.

**Comment by Nixdorf96** [comment]
Just wondering if there is any possibility to make a donation for Pugmatt? I would like to thank him for his effort and maybe help to keep up the motivation.

**Comment by jangro** [comment]
Here's his paypal. https://www.paypal.me/Pugmatt Throw him a few bucks and put your money where your mouth is. You don't realize what you've got until it's gone.

I just did with this note. Thanks for the efforts, Matt.

> Hey Matt. You've made it possible for my whole family to play together on our own server through COVID lockdowns, with switches, iphones and xboxes alongside PCs. I didn't realize you were behind it until I dug into what was wrong with the 1.16 update. We're all hoping that you'll get things working again after the update. If not, well, it was a good run and it'll be back to realms for us. Either way, thanks for the service.

**Comment by Nixdorf96** [comment]
Great, thanks @jangro.

> Hey Matthew,
> thank you very much for your great work.
> Because of you, I was able to have such a great time playing Minecraft together with my switch friends.
> Looking forward to play again soon. And if not, thanks for everything nonetheless. You're amazing!
> Best regards

Who's next?

**Comment by YaYa21618** [comment]
Thanks Matt! You've really helped make Minecraft more accessible and enjoyable for so many of us Xbox users!! Keep up the great work!

**Comment by Hazzard13** [comment]
BTW, there's no speculated release date, but Pugmatt has confirmed in a [pinned youtube comment](https://www.youtube.com/watch?v=zalT_oR1nPM) that he's already working on 1.16 support.

**Comment by IcyElectro** [comment]
Hey! I just wanted to say, the Bedrock Staff from the Build The Earth 1:1 project are really excited for your 1.16 update; As we will be using BedrockConnect in order for console players to access our server! If you want reference as to what our project is, here is our discord and a reference video to see some of our past hype: [Discord](https://discord.gg/3mrQBYd) [YouTube Video](https://www.youtube.com/watch?v=0eyyuNvKNzw)

**Comment by Pugmatt** [comment]
Thank you very much for your patience guys. Thank you for the donations as well, I appreciate it, but don't feel compelled to do so. The project currently depends on a library that is also in progress of getting itself working for 1.16. I've been trying my best to get it working none of the less with what the library has so far. I will be continuing to try to get it working, thank you for your patience.

**Comment by Higgins4k** [comment]
Hey does anyone know if I setup my own DNS setup through the steps on the bottom will it work with 1.16 or is it something he has to go update within the code

**Comment by Pugmatt** [comment]
The code itself is being updated.

**Comment by Nagol12344** [comment]
the server protocol he's using is not fully updated for 1.16 and there's a bug so we have to wait for the thing to fix itself you can learn more about it and it different issue #54 I will mention it here basically what's happening is that the code isn't fully upgraded that he's using to run the server and it doesn't support 1.16 at all it just crashes you would need to wait for the upgrade for that's what we're all doing

**Comment by MrSpidercat** [comment]
will it eventually be fixed or is it impossible

**Comment by Pugmatt** [comment]
BedrockConnect is now updated to 1.16! Thank you for everyone's patience. Keep in mind there a good amount of servers out there that are not 1.16 yet, so it's not going to work for all servers until they update as well.

**Comment by D3ATHBRINGER13** [comment]
Wow, surprised you were able to get it to work without changing any of the code
Unless you have just not pushed the changes to github

**Comment by D3ATHBRINGER13** [comment]
Especially since nukkitx/protocol hasn't finished updating yet, which you seem to use a lot

**Comment by ismay** [comment]
> Hey does anyone know if I setup my own DNS setup through the steps on the bottom will it work with 1.16 or is it something he has to go update within the code

No that this is necessary now that the 1.16 compatible version has been released, but yeah this is what I did. I set up a dns server that redirects the server URLs to my own bedrock server. For a future update that's what you could do. It's not as flexible as bedrockconnect, but it does allow you to point users to your server.

**Comment by Ztratuz** [comment]
Pugmatt you're a fvking God

**Comment by Pugmatt** [comment]
> Wow, surprised you were able to get it to work without changing any of the code
> Unless you have just not pushed the changes to github

I just haven't pushed the code yet. I'll probably push it into a new branch, since right now it's a bit weird to setup and I need to clean some code up. The Protocol library isn't technically completely read yet for 1.16, but it had enough done for BedrockConnect work.

**Comment by D3ATHBRINGER13** [comment]
Nice

**Comment by YaYa21618** [comment]
Thank you so much, PugMatt!! You’re awesome!
