### ISSUE TITLE
Serverlist not showing after changing DNS [Switch] [1.14.1]

### ISSUE THREAD

**Issue by AlexCreeper25** [Pugmatt/BedrockConnect#6]
So I Just tried to do the DNS procedure with my Nintendo Switch, but it doesnt work: after i did it, i open minecraft and go in the serverlist but no servers are shown, just a text that says that I cant play multiplayer without a microsoft account, but i checked and i was logged in. If i put back the automatic DNS it will show the servers again.

**Comment by Pugmatt** [comment]
What DNS server do you have the Secondary DNS?

**Comment by AlexCreeper25** [comment]
I set it to the google dns as shown in the video

**Comment by AlexCreeper25** [comment]
Nevermind I just restarted the console and now it works :)
