### ISSUE TITLE
[idea, if possible] intercept player connecting to multiplayer world.

### ISSUE THREAD

**Issue by KingTheGuy** [Pugmatt/BedrockConnect#60]
ok lets say you have a server running on your pc, and then also have a multiplayer world open on the same pc. what i'm thinking is to intercept anyone trying to connect to the multiplayer world and have them get taken into the server instead. so basically the multiplayer world is simply there to let console players join the server without having to do anything themselves, all they do is friend the user hosting the multiplayer world and join through them, server intercepts the connection and the player joins the server instead. 
(ive had this idea for a long time now, but i know very little about networking)

if this made no sense let me know, and ill try to reword it.

**Comment by Nagol12344** [comment]
it makes sense yes that would might work except as I do not support the command no be able to use with this so it might work it might not but it does make sense

**Comment by Bhuemann** [comment]
I believe all platforms can automatically see a server if its connected on the same LAN. So something like this is not needed.

**Comment by KingTheGuy** [comment]
> I believe all platforms can automatically see a server if its connected on the same LAN. So something like this is not needed.

the point is for people out side of your network to be able to join.. anyways you missed the point.

**Comment by Bhuemann** [comment]
Well that has a very low chance of that working. The way Pugmatt does it using DNS redirection would be the best way.

**Comment by ismay** [comment]
> I believe all platforms can automatically see a server if its connected on the same LAN. So something like this is not needed.

I believe Nintendo switch doesn't allow this. That's why I'm using this library. If you want to use LAN crossplay to allow people to connect to a server you can use https://play.google.com/store/apps/details?id=com.luzenna.mineproxydroid&hl=en_US, which works for PS4 and Xbox players on bedrock.
