### ISSUE TITLE
hive does not connect

### ISSUE THREAD

**Issue by Nagol12344** [Pugmatt/BedrockConnect#61]
when I try to connect to the hive it doesn't connect it doesn't try to do anything it just stays and sits HELP PIZ

**Comment by Pugmatt** [comment]
Appears to be working fine on my side. What does it say on the screen it gets stuck on?

**Comment by Nagol12344** [comment]
I don't get stuck in any screen your server does not try to connect I'm just stuck in your server without the list

**Comment by Pugmatt** [comment]
Sounds like a bad connection. If it continues to happen you can try to setup BedrockConnect locally: https://www.youtube.com/watch?v=AW5X7-qnvLk

**Comment by Nagol12344** [comment]
I can't run that because I don't have a computer to run it on I'm using a Chromebook right now
