### ISSUE TITLE
Momentary Fix for Connecting to Servers

### ISSUE THREAD

**Issue by CodeAX2** [Pugmatt/BedrockConnect#62]
Hey everyone! I know we are all waiting in anticipation for NukkitX protocol to be updated so that BedrockConnect can also be updated. Until then, I have actually devised a workaround that allows you to connect to any server/port you want. Unfortunately, it does require quite a bit of technical knowledge (and access to a linux server), but it does work. 

Here's how:

First, you need a linux server (or possibly some other software will allow this, not sure, worth looking into)
The server's primary function is to route any connections on the port 19132 (default bedrock port) to a different ip address and port. 

Next, you also need mod0Umleitung (the program used in Pugmatt's videos for self-hosting the DNS server).
In the conf file, you need to point the main Bedrock server addresses (mineplex, the hive, etc.) to point to the linux server. Then you run the DNS server, use it on your console, and any requests to mineplex, the hive, etc. will get forwarded to the linux server, which then forwards to the actual server you want to connect to.

Obviously, this has some downsides to it. For starters, you need access to a pc to run mod0Umleitung, and a linux server to handle the iptables that allow forwarding to a different ip and port. You also are only able to connect to one specific server by using this method, but you can easily change which server you connect to by modifying the iptables of the linux server.

IF YOU DO NOT HAVE ACCESS TO A LINUX SERVER, THERE IS STILL SOME HOPE:
If the server is hosted on port 19132, you do not need the linux server at all (since it is used for changing the port). Therefore, all you need is the IP address of the server (I do not believe a domain such as play.myserver.com works, I believe it must be an IP address based on my testing).

Hopefully this is clear enough, if you have questions or need help setting anything up, let me know.
Or if you find a way around needing a linux server, also let me know.

BTW, this is just a temporary solution, and obviously once NukkitX Protocol and BedrockConnect are updated, this will not needed, but figured it is helpful either way.

**Comment by Pugmatt** [comment]
Hey, I appreciate the thought into this post, but BedrockConnect has already been updated to 1.16 since last night. :) This post should come in handy though in future updates in the occasion where it takes a while to update BedrockConnect again.

**Comment by CodeAX2** [comment]
Oh wait, when did it update? I don't see any commits on the master branch?

**Comment by Pugmatt** [comment]
I haven't pushed the code yet, but the public DNS is updated and JAR is released: https://github.com/Pugmatt/BedrockConnect/releases/tag/1.5

**Comment by MikePerreman** [comment]
> Hey, I appreciate the thought into this post, but BedrockConnect has already been updated to 1.16 since last night. :) This post should come in handy though in future updates in the occasion where it takes a while to update BedrockConnect again, so I'll keep this open.

Thank you!

**Comment by CodeAX2** [comment]
How did you manage to use the unfinished version of the Protocol library? I couldn't figure out for the life of me how to impliment their feature-1.16 branch?

**Comment by Pugmatt** [comment]
Lots of tinkering with the packets, and also the feature-1.16 is technically behind on current changes, they have a pull request going with the current changes.
