### ISSUE TITLE
More port forwarding for Xbox One?

### ISSUE THREAD

**Issue by chuffrey4** [Pugmatt/BedrockConnect#64]
I have port forwarded 19132 on my server and router, been able to connect from cellular on iOS and my PC using the public address, however I haven't been able to connect from Xbox using anything other than the local IP of my server, is there some other port I must open for the server.

**Comment by lukemagdalin** [comment]
have you allowed the bedrock connect through the firewall?

**Comment by Pugmatt** [comment]
Just to clarify, you have a BedrockConnect server running, and a DNS server running? Or are you trying to connect to the BedrockConnect serverlist through LAN.

**Comment by chuffrey4** [comment]
I used your BedrockConnect DNS server, my own server publicly hosted, but I was able to get it working only by switching the port to 19133

**Comment by Pugmatt** [comment]
Yeah, if you have a Minecraft server and BedrockConnect hosted on the same network, the Minecraft server's port will need to be changed, as they can't be on the same port and BedrockConnect needs to be on port 19132.
