### ISSUE TITLE
We had some trouble receiving your player data 

### ISSUE THREAD

**Issue by iop34** [Pugmatt/BedrockConnect#65]
![914B0A79-2B09-42B7-A770-6BBF407484B9](https://user-images.githubusercontent.com/64849905/86497756-cb23c400-bd7a-11ea-8703-cdaa14bc0cad.jpeg)

**Comment by iop34** [comment]
I am using the lan version of bedrock connect

**Comment by iop34** [comment]
I also get a error saying cannot locate java I don’t know the exact error message when trying to use this command on my Mac terminal after install java -jar BedrockConnect-1.0-SNAPSHOT.jar nodb=true

**Comment by Pugmatt** [comment]
What version of Java are you currently using to run the jar?

Also, that error should only show when in database mode of the software. If you don't have a MySQL server running and have the server running in database mode, it will throw that error. If you don't have a MySQL server and are just trying to run the program without a database, you need to launch it in nodb mode in your command parameters, as such:

`java -jar BedrockConnect-1.0-SNAPSHOT.jar nodb=true`

**Comment by iop34** [comment]
When I try to use that command it say Error: unable to access jarfile BedrockConnect-1.0-SNAPSHOT.jar also I’m using java 8

**Comment by Pugmatt** [comment]
Is your BedrockConnect jar named BedrockConnect-1.0-SNAPSHOT.jar? If not, be sure to rename it to that, or specify the other name in the command.

**Comment by iop34** [comment]
It is the default name

**Comment by Pugmatt** [comment]
Not really sure then. The " unable to access jarfile" typically means that the file name in the run command doesn't match the name of the JAR you're trying to run.
