### ISSUE TITLE
Can't connect with xbox 

### ISSUE THREAD

**Issue by 128912891289** [Pugmatt/BedrockConnect#66]
My friend tried to use BedrockConnect to join my Java server. The first time we tried, he was unable to join any servers. The second time we tried He was able to join, but it didn't popup the server list when he tried to join. I was able to get my friend to join my server on Pocket Edition 1.16 as well, even Windows 10. I've followed this tutorial and the suggestions from the comments section: https://www.youtube.com/watch?v=g8mHvasVHMs but it didn't seem to help. (I tried with some other tutorials as well, but they basically went over the same information. We tried making both ipv4 dns 104.238.130.180, but that didn't make a difference. Thanks for your help!

**Comment by suerion** [comment]
Do you know, Bedrock Connect is not Geseyr, it could not make an bridge from Bedrock to Java, you need to add an proxy, they would add this bridge.

**Comment by suerion** [comment]
https://github.com/GeyserMC/Geyser

**Comment by 128912891289** [comment]
I know. Like I said I've already set up Geyser. I was able to get people to connect from Windows 10 Edition and Pocket Edition. The issue is not about the server, but setting up BedrockConnect. With Xbox, he was not able to connect to any other bedrock servers as well because there was no servers list when he set up BedrockConnect.

**Comment by Pugmatt** [comment]
If your friend has double-checked the DNS to make sure it's 100% correct, they can also try setting up a local solution: https://www.youtube.com/watch?v=AW5X7-qnvLk

If nothing works, it might unfortunately be this issue: https://github.com/Pugmatt/BedrockConnect/issues/25

**Comment by 128912891289** [comment]
He does not have access to a computer. Is there a more simple solution that could be done for users with just Xboxes?

**Comment by Pugmatt** [comment]
If they have an Android phone, they can try this method: https://www.youtube.com/watch?v=b8cRB88U6wY

It's a tutorial for PS4 but also works for Xbox. Past that there's nothing that can be done really unfortunately. The issue with the original DNS method could be this: https://github.com/Pugmatt/BedrockConnect/issues/25 Which I haven't seen a solution for.
