### ISSUE TITLE
Source code for version 1.5 is not available

### ISSUE THREAD

**Issue by MFeldpausch** [Pugmatt/BedrockConnect#67]
The source for BedrockConnect version 1.5, with support for Minecraft Bedrock version 1.6, is not available.  It is not in the `master` branch.  Downloading the "Source Code" package from the Releases page just gets from the Master branch.

Steps to Reproduce
---
1. Download the "Source Code" zip file from the releases page.
2. Extract it.
3. `cd` to the "serverlist-server" directory
4. `mvn package`
5. Run the serverlist with `java -jar target/BedrockConnect-1.0-SNAHOT.jar nodb=true`
6. Try to join from a 1.16 client
7. Get error `java.lang.RuntimeException: Unable to inflate buffer data`
    - Having worked with the NukkitX library, I know this means you are joining a 1.15 server from a 1.16 client.

Expected Behaviour
---
Downloading the source and building should be pretty much the same as just downloading the pre-built jar.

Required Steps
---
Upload the latest code to the `master` branch, or create a new branch for version 1.5

**Comment by Pugmatt** [comment]
1.5 source has now been pushed to master branch.
