### ISSUE TITLE
Galaxite

### ISSUE THREAD

**Issue by shyth** [Pugmatt/BedrockConnect#70]
Hey i was hoping you could add galaxite to the list as it wont let me join galaxite through the menu. It doesnt even take me to bedrockconnect throught it. Other server do though. Thanks!

**Comment by MattElekHarris** [comment]
It seems Galaxite's domain is simply "play.galaxite.net"

**Comment by Pugmatt** [comment]
Galaxite is now on the list, and should be redirecting to the serverlist as well from the Featured Servers.
