### ISSUE TITLE
Can't Connect to Xbox One

### ISSUE THREAD

**Issue by ArchiMageOcelot** [Pugmatt/BedrockConnect#73]
Hi! Thanks for updating to the 1.16 version, I was able to join when the update was out but... Since the last patch that Microsoft updated Minecraft to 1.16.1 now I can't even see the option to join or be able to use Bedrock Connect, I hope I could get something for it to work again please.

Thanks.

**Comment by Pugmatt** [comment]
Can you expand what you mean by "I can't even see the option to join or be able to use Bedrock Connect"? Does the Featured Server list show at all, and if so does it just lead you to the regular servers?

**Comment by ArchiMageOcelot** [comment]
Exactly, it doesn't appear the option to join external servers, I've done the DNS IPv4 configuration in the Xbox settings and still doesn't let me again...

**Comment by Pugmatt** [comment]
If it doesn't show an option to join any Featured Servers, that another issue entirely. Might need to reboot Minecraft or your Xbox a couple of times, and the Featured Server list should show again, that's a bug with Minecraft itself unfortunately.

**Comment by Pugmatt** [comment]
If you have a computer, you can try hosting BedrockConnect locally, and joining the BedrockConnect serverlist as a LAN server: 

- On PC, Mac, or Linux, download this JAR: https://github.com/Pugmatt/BedrockConnect/releases
- Make sure you have Java 8 or higher installed.
- In command prompt or terminal, run the following command:
```java -jar BedrockConnect-1.0-SNAPSHOT.jar nodb=true```

When in Minecraft, go to the "Friends" tab, and the server should be showing under LAN servers and available to join.

Past that, there's really not much else that can be done.

**Comment by ArchiMageOcelot** [comment]
Oh, okey I'll try that, thanks!!!

**Comment by DoctorMacc** [comment]
At Geyser we've gotten a startling amount of users saying it doesn't work, and that mostly seems to be on Xbox.

**Comment by CrazyBrick15** [comment]
Want to throw in too - Switch is not working either. Stuck on external server loading until it times out

**Comment by Pugmatt** [comment]
Make sure you have updated the game to 1.16.2. A new version was released that required BedrockConnect to be updated, so if your game version is still on 1.16.1 it won't work.

**Comment by arbosus** [comment]
i just updated the switch to 1.16.2 and it freezes at random time while connected mostly when selecting the external server but sometimes at the generating world Done! screen before getting to the server list
