### ISSUE TITLE
Readme Changes

### ISSUE THREAD

**Issue by igbopie** [Pugmatt/BedrockConnect#74]
This is an awesome project and great docs! however, it is pointed out that using a custom DNS is not dangerous. I would suggest modifying this line as one can easily do a Man In The Middle attack providing another set of IPs, for example Microsoft authentication. Then you can grab username and password.

I trust that the IPs you posted are safe, however, there is a lot of youtube content and it is easy to create a malicious website. 

Do you think you can mention something about this in the wiki?

I really appreciate the effort you are putting into this, and I hope my words don't ruin the enthusiasm. 

Thank you!

Example: https://blog.usejournal.com/man-in-the-middle-dns-spoofing-df77ab2cae35

**Comment by Pugmatt** [comment]
This is a good point, didn't think of this. I've modified the README to correctly state this. I want to be as open as possible with everyone about the project, so I appreciate the information.
