### ISSUE TITLE
Version 1.16.1 support

### ISSUE THREAD

**Issue by iop34** [Pugmatt/BedrockConnect#75]

**Comment by Pugmatt** [comment]
Already has 1.16.1 support. Try the following troubleshooting if it isn't working for you:

- Check if the DNS is 100% correct
- Check if your current connected network still has the DNS settings
- Restart Minecraft multiple times, sometimes the DNS settings takes a while to set
- Restart your game console
- Make sure the server you're connecting to from the serverlist is Bedrock Edition, not Java edition.
- If it still doesn't work, wait 5-10 minutes for the DNS Cache to clear

If it still does not work, you can try setting up BedrockConnect locally: https://www.youtube.com/watch?v=AW5X7-qnvLk

**Comment by iop34** [comment]
Ok thanks for the reply
