### ISSUE TITLE
Nicknames for servers

### ISSUE THREAD

**Issue by abayliss** [Pugmatt/BedrockConnect#77]
I'm trying to use BedrockConnect to set up a few servers at home for my daughter to play on on Switch, and it would be great if I could add nicknames to the entries in the list so she could pick "Creative World 1" rather than "10.0.0.64:19133".

**Comment by kmpoppe** [comment]
This is now "quasi" possible, when you host your own server list server (as of release 1.6.1).
But I would also think it's a nice idea for the non-self-hosted servers.

**Comment by kmpoppe** [comment]
Related #173

**Comment by kmpoppe** [comment]
Took a good hard look this morning. Currently, the servers that users can add manually (those, that not get added via the custom servers JSON) only consist of DNS-name/IP-address and Port in one string, thus a complete overhaul in the way servers are saved for users will be needed, also with ensuring backwards compatibility.
I currently don't have the time to create a PR for such a large change.
@Pugmatt You wouldn't be bored right now ;-)?

**Comment by Pugmatt** [comment]
It's been on my to-do list for a while, I just never got to it, mostly because like you said it would require a change to how servers are saved, and how current servers that are saved. Shouldn't be too hard though. I'll take another look and see what I can do.

**Comment by Pugmatt** [comment]
Setting custom/display names when adding servers has now been pushed to the main instance, and latest release.
