### ISSUE TITLE
Add to Server List toggle option

### ISSUE THREAD

**Issue by EthanWeegee** [Pugmatt/BedrockConnect#79]
What does it do? Does it add servers to the server list world, or the servers list of the game menu? Does it work without the spoof DNS active? If so, does this mean the spoof DNS can be used only temporarily?

**Comment by joshuaxlino** [comment]
> What does it do? Does it add servers to the server list world, or the servers list of the game menu? Does it work without the spoof DNS active? If so, does this mean the spoof DNS can be used only temporarily?

1. On xbox and Switch, it should add to the game, but will also add to the servers list world. The server list world reflects which servers are saved to your device. 2. It does work without the spoof DNS, watch the creators tutorial as he teaches you to setup and use your own DNS. 3. Your own DNS file will need to be loaded into another app every time you wish to start the server. This is also within the same tutorial the creator made.

**Comment by EthanWeegee** [comment]
A friend, who I am helping set this up, says that nothing appears in the game's server list. I ran the world on the Android port and can't reproduce that, but it also doesn't hide the server adding functionality. Is this expected behavior?

**Comment by joshuaxlino** [comment]
> A friend, who I am helping set this up, says that nothing appears in the game's server list. I ran the world on the Android port and can't reproduce that, but it also doesn't hide the server adding functionality. Is this expected behavior?

Depending on your device, it will appear in the 'friends' tab as a lan world. It will always show server adding if your computer is on with the .jar file running.

**Comment by EthanWeegee** [comment]
Oh, my bad. I meant that they are connecting to the version you've hosted with your DNS and such. No LAN in that case.

**Comment by kmpoppe** [comment]
"Add to server list" can only add the server data you've entered to the list of servers that is provided by the Server List Server. It has no access to the in-game list of "featured servers".
This issue is quite old, I guess this can be closed now.
