### ISSUE TITLE
Nintendo Switch - Game Freezes when trying to connect to server via the server list.

### ISSUE THREAD

**Issue by spikehidden** [Pugmatt/BedrockConnect#81]
Nintendo Switch OS version: 10.1.0
Minecraft Version: 1.16.20

### Steps to reproduce:

1. Connect to the server list server
2. Choosing the server I want to join
3. Game freezes
4. If I then leave and enter the game again the Nintendo Switch freezes too.

I also tried it on my PC with the WIndows 10 Version but it works fine there.

I know nothing about programming but I think that this is intended by Mojang since it seems to only effect one device which also doesn't officially support other servers besides the featured ones. It also could be a bug but that has to mean that the featured servers would also be affected (which I didn't test but will).

**Comment by Pugmatt** [comment]
Currently looking into this. It's seems to crash for me for every server I try to join from the BedrockConnect server list, and does seem to only happen on Switch. I don't think it's intended by Mojang, but who knows. Running some tests and will let you guys know.

**Comment by Pugmatt** [comment]
I took out the DNS out of my Switch WiFi settings, and tried to join a featured server like normal without the BedrockConnect DNS enabled. And my game actually froze. I did some research, and this is a issue that Mojang is aware of: https://bugs.mojang.com/projects/MCPE/issues/MCPE-95621?filter=allopenissues

Unfortunately, we'll have to wait and see when Mojang fixes this.
