### ISSUE TITLE
Nintendo Switch - 1.16.21 patch problem

### ISSUE THREAD

**Issue by JacekSzym** [Pugmatt/BedrockConnect#82]
After 1.16.21 update, server's tab shows  "coming soon". I have removed the DNS and servers appear and I can join them but server list don't appear ofc.

**Comment by BuyMyMojo** [comment]
I'm having the same issues now, I was able to log onto a bedrock server once last night and then every subsequent time after choosing the server in the list it ended up getting a "could not connect" error and now today it's just display Coming soon no matter how much a restart the game or my login.

**Comment by Pugmatt** [comment]
Might just be a bad connection to the BedrockConnect DNS then, I would recommend setting up a local instance if you haven't already: https://www.youtube.com/watch?v=AW5X7-qnvLk

**Comment by krystalflame** [comment]
I'm also having the same issue with my Switch. However, it did work yesterday. Is there any steps I should take to try and fix this?

**Comment by JorgeJimenez15** [comment]
It seems that the BedrockConnect server is shut down

**Comment by Pugmatt** [comment]
I gave the server a reset, should be back up and running.

**Comment by JackTheFoxOtter** [comment]
I'm having the same issue, just bought myself the Switch edition, Server List says "Comin Soon" after switching DNS1 to your BedrockConnect DNS server IP. Did Mojang blacklist you?

**Comment by dutchddv** [comment]
I have the same problem  last night  it worked and now i have only "coming soon"

**Comment by dutchddv** [comment]
For everyone have this issue try to change your secondary DNS to a another secured public DNS. This fixed by my the problem

**Comment by lgrass** [comment]
I tried a couple different secondary DNS servers and it still didn't work.  I guess I wouldn't mind trying to follow that youtube video to set it locally, but it makes me nervous a little bit.  Is the locally installed version (or the non local one for that matter) of this working for anyone else right now?

btw thanks a ton for doing this! We invested a lot of money into switches and bedrock to play with family and friends on a private server and have ran into soooo many issues.

**Comment by Pugmatt** [comment]
The server was having some issues in the past hour, I gave it a reset just now. Try it again and see if it works.

**Comment by minerj101** [comment]
I have a friend that when he tried to add a server he would get disconnected from the server.

**Comment by Sparrowitch** [comment]
> After 1.16.21 update, server's tab shows "coming soon". I have removed the DNS and servers appear and I can join them but server list don't appear ofc.

Same problem, how to fix it?

**Comment by Pugmatt** [comment]
> > After 1.16.21 update, server's tab shows "coming soon". I have removed the DNS and servers appear and I can join them but server list don't appear ofc.
> 
> Same problem, how to fix it?

It's a Minecraft bug, so you might have to restart Minecraft a couple of times. If it continues, you can also try settings the Secondary DNS to one of the following:
- 8.8.4.4
- 1.1.1.1
- 1.0.0.1
