### ISSUE TITLE
Suggestion: UI Redesign

### ISSUE THREAD

**Issue by DespicableKee** [Pugmatt/BedrockConnect#83]
The current ability to be able to play servers on consoles is great, but it seems fo be english-only. In order to make it both all language and look a bit nicer, you should consider making some alterations to custom servers. Make it look like the vanilla UI, with an edit button next to the server, for example. That way, you can remove the "Remove a Server" button, and add it to the edit server UI instead, as well as the ability to change the server name, and obviously to save.

**Comment by Pugmatt** [comment]
As far as I know having buttons side by side in a row isn't possible with Minecraft's server UI form packets. You're only able to currently display the buttons in columns, from what I've seen looking at the packet data and other servers that use custom forms. If anyone has an example of a server having buttons on the sides a buttons, I'd be happy to investigate more.

As for support for more languages, this is something I can eventually look into.

**Comment by DespicableKee** [comment]
I am not that familiar with how form UI works, so I don't know if what I said is possible. I'd assume that there is some way to make custom UI like how json works, but I am currently not aware if there is any way to use json for UI rather than the standard form UI.
I assume it's technically possible, but it would likely require coding your own plugin. You could still technically experiment with a server editing UI, by making server buttons take you to another UI where you can edit, remove, or connect.

**Comment by Pugmatt** [comment]
The BedrockConnect software is a custom coded server, so it's using the bare bones of what a Minecraft Bedrock server is capable of in terms of UI. 
In terms of editing servers, this is a feature on the to-do list.
