### ISSUE TITLE
PS4 minecraft lan game not showing up

### ISSUE THREAD

**Issue by sarasagbf** [Pugmatt/BedrockConnect#86]
Thank you for your wonderful development and release.

I hadn't been able to sign in to PS4's Minecraft for about two months with my Microsoft account.

I signed in successfully today, so I tested Bedrock Connector on PS4.

However, I could not see LAN GAME on the PS4 side when I started Bedrock Connector on a PC on the same network.

*I also tried disabling the firewall and antivirus software, but I could not see LAN GAME on the PS4 side.

Is this caused by Bedrock Connector's inability to support PS4's Minecraft 1.16.40?

Or is it just my own environmental problem?

Or Ps4 Minecraft Removed Lan game..?

![screen](https://user-images.githubusercontent.com/40536261/92276802-ac81ab00-ef2c-11ea-8046-10bbae173b81.png)

**Comment by Pugmatt** [comment]
As far as I know, other PS4 players have gotten this to work on 1.16.4, here's a video from a few days ago of someone joining the public BedrockConnect serverlist using an android app: https://www.youtube.com/watch?v=9xtHFGRJ_7E

I think with PS4 you will need Playstation Plus, if you don't have that already.

**Comment by sarasagbf** [comment]
I tried it after first post and I could connect.(So I understood that not removed "LAN GAME".)

Everyone who playing in my server doesn't play it on PS4 (except me)

So this problem is not important for me now.

Anyway , thank you for reply about another way.:)
