### ISSUE TITLE
Stuck on connect to external server

### ISSUE THREAD

**Issue by lifegame1lu111** [Pugmatt/BedrockConnect#87]
Hi, i am having trouble connect could you please give the dns a restart?
im on switch and its stuck on connect to external server

**Comment by Technoguyfication** [comment]
Are you following this tutorial? https://www.youtube.com/watch?v=zalT_oR1nPM

**Comment by lifegame1lu111** [comment]
yes its fixed already

**Comment by Technoguyfication** [comment]
> yes its fixed already

Can you go ahead and close this issue if the issue is resolved please?
