### ISSUE TITLE
Can't see "Join to connect to server list" MOTD on the server / Only some servers take me to the BC Server.

### ISSUE THREAD

**Issue by MattJGH** [Pugmatt/BedrockConnect#88]
When you connect the DNS on the game console, Only some of the servers pass through the DNS. The ones without an motd work, while the ones with the motd for the original server doesn't. The servers that work are completely random each time and it does the same on the public DNS. I think it may be because the conf it generates is missing some ips, because according to https://minecraft.gamepedia.com/Featured_servers , some ips are different. Thanks for any help!

**Comment by Pugmatt** [comment]
Added updated domains to DNS file generation code in latest commit.
