### ISSUE TITLE
Unable to connect to world

### ISSUE THREAD

**Issue by kingelectrixgyt** [Pugmatt/BedrockConnect#89]
My Nintendo switch lite minecraft wont let me connect to the servers list on your dns server and i haveinternet with your dns code and googles dns as secondary dns

**Comment by QPCrummer** [comment]
My friend is having the same exact problem, except for he is on Xbox one.

**Comment by QPCrummer** [comment]
He is trying to connect to my server through Bedrock Connect, then through GeyserMC. This is the only way for him to play with me

**Comment by kingelectrixgyt** [comment]
@Pugmatt Please Help

**Comment by QPCrummer** [comment]
@Pugmatt  We really need this fixed. My server lives off of this.

**Comment by surprise0451** [comment]
I’m having the same issue on Nintendo Switch.

**Comment by QPCrummer** [comment]
I think the server was just down. Seems to be working now.

**Comment by kingelectrixgyt** [comment]
Solved

**Comment by kingelectrixgyt** [comment]
its doing it again
