### ISSUE TITLE
Trying to click any menu just kicks me

### ISSUE THREAD

**Issue by j5155** [Pugmatt/BedrockConnect#90]
So I was testing this on windows 10 by just manually adding the IP and it works fine, except whenever I click on any of the menu options, I get kicked for "Exiting server list". Is this a bug or should I just be on console?

**Comment by Pugmatt** [comment]
This has happened occasionally I think for some people. I tested just now on windows 10, and I was actually able to replicate this a couple of times. But when I joined again a third time, it wouldn't happen again, so seems to only happen sometimes. I'm assuming though you have attempted to get through multiple times?

**Comment by j5155** [comment]
yes

**Comment by Pugmatt** [comment]
Sorry the for long wait on this. Latest release should now have fixed this with the introduction of the Exit server button. Old method of exiting the serverlist by closing the main form was causing issues that caused this.
