### ISSUE TITLE
I have a friend that when he tried to add a server he would get disconnected from the server list.

### ISSUE THREAD

**Issue by minerj101** [Pugmatt/BedrockConnect#92]
I made a server for my friend group to join and one of my friends are on xbox. He can get to the server list, when he tries to add a server it disconnects him from the server list

**Comment by Pugmatt** [comment]
Currently an issue I'm looking into. Seems to have randomly. Rejoining and retrying a couple of times typically seems to work.

**Comment by Pugmatt** [comment]
Sorry the for long wait on this. Latest release should now have fixed this with the introduction of the Exit server button. Old method of exiting the serverlist by closing the main form was causing issues that caused this.
