### ISSUE TITLE
No internet connection on switch

### ISSUE THREAD

**Issue by pokemonplayer101** [Pugmatt/BedrockConnect#94]
When ever i change the DNS settings on my switch i won't let me connect to the internet sorry if i'm wasting your time :(

**Comment by Pugmatt** [comment]
Try a different DNS address for the Secondary DNS, such as one of the following:
- 8.8.4.4
- 1.1.1.1
- 1.0.0.1

**Comment by pokemonplayer101** [comment]
I have done that but still no connection and I would try bind because i use linux but i don't know how it works or even what to do.

**Comment by Pugmatt** [comment]
I have a short document here for Linux: https://github.com/Pugmatt/BedrockConnect/blob/master/BIND_Install.txt

I'll write a more detailed guide in a bit.

**Comment by pokemonplayer101** [comment]
thank you also i accidentally closed the issue
