### ISSUE TITLE
Xbox one issue

### ISSUE THREAD

**Issue by cookelg** [Pugmatt/BedrockConnect#95]
I input the correct dns address into the Xbox setting, I have network connectivity, but when I open a server from the default list (I've tried all of them), it does not prompt me with the window that allows me to input a custom server. Did xbox catch on and disable this functionality? Or am I doing something wrong.

**Comment by Pugmatt** [comment]
If you haven't already, try restarting Minecraft and your Xbox a couple of times, as it could be the DNS cache just not clearing.

If it still doesn't work, it could be this issue: https://github.com/Pugmatt/BedrockConnect/issues/25

If this is the case, you could try hosting the BedrockConnect serverlist server locally:

- On PC, Mac, or Linux, download this JAR: https://github.com/Pugmatt/BedrockConnect/releases
- Make sure you have Java 8 or higher installed.
- In command prompt or terminal, run the following command:
```java -jar BedrockConnect-1.0-SNAPSHOT.jar nodb=true```

At this point the serverlist server should be running. Make sure this is also running on the same network as the Xbox. When in Minecraft, go to the "Friends" tab, and the server should be showing under LAN servers and available to join.
