### ISSUE TITLE
Xbox problem

### ISSUE THREAD

**Issue by DankDuck201** [Pugmatt/BedrockConnect#96]
So I just found out about bedrock connect a week or so ago and it was working fine until today. I would go to join the server list and I would either get stuck on locating server forever or it would just say unable to connect to world. I have restarted minecraft and my xbox may times and even turned off ipv6 and it still isn't working. Any suggestions?

**Comment by DankDuck201** [comment]
And actually the same problem has been happening to my cousin on nintendo switch  but he hasnt turned ipv6 off yet.

**Comment by wwboyer** [comment]
+1 on this. I'm currently having trouble connecting on both the Switch and on Windows 10. The server will fluctuate from very low to very high pings (e.g., ~50 to something ridiculous, like 20000 or 40000), and connecting either takes an incredibly long time or just hangs indefinitely. I managed to get my Switch to connect to the server after a long time (not sure exactly how long, but it was definitely more than 15 minutes) where it seemed to work as expected, but trying to connect on Windows 10 has been hanging on "Locating server" for more than 30 minutes now.

**Comment by Pugmatt** [comment]
The server is under super heavy load today, I've never seen this many on the server at once. A YouTuber or someone must have shared the DNS ip. I'll be looking into upgrading the server if this continues.

**Comment by Pugmatt** [comment]
I also gave the server a restart, in case the server is just bugging out.
