### ISSUE TITLE
Cannot Connect To World (Xbox One)

### ISSUE THREAD

**Issue by Keeps64** [Pugmatt/BedrockConnect#98]
After inputting the correct DNS, restarting the console and restarting Minecraft, I am able to load up the server to add or remove servers. At this point, I add a server and attempt to connect to it. It doesn't work, even after a number of extra tries and resets. 
I'm using ipv4, and I've connected to the server I want to play on before. 

Any help would be greatly appreciated! Thank you in advance.

**Comment by Pugmatt** [comment]
Have you confirmed that the server you are trying to connect to is on Bedrock Edition, and not Java edition?

**Comment by Keeps64** [comment]
It is a Java server that I've connected to that has a plug in allowing Bedrock players to join
